### ISSUE TITLE
Custom Keyboard View for Filters

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#1008]
Been toying around with my bank's (Monzo) search feature recently, and I thought it had quite a nice interface for searching and adding different filters

Image for reference, but basically each of the buttons obviously does something a little different. The first one for example (tags) takes you to a secondary page to select a tag to filter on. The same could be done for labels to see all issues in a label, other options (in our world) would be assignee/reviewer, open/closed, stale (unique feature), my issues, by milestone, etc etc

(Ignore the SwiftKey keyboard, that's not part of it!)

![img_0765](https://user-images.githubusercontent.com/15193942/32996957-95e53454-cd81-11e7-8383-96e9748c637e.PNG)

**Comment by rnystrom** [comment]
This is a super cool idea. Hadn’t thought of putting filters in the accessory view. That’s pretty great!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Linking to #287
