### ISSUE TITLE
Expanded cell doesn't update reactions

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#1013]
Found on #1008 - Might be because of the image? Started with cell collapsed, taped to expand but the reaction cell decided he didn't feel like moving

![img_0766](https://user-images.githubusercontent.com/15193942/33009493-fb119244-cdce-11e7-8991-665e60e91c79.PNG)
![img_0767](https://user-images.githubusercontent.com/15193942/33009496-fd63dd22-cdce-11e7-9715-5a240d223b87.PNG)

**Comment by rnystrom** [comment]
@Sherlouk I can't seem to repro this. Can you consistently? What device are you using?

**Comment by Sherlouk** [comment]
@rnystrom Not 100% consistent, but I've had it happen a handful of times - more so now I'm actually noticing it happen 😬

**Comment by rnystrom** [comment]
Still yet to see this or get another report of it. Closing.
