### ISSUE TITLE
Dynamic font support

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#1016]
- [Style](https://github.com/rnystrom/GitHawk/blob/master/Classes/Views/Styles.swift) font sizes should be functions that return a relative font based on system settings
  - e.g. baseline `body` is size 16
- Listen for `UIContentSizeCategoryDidChangeNotification` and:
  - Rebuild all models since `NSAttributedStringSizing` will have the font stored in its `NSAttributedString`
  - Call `listAdapter.reloadData()` to rebuild section controllers

**Comment by rnystrom** [comment]
Should we do this (see: "customization")

https://stablekernel.com/supporting-accessibility-larger-text-in-ios/

Or start using system font descriptor sizes (`.body`, `.headline`, etc)?

**Comment by viktorgardart** [comment]
YES!!!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Yes yes yes! Think the customization would make sense as we can group it all in one place.
