### ISSUE TITLE
Set pronounceable app name to "ghit-hawk"

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#1017]
From #934

**Comment by Sherlouk** [comment]
Think the opposite, it should say "Git Hawk" it already prononunces it "Ghit Hawk". I think breaking it up is enough to get it pronounced correctly!

**Comment by rnystrom** [comment]
Ooooh, I assumed it pronounced it “jit hawk”

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Haha, I think that’s what @Sherlouk means too. It’s pronouncing it JitHawk for me at least (using Daniel / English UK)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Sorry yea it pronounces it Jithawk, if that's how we're going to write it out 😂 Support that makes more sense

**Comment by rnystrom** [comment]
Poking around at it, I actually don't have any problem w/ how its pronounced. If someone has a better idea I'll accept a PR, but it sounds fine to me?
