### ISSUE TITLE
Allow soft-read when opening issues

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#102]
From #36

Put in a setting (`UISwitch`) that sends "read notification" responses when opening a notification.

**Comment by BasThomas** [comment]
Was thinking... would an auto soft-read after commenting make sense? I feel like it does, but it might  be confusing at the same time. 🤔

**Comment by rnystrom** [comment]
Hmm @BasThomas good question. I actually really like this idea. Like you've "actioned" the notification at that point... 

You're on to something. Maybe the rule should be once you perform and action mark as read? Would we still want this setting then?

**Comment by BasThomas** [comment]
Think so, yeah. Just reading might also been an action (for me it quite often is) and would like it marked as read.

**Comment by BasThomas** [comment]
We might want consider other terminology at that point? "Mark as read" vs "mark as actioned"? That would again make it less understandable though...

**Comment by rnystrom** [comment]
My typical workflow (and why I don't auto send reads) is to peek at what the notification content is, then return to it later and actually do something. As soon as it drops off of "unread" I forget about it.

**Comment by rnystrom** [comment]
Done!
