### ISSUE TITLE
Notifications?

### ISSUE THREAD

**Issue by jacc** [rnystrom/GitHawk#1028]
I’ve received multiple notifications on repos, however I cannot see them. Is this a setting i need to turn on?

**Comment by rnystrom** [comment]
@jacc can you let us know what type of notifications? I assume this means you had notifications on GitHub.com but they didn’t show up on GitHawk? Are they in private or org repos? You might need to request access.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jacc** [comment]
oddly enough, this triggered a notification! is it based on mentions?

**Comment by rnystrom** [comment]
It’s anything that the GitHub [notifications](https://developer.github.com/v3/activity/notifications/#list-your-notifications) API will give us! Some examples:

- Mentions
- Activity in Issues and Pull Requests that you’re active in
- Activity in Repositories you’re watching 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jacc** [comment]
ah ok. that makes much more sense. thank you!!
