### ISSUE TITLE
Targeting the wrong secrets in TestFlight

### ISSUE THREAD

**Issue by heshamsalman** [rnystrom/GitHawk#1031]
New phone, new install. 

I think we’re sending the wrong client id or secret because I’m getting a 404 on sign in attempt.

**Comment by heshamsalman** [comment]
![49229ce3-063c-4646-800a-7340845ff53d](https://user-images.githubusercontent.com/3388381/33078481-cf631910-cea0-11e7-9f40-efe8ae952ed0.png)

**Comment by Sherlouk** [comment]
Ryan probably hasn't pushed a new version after he accidentally pushed one without the keys all in (hence the recent work to make it more obvious; so it doesn't happen again!)

**Comment by BasThomas** [comment]
Grats on the X! In the meantime, at least you *can* login with a PAT. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by heshamsalman** [comment]
@Sherlouk thanks for the heads up there, was off the grid for a bit and had a bit of an _oh no_ moment when i re-installed the testflight build

**Comment by rnystrom** [comment]
Ya this was my fault. New build soon!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
