### ISSUE TITLE
Lighter tint for expanded manage area

### ISSUE THREAD

**Issue by joerocca** [rnystrom/GitHawk#1032]
Similar to @rnystrom thoughts for the search filter

https://dribbble.com/shots/2097072-Working-on-new-filters-interactions

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
YES, sounds awesome. I’ll hack at this

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Not doing. Maybe we can explore large colored-in circles behind the icons? Might give the manage buttons more life, and different colors could make it easier to find what you want to do? Let's see if it comes up.
