### ISSUE TITLE
Recent search vs Bookmark cell different heights

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#1037]
Exact same content in both cells (rnystrom/GitHawk) but the bookmark one is a little bit bigger

Only something somebody with mild OCPD would notice but I do think we should try and be as consistent as possible for these things. I would go as far as to say as they should be using the exact same cell. "RepositorySectionController" which is used by both of them

**Comment by rnystrom** [comment]
Can’t unsee. Lets fix.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
😈

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
