### ISSUE TITLE
Image Upload failure always says Rate Limit reached

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#1047]
If the imgur request fails because we don't define the client ID or something else, it'll always say "Rate Limit Reached" which obviously isn't strictly true.

We should show a more appropriate error here so we know the difference!

**Comment by rnystrom** [comment]
@Sherlouk assigning to you since you know the upload stuff best!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Will knock it out later, should be a super small change
