### ISSUE TITLE
Fabric Access

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#1049]
@rnystrom Any chance of the collaborators (of whom want access) could see into Fabric? Be nice to see the 0 crashes in person 😉

**Comment by rnystrom** [comment]
Just invited @Sherlouk @BasThomas @joerocca and @rizwankce. If anyone else wants access let me know! I probably have your email from TestFlight, but if not please DM it to me 😄

**Comment by BasThomas** [comment]
I am going to close this one for now 👍
