### ISSUE TITLE
Replying to comment threads

### ISSUE THREAD

**Issue by alexpyoung** [rnystrom/GitHawk#1053]
Hi,

Wondering if it's possible to directly reply and react to comment threads instead of just the main PR description?

Thanks

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.13.0 (1197)
Device: iPhone X (iOS 11.1.2)
TestFlight: false
</pre>
</details>

**Comment by rnystrom** [comment]
Tracking in #874, we'll be working on this soon!
