### ISSUE TITLE
Migrate IssueReferencedCell to AttributedStringCell

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#1055]
See #864 for how-to. Requires same label/background stuff as #1057.

**Comment by rnystrom** [comment]
Much more complicated cell, punting

**Comment by Sherlouk** [comment]
Sorry, what's so complicated about this cell in particular?

**Comment by rnystrom** [comment]
See #1070, not crazy hard but I also have truncation figured out for this one. Once the cells with bg colors and icons work we could migrate this. I’ll reopen as a reminder.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
@Sherlouk yup!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
