### ISSUE TITLE
Migrate IssueLabeledCell to AttributedStringCell

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#1057]
See #864 for how-to

Requires adding custom drawing for rounded background colors on labels. See:

- https://stackoverflow.com/questions/21857408/how-to-set-nsstrings-background-cornerradius-on-ios7
- https://stackoverflow.com/questions/16362407/nsattributedstring-background-color-and-rounded-corners

**Comment by Sherlouk** [comment]
I might have a look into this if nobody else does, tried to do this effect before and it beat me 😂 round two!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
![image](https://user-images.githubusercontent.com/15193942/33155015-9ede71f0-cfe4-11e7-8efd-a3d9037fa25f.png)

Very much WIP, but this is what I av so far -- All one big attributed string!

**Comment by rnystrom** [comment]
Dang that looks awesome!!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
