### ISSUE TITLE
Scroll down to load more

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#1059]
A la Slack, if youre at the bottom let me bounce the view to see if there are new comments and load them if there is!

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.14.0 (1213)
Device: iPhone 6s Plus (iOS 11.2)
TestFlight: true
</pre>
</details>

**Comment by Sherlouk** [comment]
Does this make sense btw? (For those who don't use slack)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
I feel like it's a bit of overkill. GH Issues / PRs are not as realtime as a chat; when do you really expect to get a reaction where you want to refresh for until you see it?
