### ISSUE TITLE
Feed sticks to bottom (keyboard)

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#1060]
I'd say 95% reproducible, but basically it's possible to get the app in a weird state where the content sticks to the bottom of the phone. (See the screenshot, I'm doing nothing to the phone to get that).

My steps is basically just go into an issue where the content size is less than the size of the phone (so basically one comment), tap to start writing a comment (that sometimes enough, but it's a lot more reproducible if you preview the comment as well now) then click the screen somewhere else to dismiss the keyboard and boom bada bing.

![img_0773](https://user-images.githubusercontent.com/15193942/33148679-a1dab2b2-cfc4-11e7-857d-f33371301594.PNG)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.14.0 (1213)
Device: iPhone 6s Plus (iOS 11.2)
TestFlight: true
</pre>
</details>

**Comment by Sherlouk** [comment]
New bug imminent as soon as I can upload images Ryan 😩😂

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Yeah, have been seeing this occasionally as well. Especially on iPad when switching between hardware + software keyboard

**Comment by rnystrom** [comment]
Ya something to do with that slack control. The more I use it the more I hate it. The code is garbage.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
@rnystrom Might be time to build our own then 🤷‍♂️  We've got a number of bugs relating to that area now

**Comment by rnystrom** [comment]
Ya, it's only a matter of time at this point. Getting tired of it.
