### ISSUE TITLE
Can't build master at the moment

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#1061]
![image](https://user-images.githubusercontent.com/15193942/33149424-9eba7182-cfc7-11e7-8348-b29289f5389c.png)

@BasThomas @rnystrom 

😢

**Comment by BasThomas** [comment]
Up to date with master? This is what was happening before #1039

**Comment by BasThomas** [comment]
Or at least, this was happening before I recloned the repo I think?

**Comment by Sherlouk** [comment]
Did a fresh fetch and that's what's happening

Generate Secrets config is before the CP stuff, so that fix has gone in

🤔

**Comment by BasThomas** [comment]
But the xcconfig isn't generated yet looking at your screenshot?

**Comment by BasThomas** [comment]
Did you build or run?

**Comment by Sherlouk** [comment]
Run, I just did a clean and build and it went through, So maybe false alarm

Though maybe it is an issue where you have to build twice because of the order of events

**Comment by BasThomas** [comment]
I *think* you have to specifically build the first time, as for some reason run doesn't invoke the script. Not sure.

**Comment by Sherlouk** [comment]
Buddybuild still broke as well, so something's definitely up!

**Comment by BasThomas** [comment]
Ugh, you're right

**Comment by rnystrom** [comment]
God this is so frustrating. Tempted to just revert all of the changes so I can actually focus on building things instead of fighting blackbox tools.

So its working locally, even cloned a new repo and got it to work out of box. I assume that buddybuild is using their own config or something.

I'm pretty stuck at the moment. Any ideas?

**Comment by Sherlouk** [comment]
Genuinely I'm just unsure how the whole ObjC bit fits in, I feel we could use `ProcessInfo.processInfo.environment` to get the environmental variables. They can be set via the scheme that way, and BB uses env variables AFAIK so should be fine!

Removes all this complexity with .xcconfig etc, but yea I'm easy

**Comment by rnystrom** [comment]
@Sherlouk mind putting up a PR to change that?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
@Sherlouk just checking, are you able to help with this? Would be really appreciated. I tried using the env vars and got stuck.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Sorry yea will pick this up today! (DIdn't actually get a notification for the first comment 🤔)

**Comment by Sherlouk** [comment]
@rnystrom What's the goal here, what do we want to achieve?

Is it that BuddyBuild can define these constants without your intervention? Or is it that the app can't build if you don't define them? or what?

**Comment by rnystrom** [comment]
- Switch branches and pull without changing keys
- Don’t check in keys
- Using fastlane locally will fail of keys aren’t set
- CI builds with keys
- Not flaky

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
How's this coming along?

**Comment by Sherlouk** [comment]
I wanna say it's done, but will leave that to @rnystrom 

Know there was a few teething issues, but think they're fine???

**Comment by rnystrom** [comment]
Ya I think this is ok now

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
