### ISSUE TITLE
Use NSTextAttachment to render checkboxes

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#1074]
- [x] Need unchecked asset
- [x] Need checked asset
- [ ] Find/replace `[ ]` and `[x]` (does GH support things like `[ x]`?)
- [ ] Create `NSTextAttachment` probably in `NSAttributedStringSizing` alongside find/replace

Prereq for finishing #50 (making interactive)

**Comment by Sherlouk** [comment]
- [ x] No is the answer you're looking for 😂 

Looking forward to this!

**Comment by rnystrom** [comment]
Testing some other scenarios

[ ]

[x]

1. [ ]
2. [x]

Word word word [ ] and word word word [x] and word
