### ISSUE TITLE
Build errors due to codegen?

### ISSUE THREAD

**Issue by eito** [rnystrom/GitHawk#1093]
I just setup my environment to build GitHawk today: including installing `homebrew`, running `npm install`, etc. 

When I build though, the codegen is changing API.swift which doesn't look to be expected 

![image](https://user-images.githubusercontent.com/775643/33238119-0e13752c-d23b-11e7-8b36-1de93eb03654.png)

Here is the `resolved` value from the apollo-codegen's package.json file in case the version is in question

```
 "_resolved": "https://registry.npmjs.org/apollo-codegen/-/apollo-codegen-0.17.2.tgz",
```

**Comment by eito** [comment]
Looks like this is stemming from the newer version of apollo-codegen v0.17.2. Here's the diff with this particular change

https://github.com/apollographql/apollo-codegen/compare/v0.17.0-alpha.13...v0.17.2#diff-d97b285146ff1efcc19d05c00552c7d2L735

**Comment by eito** [comment]
For now, I've worked around this by setting the version explicitly to `"apollo-codegen": "0.17.0-alpha.13"` in my local package.json file as I don't yet know enough about how apollo works and how Freetime depends on it, but I can investigate.

**Comment by Sherlouk** [comment]
As part of newer versions of Apollo they now have version control within the pod itself, you can see this [here](https://github.com/rnystrom/GitHawk/blob/master/Pods/Apollo/scripts/check-and-run-apollo-codegen.sh#L2-L14)

The `package.json` file was created before this functionality was available, so you shouldn't need to use NPM anymore! We should probably validate this, remove the JSON file and update the guides

**Comment by eito** [comment]
ahh, ok, thanks @Sherlouk!

**Comment by eito** [comment]
FWIW, I reset my environment and removed the JSON files and my npm packages/node_modules, but the script that you reference still installs 0.17.2. Should it be explicit and limited to `v0.17.0-alpha.13` for now?

**Comment by Sherlouk** [comment]
It depends which way you look at it, as your original comment says the version installed by doing `npm install` should **not** be overridden by the run script as the major & minor both match (`0.17`).

If you do `npm install` and then the run-script changes this, then I would say this is a bug with Apollo

**Comment by eito** [comment]
Ah, I must have misunderstood what you meant. I thought you were saying we wouldn't need to use `npm install` anymore. If I run that first, then build, it's fine and doesn't override the version.

**Comment by Sherlouk** [comment]
Technically we don't need to use npm anymore but using it means we can guarantee were all on the same version and prevents API.swift constantly changing!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Closing this as I think it is resolved. @eito, feel free to reopen if you have any more questions!
