### ISSUE TITLE
Image tapping broken

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#1094]
Can’t tap images to open them in the photo viewer. Possible regression after double tap maybe?

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.14.0 (1230)
Device: iPhone X (iOS 11.1.2)
TestFlight: true
</pre>
</details>

**Comment by Sherlouk** [comment]
Link to issue where you're seeing issue? I've just tested it in #1085 and it worked fine!

**Comment by rnystrom** [comment]
@BasThomas are you tapping an image rendered in a web view? You can use FLEX to check.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
It is. Issue: https://github.com/Moya/Moya/issues/1481

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
![GitHawk Upload by BasThomas](https://i.imgur.com/Dhcau6P.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Ya this is a known issue. We could add some JavaScript to each webview that listens for taps on images and then sends info back to the cell.

**Comment by BasThomas** [comment]
Opened #1100 👍
