### ISSUE TITLE
Comment image uploading broken when already typed something

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#1095]
To reproduce:

Start a comment
Upload an image

The image markdown is never added to your WIP comment

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.14.0 (1230)
Device: iPhone X (iOS 11.1.2)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
Hmm can also repro this. The delegate is hooked up, the text view exists. Something weird is going on...

**Comment by Sherlouk** [comment]
Using sim and personal phone I've not been able to reproduce, to confirm the steps I'm doing is:
- Tap "Leave a comment" (Don't change anything)
- Tap Upload Image
- Go through the flow
- When I'm returned back to the text view, it inserts the text just fine

I've also tried not tapping leave a comment, and going straight to the upload image (technically this bug: #231) but that also works. I've also tried inserting a comment, and the message is inserted much like a header is 🤔

**Comment by Sherlouk** [comment]
Alright reproduced, the textview's text is being defined correctly.

What I think is happening is the Slack TextViewController's caching mechanism is setting the textView's text to be what it cached on view[Will/Did]Appear but because we've changed the version which isn't cached it's basically just overriding with what it thinks is the correct answer

It doesn't break when you have no text as it skips all of the caching logic

Un-assigning myself as I'm not familiar with the inners of Slacks VC

**Comment by rnystrom** [comment]
Good chance to get familiar with the inners 😉

I can probably fix later if not 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
I'll rephrase, I didn't wanna just add a super kludgy fix 😂 

Possible solutions:
- Delay the replacement of text until things have loaded
- or: Call `cacheTextView()` as soon as we update it

**Comment by BasThomas** [comment]
Oh that makes “sense”! Nice detective work @Sherlouk 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
They don't call me [Sherlock](https://en.wikipedia.org/wiki/Sherlock_Holmes) for the fun of it 😉

**Comment by BasThomas** [comment]
You don't have to link to a Wikipedia article for that 😂

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
I've made the reference before and people have been like who the hell is that 😂
