### ISSUE TITLE
Referenced event not showing reference “author”

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#1096]
![GitHawk Upload by BasThomas](https://i.imgur.com/U7xg2cG.jpg)

Should be “BasThomas referenced”

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.14.0 (1230)
Device: iPhone X (iOS 11.1.2)
TestFlight: true
</pre>
</details>

**Comment by Sherlouk** [comment]
Yea noticed this in the master sheet too #1085 - The badge should have a bit more horizontal padding too!

**Comment by rnystrom** [comment]
Oops, introduced in #1068
