### ISSUE TITLE
Search bar obstructs UICollectionView (< iOS 11)

### ISSUE THREAD

**Issue by msaps** [rnystrom/GitHawk#1108]
When running GitHawk on iOS 10, the search bars cause insetting issues with the collection view below. Assume it must be doing something with the `contentInset` when the search bar is tapped. 

![githawk-search-ios10](https://user-images.githubusercontent.com/3515448/33325298-26e07488-d452-11e7-8142-f7157cf7cba8.gif)

**Comment by rnystrom** [comment]
Ack, thanks!

**Comment by rnystrom** [comment]
I can only barely reproduce this and its really inconsistent. Wonder if its a simulator-only issue? I don't have any iOS 10 devices on me atm either. Maybe not the highest priority?

**Comment by BasThomas** [comment]
Can consistently reproduce this on either a 7 or 5s simulator using 10.1.

**Comment by rnystrom** [comment]
Crazy, will-hide is being called before will-show... not sure I understand why. Fixing.
