### ISSUE TITLE
Clean up label drawing

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#1110]
The border and corner radius looks a little funky. Maybe more bottom padding.

Will post screenshot later, don’t API key atm.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.15.0 (SEE BUILD PHASE)
Device: iPhone X (iOS 11.1.2)
TestFlight: false
</pre>
</details>

**Comment by Sherlouk** [comment]
I would've loved more vertical padding, I couldn't work out how to increase the line height though - that's the maximum I could get it without it looking super screwy!

I did find if I added UITextAttachment in the string and defined the size in that it would work; but that was super kludgy!

**Comment by rnystrom** [comment]
![img_e0214](https://user-images.githubusercontent.com/739696/33339387-f2ecaa44-d446-11e7-9d39-ef86b164650e.JPG)

**Comment by Sherlouk** [comment]
Looks beautiful 😅 I think we could drop the border tbh, doesn't really add anything! The corners were definitely better if the vertical embed is made slightly bigger but that makes the entire thing smaller in height (an annoying balance) so yeah

**Comment by rnystrom** [comment]
The only reason for the border is for label colors that are really close to the bg color of this view, makes it hard to see.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
I mean yea if we can work out the height issue then we can keep the border! Like I said a super kludgy way is tor add a UITextViewAttachment anywhere we have a badge, which would technically work but ideally we need to find a way to replace the glpyh's height - nothing I could find on Google explained this!
