### ISSUE TITLE
Add Bookmark buttons gone

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#1111]
Latest testflight has no way to add either issues, prs or repos to bookmarks

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.15.0 (1511717840)
Device: iPad7,3 (iOS 11.1.2)
TestFlight: true
</pre>
</details>

**Comment by Sherlouk** [comment]
Working fine on my phone, same build 🤔

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Checked on both phone and iPad, neither work

**Comment by BasThomas** [comment]
![GitHawk Upload by BasThomas](https://i.imgur.com/Wph2fOI.jpg)

**Comment by Sherlouk** [comment]
The little flag icon next to the triple dot is to bookmark! 😄

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Can I completely remove an issue from existence? My brain...

**Comment by rnystrom** [comment]
iPad specific?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
No, I am stupid

**Comment by Sherlouk** [comment]
We've all been there 😂

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Maybe we do need onboarding (#962) for our collaborators too 😆 

(but in all seriousness it would be a cool thing to do in sort of a "tips" fashion, see https://github.com/ephread/Instructions for what I mean -- I didn't immediately associate the buttons)

**Comment by rizwankce** [comment]
haha @BasThomas we have been to you situation. We changed from button to bookmark navigation item

**Comment by BasThomas** [comment]
But the thing about it is that I was well aware of that. I’ve been using the bookmark button, but for some reason yesterday I totally overlooked it. 😅🤷‍♂️

**Comment by BasThomas** [comment]
Re tips: that wouldn’t hurt, want to create a separate issue for that @Sherlouk?
