### ISSUE TITLE
Manage button is not a button

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#1112]
<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.15.0 (1511717840)
Device: iPad7,3 (iOS 11.1.2)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
?

**Comment by rizwankce** [comment]
Guess @BasThomas saying its not a button in terms of Accessibility
