### ISSUE TITLE
Use fastlane + UI tests to automate screenshot generation

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#1113]
<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.15.0 (1511717840)
Device: iPad7,3 (iOS 11.1.2)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
I've looked into doing this before. Some of the issues I didn't have time to solve. Curious if this is easy to change:

- Gradient backgrounds ([docs](https://docs.fastlane.tools/actions/frameit/) don't detail this)
- Subtitles?
- Injecting fake content when running as snapshot
  - I try to show off specific stuff in screenshots, would need to inject specific things + keep it updated

Happy to accept a PR that can get this all up and running!
