### ISSUE TITLE
Add "Tips"

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#1116]
add-on to onboarding flow issue (#962)
follow up to https://github.com/rnystrom/GitHawk/issues/1111#issuecomment-347693450

Similar to https://github.com/ephread/Instructions

Things like the manage button, bookmark button, and some others?

**Comment by rnystrom** [comment]
Tbh I'm not crazy about this. If we need "tips" then our UX is a failure. Let's attack stuff that has an observable problem.
