### ISSUE TITLE
Add support for GitHub Enterprise 

### ISSUE THREAD

**Issue by cwagdev** [rnystrom/GitHawk#1118]
Some bigger more protective corporations opt to use [GitHub Enterprise](https://enterprise.github.com/home). As far as I am aware there's no way to log in to an enterprise account from GitHawk. This may pose more implementation challenges than it is worth due to the varying authentication schemes supported. But worth taking a look at!

**Comment by BasThomas** [comment]
You are right, and it would be awesome if this could be added. There is already a ticket for this (which I can’t find right now), but this is definitely on our radar. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cwagdev** [comment]
Whoops, sorry about that. My quick "enterprise" search didn't yield what I was looking for.

**Comment by cwagdev** [comment]
Looks like it's discussed in here now that I read the comments, https://github.com/rnystrom/GitHawk/issues/408

**Comment by Sherlouk** [comment]
As linked above there is an open ticket for this, it's a great signal though for us to see so many people looking for this functionality!
