### ISSUE TITLE
Add separator between review comments

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#1123]
Now only distinguished by avatar. Should probably use the same separation style as comments in an issue / PR. 

![GitHawk Upload by BasThomas](https://i.imgur.com/bjqPyrX.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.15.0 (1511968511)
Device: iPhone X (iOS 11.2)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
I was trying to keep the thread UI consistent with PR review threads on GitHub.com. The separator isn’t there so it’s more clear that it’s a continuous conversation. Different threads get separators, a diff hunk, and file. 

I’ll enable separators and see how it looks.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
That's a good point; on web you have this vertical line, but we can't have that unless we inset the text to the right... which due to size constraints I wouldn't do 😛

<img width="56" alt="screen shot 2017-12-02 at 21 01 22" src="https://user-images.githubusercontent.com/4190298/33519267-089c8048-d7a4-11e7-9f5a-564dfb5634c2.png">

**Comment by Sherlouk** [comment]
![image](https://user-images.githubusercontent.com/15193942/33519313-5ab71dd2-d79c-11e7-83a5-b513be70c097.png)

Problem Solved :trollface:

**Comment by rnystrom** [comment]
so beautiful

**Comment by rnystrom** [comment]
Gonna say its too busy

![img_0232](https://user-images.githubusercontent.com/739696/33519649-2f830afe-d779-11e7-969c-7b5949194aa7.PNG)

**Comment by Sherlouk** [comment]
I actually think it looks nice with the blue headers where it's "you" -- could we do a very faint grey for anybody but "you"?

@rnystrom 🤔

**Comment by BasThomas** [comment]
The blue headers are already there; the gray horizontal lines aren't.

**Comment by Sherlouk** [comment]
@BasThomas Yea I know! I'm suggesting we don't have the lines, but have a light grey background on all other users 😄
