### ISSUE TITLE
"Project has no Readme" when offline

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#1134]
When not connected to the internet, browsing to a repo will have the overview stating there is no readme, even though there could be one.

**Comment by Sherlouk** [comment]
I wonder if we should re-approach caching? At the moment we basically don't cash _anything_ - READMEs don't change often, so would be nice to cache that until we get a new copy or somethin'

**Comment by BasThomas** [comment]
After I created this one I was thinking about the whole offline thing - most of the time it probably doesn't make sense to have stuff offline, so maybe we should skip it completely.
