### ISSUE TITLE
Improve compile times

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#114]
I took a stab at removing CocoaPods and didn't notice any build improvements. Instead of hacking at it, it'd be good to do some [profiling](http://irace.me/swift-profiling) of builds. Will do this and report back.

Any good tools for profiling Swift builds?

**Comment by rnystrom** [comment]
Dang, some gnarly ones:

https://github.com/rnystrom/Freetime/blob/master/culprits.txt

**Comment by Sherlouk** [comment]
Also worth just making sure the whole project optimisation settings are correct; that alone can save a lot of build times!

**Comment by MosheBerman** [comment]
I’ve used this one before: https://github.com/RobertGummesson/BuildTimeAnalyzer-for-Xcode/

I don’t know if works with Xcode 9, haven’t used it since Swift 2.3.

**Comment by rnystrom** [comment]
Should be helpful

http://khanlou.com/2016/12/guarding-against-long-compiles/
