### ISSUE TITLE
Align right hand side labels in Settings

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#1142]
![GitHawk Upload by BasThomas](https://i.imgur.com/Kt09D30.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.15.0 (1512249487)
Device: iPhone X (iOS 11.2)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
Gross, good eye

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
