### ISSUE TITLE
Improve repo issue search filters

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#1145]
Now that we show labels, I would at least expect to also be able to filter by labels.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.15.0 (1512249487)
Device: iPhone X (iOS 11.2)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
Would probably be good to start planning for this. Maybe 1.16.0? Some basic filters won’t be too difficult.

dupe #287

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
