### ISSUE TITLE
Manage button not respecting safe area

### ISSUE THREAD

**Issue by joerocca** [rnystrom/GitHawk#1149]
![GitHawk Upload by joerocca](https://i.imgur.com/yvY9yzn.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by joerocca** [comment]
The comment field also does not respect the safe area, but I remember seeing an issue for that?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Don't think there's once as far as I know

**Comment by BasThomas** [comment]
Can we also not create a more error-prone safe area-respected view here? Seems like we keep hitting these. Eg, can't we just make the ViewController handle everything?

**Comment by rnystrom** [comment]
@BasThomas pretty tricky unless we want to just squish all the content in. Looks kind of clowny if the background doesn’t actually stretch to the edge (this is how stock tables work).

Just a matter of using the base cells and `contentView`.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
