### ISSUE TITLE
Repo paging tab is not respecting safe area

### ISSUE THREAD

**Issue by joerocca** [rnystrom/GitHawk#1152]
![GitHawk Upload by joerocca](https://i.imgur.com/VgTnIQQ.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
This actually belongs on Tabman. Mind filing there? cc @msaps 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
