### ISSUE TITLE
Weird flicker animation on Slack text view

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#1161]
Toss it on the pile of crap I keep finding...

Will post gif of issue

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.15.0 (SEE BUILD PHASE)
Device: iPhone X (iOS 11.1.2)
TestFlight: false
</pre>
</details>

**Comment by SD10** [comment]
We can close this because we're not using Slack any longer? Going through all the bugs looking for quick wins 😆

**Comment by rnystrom** [comment]
Thanks for helping clean this up @SD10!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
