### ISSUE TITLE
Should files have disclosure indicators?

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#1175]
Previously it was only dirs. I liked that they were different. But, files still push another view.

Thoughts?

![GitHawk Upload by rnystrom](https://i.imgur.com/rAQCNfh.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.15.0 (1512339646)
Device: iPhone X (iOS 11.1.2)
TestFlight: true
</pre>
</details>

**Comment by BasThomas** [comment]
For what it’s worth Notes.app has disclosures for folders, not notes. Think it wouldn’t hurt to remove, but not sure about the average user. Definitely removes some ambiguity (is it tappable? or is it not?)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Ok, lets remove. I liked it that way.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
