### ISSUE TITLE
Tap part of path to go back that far?

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#1176]
In the title

![GitHawk Upload by rnystrom](https://i.imgur.com/NzqD3Fl.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.15.0 (1512339646)
Device: iPhone X (iOS 11.1.2)
TestFlight: true
</pre>
</details>

**Comment by BasThomas** [comment]
?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Ya sorry writing issues while at dinner lol.

Imagine if you could tap the individual path components in the nav bar:

“Classes/Issues/Comments/CodeBlock”

Tapping “Classes” would pop 4x so you’re at the Classes VC, instead of tapping back 4x.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Would be kind of cool, but niche and the tap target would be super tiny. I would say it's not that feasible.
