### ISSUE TITLE
Add logging event when prompting for rating

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#1182]
Should add for both types. Can see how often they trigger (even if we don’t know for sure if the native one appears).

Maybe couple with how often the rating controller is _asked_ to prompt, that way we can see a ratio and frequency.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.15.0 (1512339646)
Device: iPhone X (iOS 11.1.2)
TestFlight: true
</pre>
</details>

**Comment by BasThomas** [comment]
Still do not think I have seen them ever o.o

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
