### ISSUE TITLE
Add changed files, additions, and deletions to “View Files” cell in PRs

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#1183]
This might contradict @Sherlouk’s plans for adding tabs, but it would be nice to see the change summary inline.

I think this info is new to the PR object.

https://developer.github.com/v4/reference/object/pullrequest/

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.15.0 (1512339646)
Device: iPhone X (iOS 11.1.2)
TestFlight: true
</pre>
</details>

**Comment by Sherlouk** [comment]
You mean like this:?
![image](https://user-images.githubusercontent.com/15193942/33579338-62779910-d941-11e7-8345-0436f9773c54.png)

If so, doesn't contradict my plans at all! Both can be done easily and nicely!

**Comment by rnystrom** [comment]
Ya just like that. I was thinking of changing the button text to look like:

View Files (12) +197 -97

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Not a huge fan of the proposed position I must say! I think if we had tabs, having it right aligned similar to desktop would look fine and should fit even on small devices.

Otherwise above the tabs similar to manage button I think would look nice
