### ISSUE TITLE
View hidden under nav bar

### ISSUE THREAD

**Issue by narup** [rnystrom/GitHawk#1189]
![0d140292-563d-4412-a43e-66f4f99ab320](https://user-images.githubusercontent.com/178289/33615674-937fc066-d98f-11e7-80ea-847f9f22c263.jpeg)
Version 1.9.0 (1513)
Device: iPhone 6s (iOS 11.2)

**Comment by rnystrom** [comment]
@narup can you update? A LOT has changed since that version.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by narup** [comment]
Yeah, my bad. I realized later I had old version

**Comment by BasThomas** [comment]
Would be cool if we can have a check somewhere (either in-app - before submitting a bug report - or in the GitHub issue) checking if the version is out-of-date automatically!

**Comment by Sherlouk** [comment]
Maybe a little warning box above the form content? Similar to how GitHub desktop gives you the prompt to check the contributing guide etc?

**Comment by BasThomas** [comment]
Yes, and then we can do a version comparison through the iTunes API ([this](https://itunes.apple.com/lookup?id=1252320249) endpoint). Would obviously have to ignore a higher version (as can happen w/ TF), but that should help 👍
