### ISSUE TITLE
Broken tables, html comment visible

### ISSUE THREAD

**Issue by forivall** [rnystrom/GitHawk#1192]
App:
![GitHawk Upload by forivall](https://i.imgur.com/ScaEYQo.jpg)

Browser:
![GitHawk Upload by forivall](https://i.imgur.com/qspzNU7.jpg)

Sorry if this is a duplicate, doing this quickly on my phone from githawk.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.15.0 (1512350154)
Device: iPhone 6s Plus (iOS 11.2)
TestFlight: false
</pre>
</details>

**Comment by rnystrom** [comment]
Oh noooo, good find, tables are a pain in the butt. Will try to fix this for the next release!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
