### ISSUE TITLE
Confirm new label drawing is correct

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#1193]
Got this bug report via email

![image1](https://user-images.githubusercontent.com/739696/33625188-c979f486-d9c4-11e7-98da-6d2f7ca8ad79.png)

```
App Information:
App Name: GitHawk for GitHub
App Version: 1.15.0 (1512339646)
Installed App Version: 1.15.0 (1512339646)

Device Information:
Device: iPhone8,1
iOS Version: 11.2
Language: en-GB (English (United Kingdom))
Carrier: EE
Timezone: GMT
Architecture: N/A
Connection Status: WiFi
Paired Apple Watch: N/A
```

**Comment by Sherlouk** [comment]
Not what you're showing I assume, but I like the device/app dump 😅

**Comment by BasThomas** [comment]
That's from TestFlight I think!

**Comment by rnystrom** [comment]
Lol yup, TestFlight email attachment

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gingerbeardman** [comment]
This is from me. I was short on time so just fired it off.

What I was reporting was the fact it was not possible to scroll further to see what comes after "What actually happens". If I was at the end of the thread, then the status/emoji bar obscured the bottom of the post. I would have expected them to be stacked? 

I'll try to take a video.

**Comment by BasThomas** [comment]
Hey @gingerbeardman - you can actually tap the comment to expand it; that should solve your issue. 👍

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gingerbeardman** [comment]
@BasThomas interesting! it seems you have to tap some text in the comment to have it expand? it does not expand if you tap whitespace. Shall I file that as a new issue?
