### ISSUE TITLE
Tapping whitespace does not expand comment

### ISSUE THREAD

**Issue by gingerbeardman** [rnystrom/GitHawk#1199]
It was not obvious to me that it was possible to expand the comment. Maybe it should also be on the triple dot menu?

Tapping to expand the comment requires you to tap on text in the comment, rather than anywhere in the comment. Tapping whitespace does not expand the comment.

- If I tap the whitespace to the right of "Description" it will not expand the comment.
- If I tap "Decription" it will expand the comment.

<hr>

![https://user-images.githubusercontent.com/739696/33625188-c979f486-d9c4-11e7-98da-6d2f7ca8ad79.png](https://user-images.githubusercontent.com/739696/33625188-c979f486-d9c4-11e7-98da-6d2f7ca8ad79.png)

**Comment by rnystrom** [comment]
Oh wow yup, I can repro this. I think it’s a regression.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gingerbeardman** [comment]
I'm wondering if only long comments could be truncated? 

I've not looked at your code, sorry.

**Comment by rnystrom** [comment]
@gingerbeardman they are! Only comments that exceed 300 pts in height are collapsed. Here's the code:

https://github.com/rnystrom/GitHawk/blob/master/Classes/Issues/Comments/IssueCollapsedBodies.swift#L20-L42

**Comment by gingerbeardman** [comment]
Rather than an arbitrary amount maybe factor in whether or not the comment contains quote/code? I don't mind long comments, it's just ones with quotes, code or logs that I don't want to see in full.

**Comment by rnystrom** [comment]
@gingerbeardman love it! Mind splitting off a new issue?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
