### ISSUE TITLE
I can’t download files that can’t be displayed as text.

### ISSUE THREAD

**Issue by F4Tornado** [rnystrom/GitHawk#1209]
I can’t download files that can’t be displayed as text. I don’t know if this is intended behavior.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.15.0 (1512350154)
Device: iPad Mini 2 (iOS 11.0.2)
TestFlight: false
</pre>
</details>

**Comment by rnystrom** [comment]
Dupe of #587 (its expected now, but something we want to keep advancing)
