### ISSUE TITLE
.md treated as code

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#1212]
![GitHawk Upload by BasThomas](https://i.imgur.com/OZ8ikU6.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.16.0 (1512840803)
Device: iPhone X (iOS 11.2)
TestFlight: true
</pre>
</details>

**Comment by BasThomas** [comment]
Or is this intented? It seems to “work”

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
dupe #588
