### ISSUE TITLE
Excessive inset on bookmarks page

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#1218]
Notice scroll bar in pic

![GitHawk Upload by Sherlouk](https://i.imgur.com/8YKpHzQ.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.16.0 (1512840803)
Device: iPhone 6s Plus (iOS 11.2)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
Is this on a repo? Bookmarks doesn’t have a “load more”.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
A repo from within bookmarks it seems. Might not happen in search is what @Sherlouk meant?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Sorry yea, repo issues page navigated from bookmarks

**Comment by Sherlouk** [comment]
Fixed with new tabman
