### ISSUE TITLE
Replace labels dot view with text labels view in issue/pr cells?

### ISSUE THREAD

**Issue by joerocca** [rnystrom/GitHawk#1220]
I am a fan of this on GitHub web

![GitHawk Upload by joerocca](https://i.imgur.com/89rfGZg.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
So you mean the full text over just dots?

**Comment by joerocca** [comment]
@BasThomas Yes!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Ya lets do it, I LOVE the new labels. For this view we could just limit the number we show (maybe with a white gradient on the right indicating there’s more).

Or if we want to get fancy, refactor this cell and do labels like we do in issues (harder).

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by joerocca** [comment]
@rnystrom We should be able to use the embedded collection view and calculate the size like originally in issues, right?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
@joerocca we could, ya. That might be really easy. Just have to cache sizes like the issues section controller does now so we're not always calculating label size. Maybe we could make that a singleton?

**Comment by joerocca** [comment]
Sounds good. I will work on this!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
