### ISSUE TITLE
Configured title+subtitle needs VO param

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#1240]
Something to make it more spoken-friendly. e.g.

#1237
rnystrom/GitHawk

Could read as: "Issue 1237 in repository GitHawk by rnystrom" or something

**Comment by BasThomas** [comment]
Oh I think I tried to tackle this one before, but held off as the `configure` method we use for that is more flexible than just adding repo # and name. Where do you think we could best tackle this?

**Comment by rnystrom** [comment]
What about just adding an optional param to that method with a “read out loud” string?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Yeah, I can do that. Just `accessibilityLabel: String? = nil` I guess?

**Comment by BasThomas** [comment]
Oh 🤔, why do we not "know" what issue type something is when initing the `IssuesViewController`? We know before.

**Comment by rnystrom** [comment]
Ya! Sounds great to me!

**Comment by rnystrom** [comment]
> why do we not "know" what issue type something is when initing the IssuesViewController? 

not sure I follow?

**Comment by BasThomas** [comment]
Instead we use this guy to find out again:

```swift
var result: IssueResult? {
    guard let id = resultID else { return nil }
    return client.cache.get(id: id) as IssueResult?
}
```

**Comment by BasThomas** [comment]
In a list, we know if an issue is a PR or an issue. Then we open the detail VC (`IssuesViewController`), which we just pass an `IssueDetailsModel` which only has an owner, repo and number (and thus does not know if it is a pull request or an issue)

**Comment by BasThomas** [comment]
<img width="433" alt="screen shot 2017-12-15 at 22 53 38" src="https://user-images.githubusercontent.com/4190298/34062018-d573bfdc-e1ea-11e7-80ed-52e4342aeb06.png">
<img width="433" alt="screen shot 2017-12-15 at 22 53 42" src="https://user-images.githubusercontent.com/4190298/34062020-d58d596a-e1ea-11e7-97e0-bb3d36ca7a45.png">
<img width="433" alt="screen shot 2017-12-15 at 22 53 49" src="https://user-images.githubusercontent.com/4190298/34062021-d5a53ef4-e1ea-11e7-85f1-e632f79975b8.png">
Eg here we know what cells are PRs and what are issues
