### ISSUE TITLE
Milestone 100% makes it empty in-app

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#1244]
As seen in #1200. The milestone is completed, but the app shows it as not completed at all.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.16.0 (1512947879)
Device: iPad7,3 (iOS 11.2)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
Ha, ew! I’ll fix before 1.16

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
