### ISSUE TITLE
Milestone/Label cells do not respect safe area

### ISSUE THREAD

**Issue by joerocca** [rnystrom/GitHawk#1246]
![img_0108](https://user-images.githubusercontent.com/10346184/33900964-3f9ce8fc-df3e-11e7-815f-4b2054a59ea5.PNG)

**Comment by rnystrom** [comment]
Dang it good catch!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Under the same category, do assignees/reviewers out of interest?

**Comment by joerocca** [comment]
@Sherlouk They do!
