### ISSUE TITLE
Label incorrect padding

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#1247]
![GitHawk Upload by Sherlouk](https://i.imgur.com/RT5XfeD.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.16.0 (1513090523)
Device: iPhone 6s Plus (iOS 11.2)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
Seems fixed now

![simulator screen shot - iphone x - 2018-01-14 at 12 15 28](https://user-images.githubusercontent.com/739696/34918686-a996d6dc-f924-11e7-90f2-07d58b722001.png)
