### ISSUE TITLE
2017 Recap

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#1254]

**Comment by BasThomas** [comment]
Don't want to pressure, but might be nice to do this sooner rather than later? :)

**Comment by rnystrom** [comment]
Ya these take a lot of time, higher pri stuff to do now, may not ever get to it

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
I understand! 😊

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
2018 Recap, start early :trollface:

**Comment by BasThomas** [comment]
What about a "Year in review" in July? 😎

**Comment by rnystrom** [comment]
I am def gonna do another post soon to update the latest! Just not able to pull off any cadence like I wanted to...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
