### ISSUE TITLE
Try out new selection state design

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#1261]
I love this. Would look great on iPad.

- Blue bar along the left (maybe)
- Light blue background

Inbox Client
https://dribbble.com/shots/4020485-Inbox-Client

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.16.0 (1513090523)
Device: iPhone X (iOS 11.2)
TestFlight: true
</pre>
</details>

**Comment by BasThomas** [comment]
Why did you close this?

**Comment by rnystrom** [comment]
Kind of a random idea that lost its flare 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
