### ISSUE TITLE
Manage buttons have different colors

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#1263]
- White icon
- Different colors
- Labels same color as bg

https://dribbble.com/shots/3990108-Graphic-designers-community

This should reduce time thinking about what button is what, instead use color and pattern matching.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.16.0 (1513090523)
Device: iPhone X (iOS 11.2)
TestFlight: true
</pre>
</details>

**Comment by Sherlouk** [comment]
Love this!

**Comment by rnystrom** [comment]
Feedback on this direction? I pulled the colors from [this page's header graphic](https://github.com/marketplace/free-trials) (looking for diverse brand colors).

Not crazy about the yellow, pretty hard to read.

![simulator screen shot - iphone x - 2017-12-17 at 14 43 57](https://user-images.githubusercontent.com/739696/34083109-dd18e722-e338-11e7-9a56-4fbfa7b8cfa9.png)

**Comment by BasThomas** [comment]
Prefer colors over all blue, but probably because the dark blue is screaming a bit too much with some many large circles.

**Comment by BasThomas** [comment]
Also the contrast with the yellow one isn't the best.

**Comment by Sherlouk** [comment]
Prefer the colors one (minus the yellow)!

**Comment by rnystrom** [comment]
Here's GitHub's lighter blue, and a shot w/ a lot of other stuff going on. Too busy? Or you liking it? I think I'm going to ship a beta w/ this and try it out myself.

![simulator screen shot - iphone x - 2017-12-17 at 15 03 03](https://user-images.githubusercontent.com/739696/34083278-83b4e57a-e33b-11e7-83b3-00e93c6bd30e.png)

**Comment by Sherlouk** [comment]
I'd genuinely like to see it with a row two for Lock and Close tbh!

I also think with a bit more spacing as well it won't look so dense?

We can obviously change the colour as well super easily

**Comment by rnystrom** [comment]
Oooh. Lock and close would be interesting. Easy colors (would need to swap close & re-open).

Maybe even a merge button eventually?

**Comment by Sherlouk** [comment]
Merge could work but I'd like to consider that a bit more especially since all the states it can be in (Conflict, Pending, Mergable but mergable with 3 different methods, etc)

but deffo up for movin close/lock out of the overflow!

**Comment by BasThomas** [comment]
I can see merge logic going into "view files", you would want to look at the files before merging often anyway (assumption!).

Plus otherwise it would get a bit much super quickly I think

**Comment by Sherlouk** [comment]
Oh well we know what all those status events mean 😉 😉

**Comment by rnystrom** [comment]
maaaaaaaaaaybe
