### ISSUE TITLE
Dropdown from file navigation and select path

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#1267]
- Add a small carrot to the title
- Tap and show a dropdown of file paths (overlay content)
- Tapping a path pops back to that VC

Easy way to go back vs tapping back button over & over.

Would justify having a control for the inbox nav design too.

(Using Photos.app markup)

![GitHawk Upload by rnystrom](https://i.imgur.com/BghiTMA.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
No too big of a fan, as I think it’s easier to use navigation the usual way, especially since I feel like this is a pretty limited use case?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
I'd tend to agree with Bas here, you're not getting much more information than one level of navigation deep anyway which I don't think is a particularly slow thing to do!

Maybe if it was something like "Recent Files" or something? As a quick way to jump around within a single repo's code base? I think that'd be pretty handy!

**Comment by rnystrom** [comment]
I find getting back to root _really_ annoying (tap back 5x). Also think this style nav could be applied elsewhere. Imagine a dropdown on Issues that have options for the owner and repo.

Once code browsing has more features (share url, link to lines, search) I’ll be spending even more time in here.

Idk, gonna explore this more.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Admittedly I misread the message and thought it was items within the same level, not the breadcrumb hierarchy

So actually might be helpful, but equally I like the idea of Recent Files especially if you're jumping around looking for certain classes that reference each other!

I'm also not against the implementation, I could definitely imagine a similar dropdown in other places!

**Comment by rnystrom** [comment]
Here's a good example control that either we can use or get inspiration from:

https://github.com/PhamBaTho/BTNavigationDropdownMenu
