### ISSUE TITLE
Outlook style tab bar colors

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#1271]
I kind of love these. Thoughts?

![GitHawk Upload by rnystrom](https://i.imgur.com/EAc3ZUb.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.16.0 (1513090523)
Device: iPhone X (iOS 11.2)
TestFlight: true
</pre>
</details>

**Comment by Sherlouk** [comment]
Loving the more design questions recently, would be intrigued to see what our set would look like!

**Comment by Huddie** [comment]
>I kind of love these. Thoughts? ...

@rnystrom Outlook also has a beautiful animation on the calendar tab icon when scrolling in calendar -> agenda 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
