### ISSUE TITLE
Inconsistent close button location

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#1279]
I'm finding it's not super good for remembering where buttons are when the close button changes row depending on issue/pr

Wonder what other people think about always making sure the row splits before it?

++ centering everything but would require a custom layout

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.17.0 (1513546049)
Device: iPhone 6s Plus (iOS 11.2)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
The buttons are highly dynamic, thus the colors help a lot.

- Lock/unlock switch
- Close/re-open toggle
- If a PR is merged, close/re-open is not displayed
- If not a PR, reviewers isn't displayed
