### ISSUE TITLE
Sort inbox notifications into sections by repository

### ISSUE THREAD

**Issue by SD10** [rnystrom/GitHawk#1281]
Hey everyone 👋,
Great work on this app, thank you for dedicating your _free time_ 😉

I'd like to suggest a feature where the notifications in the Inbox are sorted by repository, similar to the notifications page on GitHub.
![screen shot 2017-12-17 at 5 48 06 pm](https://user-images.githubusercontent.com/7445580/34085212-7f33e6a6-e352-11e7-961e-a3ede4bf7193.png)

**Comment by rnystrom** [comment]
Ya!! I’ve been brainstorming a new control that drops down from the title so you can select a single repo. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Definitely want this feature myself! Think the primary issue has always been how to "load more" when they're grouped? It wouldn't be completely obvious so that'd need to be worked out!

Closing in favor of keeping it in one issue though: #61
