### ISSUE TITLE
No empty state for milestones

### ISSUE THREAD

**Issue by viktorgardart** [rnystrom/GitHawk#1283]
![GitHawk Upload by viktorgardart](https://i.imgur.com/26zwENI.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.17.0 (1513546049)
Device: iPhone X (iOS 11.2)
TestFlight: true
</pre>
</details>

**Comment by BasThomas** [comment]
Dupe of #1234 :)

**Comment by viktorgardart** [comment]
Ooh nice! 😃 love the issue #

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
