### ISSUE TITLE
Allow closing issue if you are author

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#1290]
<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.17.0 (SEE BUILD PHASE)
Device: iPhone X (iOS 11.2)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment]
Good one, I hit this the other day but forgot to make an issue. Also the case for Pull Requests (of course)
