### ISSUE TITLE
Link and code should be blue

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#1297]
![GitHawk Upload by rnystrom](https://i.imgur.com/E7MBVs1.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.17.0 (1513713275)
Device: iPhone X (iOS 11.2)
TestFlight: true
</pre>
</details>

**Comment by SD10** [comment]
Is this resolved by #1302?
