### ISSUE TITLE
Inbox more options showing only own repos

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#1301]
Should show repos you’re contributing to, too. 

Not that useful atm. (At least for me) includes many unused repos and does not include repos I frequently contribute to / repos I recently contributed to.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.17.0 (1513713275)
Device: iPhone X (iOS 11.2)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
Hmm the list is from watched repos, which should be what you get notifications for.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Ah, watched and limitex by like 20, sortex by oldest / last updated or so?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Maybe a better solutions n would be just showing a list of repos in your inbox?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
That would mean no repos when inbox zero? Or cache latest? If the latter, I think that could work. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Ugh ya good point...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
