### ISSUE TITLE
Easy to accidentally press close button

### ISSUE THREAD

**Issue by joerocca** [rnystrom/GitHawk#1303]
This may just be me, but I keep accidentally closing issue/pr when trying to close the manage tray. Maybe we could increase the manage button tap target? Not sure how much that would help.

![GitHawk Upload by joerocca](https://i.imgur.com/l5BC9a9.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Agree, I’ve done this too. I think decreasing the cell size and adding some padding in between will do it. Right now theres no padding, the cell fills all the white space. That’s why taps register. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
