### ISSUE TITLE
Possible gray view for “big” file (changes)

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#1304]
Was like +100 -100, got this when viewing the diff. 

Could dismiss by swiping back as normal, but nothing other than that. ![GitHawk Upload by BasThomas](https://i.imgur.com/ZqVkY2f.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.17.0 (1513713275)
Device: iPhone X (iOS 11.2)
TestFlight: true
</pre>
</details>

**Comment by BasThomas** [comment]
Was the InspectorVC diff [here]()

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Ha, so the way I'm laying out the `UITextView` is consuming like 900+mb of memory. Dang. Really liked the dual-scroll UI, but looks like we need to fallback to plain-old `UITextView` scrolling and word-wrapping so that we can take advantage of its tiled layers.

**Comment by BasThomas** [comment]
Oh wow 😱

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
