### ISSUE TITLE
Empty State Improvement/Bug

### ISSUE THREAD

**Issue by JamesKuang** [rnystrom/GitHawk#131]
Just signed in, and I see the following screen:

![img_2189](https://user-images.githubusercontent.com/1231513/28181828-f4863950-67d7-11e7-98c5-a348b3f589ef.PNG)

I also tried pulling to refresh and even re-signing in, but same issue. I think it had to do with me not having any unread notifications at the time. It eventually went away later when a new unread notification showed up. And now whenever I clear all my notifications, the proper inbox zero screen with floating emoji is showing. 

My best guess is the combination of having 0 notifications in local cache because I just signed in, and network response returning 0 unread notifications causes that error state?

**Comment by gtchance** [comment]
I've gotten this state when the notification (read and unread) count is zero. It's a little misleading.

**Comment by rnystrom** [comment]
Ya I think this is just poor messaging. Will update.
