### ISSUE TITLE
Update inbox zero to New Years?

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#1312]
✨💥🎇🎆

Not sure on the emoji, but might be nice from Friday or something?

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.17.0 (1513713275)
Device: iPhone 6s Plus (iOS 11.2.5)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
Yup! That’s the plan

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
done!
