### ISSUE TITLE
Send push notifications for repository activities

### ISSUE THREAD

**Issue by RishabhTayal** [rnystrom/GitHawk#1313]
<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.16.0 (1513134612)
Device: iPhone X (iOS 11.2)
TestFlight: false
</pre>
</details>

**Comment by Sherlouk** [comment]
Going to close as a duplicate of #224 - Let's keep the conversation in one place so it's easier to pick up!

Irrespective of the details such as what notifications are sent for what I think we can all agree that push notifications would be a welcomed feature!
