### ISSUE TITLE
Added url scheme to open GitHawk app

### ISSUE THREAD

**Issue by RishabhTayal** [rnystrom/GitHawk#1314]
It will be nice to have a url scheme for the app

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.16.0 (1513134612)
Device: iPhone X (iOS 11.2)
TestFlight: false
</pre>
</details>

**Comment by unnamedd** [comment]
An existing issue was opened before, you can check it here #418

**Comment by BasThomas** [comment]
Thanks for following up, @unnamedd!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
