### ISSUE TITLE
Issue comment redesign

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#1315]
Had a productive morning getting feedback from @orta. One big discussion we had was GitHawk's use of whitespace to achieve a visual information hierarchy (or lack there of).

After some brainstorming, I decided to play around w/ a "card" design for comments. I've been pretty averse to the idea b/c I dread _double padding_ and wasting precious space for text.

However, after looking at other apps and playing w/ some mockups, I think this makes reading GitHawk threads so much more readable.

I still want to play with the header spacing a bit and organize/prioritize the title + metadata correctly, but wanted to post this mockup and get some early feedback.

Some stuff I'm playing w/

- 10pt padding instead of 15 (2x 10pt on the cards)
- 15pt between card metadata and content (header, reactions)
- New "more" indicator (get this feedback a lot)
  - Might work on extending IGListKit w/ decorator support to make this more manageable

cc @BasThomas @Sherlouk 

![redesign-mocks](https://user-images.githubusercontent.com/739696/34456061-b2d32da6-ed5b-11e7-8f94-3956c25bc256.png)

**Comment by Sherlouk** [comment]
The mockup looks really cool and I definitely support the overall ideas. Love the more indicator, especially if we can improve support regardless of the comment models (html, etc)

I'd say we need to be careful of the header row though, especially with things like "edited by" and the author association (collaborator etc)

Also PR threads, those are really difficult to follow at the moment so some serious work needed there I think!

**Comment by rnystrom** [comment]
Oh also note that this mockup is to a 320pt width device, so the minimum that we need to worry about.

**Comment by BasThomas** [comment]
Love it!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
