### ISSUE TITLE
Fetch notification issue/PR status

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#1316]
Had a 💡 moment w/ @orta this morning. We can request _multiple issue/PR_ status info via the GraphQL API to batch notification status into a **single network request** using GQL aliases. An example request:

```
query {
  repository(owner: "rnystrom", name: "githawk") {
    issue(number:1) {
      title
      state
    }
    issue2: issue(number:2) {
      title
      state
    }
  }
}
```

Response:

```json
{
  "data": {
    "repository": {
      "issue": {
        "title": "Sample issue",
        "state": "CLOSED"
      },
      "issue2": {
        "title": "New MarkdownView",
        "state": "CLOSED"
      }
    }
  }
}
```

The trick to making this work is to:

1. Fetch notifications w/ V3 API
  - Mark all models as status "pending" or something, show as blue
2. Collect all issue/PR numbers
3. Dynamically build a GraphQL request
  - Do **not** use Apollo for this
4. Send request w/ token, manually parse
5. Map status and update models
6. Refresh UI
  - Updates should be done via `FlatCache`, so just reload feed with `.list` type changes

Really, **really** excited about this. Makes consuming notifications so much easier!

**Comment by Sherlouk** [comment]
I know you said not to use Apollo, but might be an idea to throw this Martijn as it could be pretty cool functionality on their side to group requests! (extremely powerful, and something they could do pretty easily with their infra!)

Overall support the idea

**Comment by rnystrom** [comment]
Good call, creating dynamic queries would be _amazing_.

**Comment by BasThomas** [comment]
Cc @martijnwalraven :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by martijnwalraven** [comment]
We've [experimented with various ways of doing query batching in Apollo Client](https://dev-blog.apollodata.com/query-batching-in-apollo-63acfd859862), including dynamically constructing queries. Using dynamic queries had too many drawbacks however, so we've actually removed this from more recent versions. Instead, we recommend transport level batching, which is a simple way to send multiple queries in a single HTTP request. It does require server support however, so it may not be supported by the GitHub API.

**Comment by rnystrom** [comment]
Btw got a hack together locally!

![simulator screen shot - iphone x - 2018-01-03 at 17 27 21](https://user-images.githubusercontent.com/739696/34543522-458c2264-f0af-11e7-9162-aa8b6056c6b7.png)

**Comment by BasThomas** [comment]
Yesssss! Would it be possible to query for labels also (and show them, just like in repositories)? That would be perfect!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
@BasThomas yup! that's a good followup. I added a comment count too (not sold on its position atm). Honestly this unlocks so many doors!
