### ISSUE TITLE
Focus search bar

### ISSUE THREAD

**Issue by RishabhTayal** [rnystrom/GitHawk#1323]
Focus search bar when long press on search and bookmarks tab just like Twitter app. That gives easy access to the search bar.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.16.0 (1513134612)
Device: iPhone X (iOS 11.2.1)
TestFlight: false
</pre>
</details>

**Comment by rnystrom** [comment]
You can double tap the tab bar, that’ll focus it!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
