### ISSUE TITLE
Hold and drag "Send" button for management options

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#1325]
Hard to explain in title, but spurred a bit on from the #1324 PR

Basically the "Send Comment" button at the bottom of the issue/PR, I wonder if we could do something when as a user I hold that?

UI wise I was thinking something stylistically like Quick Actions, but triggered by long press (though 3d touch would be slick too!)

However, something like this could also work if done correctly: https://github.com/bradjasper/RadialMenu

Options could be "Comment & Lock/Unlock", "Comment & Close/Open", "Just Comment". Opens door for more contextual management as well I suppose

@rnystrom Yay? Nay? ~~Fifty shades of Gray?~~

**Comment by rnystrom** [comment]
Interesting idea! FB messenger and Mesaages.app both have extra buttons. Maybe we could follow suit?

Or even add a new button in the tray below? Left of preview?

My biggest concern with the 3D Touch on the current icon is just discoverability. Also would be nice to keep the UIs consistent somehow.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
More I think about it, I might just bring back all the stuff in the ... nav bar button. I’m planning on moving the owner/repo nav to a new control anyways.

Did some poking around other apps, and a basic action sheet seems standard. No need to reinvent the wheel here for an editing/action menu.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
