### ISSUE TITLE
Tapping on badge doesn’t work

### ISSUE THREAD

**Issue by RishabhTayal** [rnystrom/GitHawk#1331]
Tapping on a badge shows “something went wrong”

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.16.0 (1513134612)
Device: iPhone X (iOS 11.2.1)
TestFlight: false
</pre>
</details>

**Comment by rnystrom** [comment]
A little confused what badge you’re talking about?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by RishabhTayal** [comment]
Sorry for the little description. Here is a video. 

https://www.dropbox.com/s/vldkuudauduvvmh/Untitled.mov?dl=0
