### ISSUE TITLE
CI status not showing

### ISSUE THREAD

**Issue by RishabhTayal** [rnystrom/GitHawk#1336]
The pull requests don’t show CI status in the app. Is this in the feature request?

![GitHawk Upload by RishabhTayal](https://i.imgur.com/xcpu6Xh.jpg)

![GitHawk Upload by RishabhTayal](https://i.imgur.com/SyyDOj5.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.16.0 (1513134612)
Device: iPhone X (iOS 11.2.1)
TestFlight: false
</pre>
</details>

**Comment by Sherlouk** [comment]
This is definitely a feature I want too! There's #419 to track the actual CI status of a PR and #918 to add a merge button!

Closing this as the discussion can be in those issues 😄
