### ISSUE TITLE
“Feed” of updates for repositories you starred: issues/PRs/code updates etc

### ISSUE THREAD

**Issue by CameraPost** [rnystrom/GitHawk#1337]
Purpose is to provide a way to check out what’s happening on Github without needing to subscribe to all notifications.

I don’t know which updates may turn-out to be particularly interesting. My guess is that code updates or at least meaningful feature updates would make sense to be included in Feed, if possible to determine what those are.

Optionally some notion of ranking/filtering for particularly active updates.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Not sure if this fits with what GitHawk tries to do. Time for a vision? Also, if this would be added, where do you expect it to be? cc @rnystrom 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Ya this is pretty out of scope for the time being. I want to keep the focus on personal project productivity and less on consumption.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
