### ISSUE TITLE
Tapping more options on iPad notifications crashes the app

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#1340]
Probably happens because the action sheet has no `barButtonItem` associated with it?

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.17.0 (1514903367)
Device: iPad7,3 (iOS 11.2.1)
TestFlight: true
</pre>
</details>

**Comment by BasThomas** [comment]
Confirmed - crashes when dragging from 50% to 75% on iPad.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dkhamsing** [comment]
Was gonna report, thx 🙏 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
