### ISSUE TITLE
Sort milestones by due date and title

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#1341]
Should be from low > high or opposite?

![GitHawk Upload by BasThomas](https://i.imgur.com/lwLKoZP.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.17.0 (1514903367)
Device: iPad7,3 (iOS 11.2.1)
TestFlight: true
</pre>
</details>

**Comment by Sherlouk** [comment]
I'd say order by due date as priority 1, if undefined (as your example is) then yea order it 1.17.0 -> 1.18.0 -> 2.0.0

**Comment by rnystrom** [comment]
Anyone wanna pick this off? Should be easy. Here's where they are sorted:

https://github.com/rnystrom/GitHawk/blob/master/Classes/Milestones/GithubClient%2BMilestones.swift#L28
