### ISSUE TITLE
Reaction Cell Size Incorrect

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#1356]
![img_1746](https://user-images.githubusercontent.com/15193942/34624485-618eaac8-f24d-11e7-8c90-2b1faafd63b9.PNG)

This issue has gone around quite a lot recently, and due to its size there appears to be a number of issues on it, so probs good to take a look!

https://github.com/danielmiessler/SecLists/pull/155

For this, the cell size seems to be incorrect because when you horizontally scroll they disappear too early?

**Comment by jens1o** [comment]
haha, lol
