### ISSUE TITLE
Use "Card" design for reviews

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#1359]
![img_1747](https://user-images.githubusercontent.com/15193942/34625435-8f5a9856-f250-11e7-8dd7-59f13a29bd76.jpg)

I feel this looks a bit weird with the mismatch UI, I think if we turned the review into it's own card it would look a lot nicer! (Basically just more padding and rounded edges!)

@rnystrom

**Comment by rnystrom** [comment]
Ahhhh thanks. Knew I forgot something.
