### ISSUE TITLE
Can’t open source code for some link.

### ISSUE THREAD

**Issue by cpedia** [rnystrom/GitHawk#1371]
I favorited the project of ofmeet-openfire plugin. When I get into the source code of following:

https://github.com/igniterealtime/ofmeet-openfire-plugin/blob/master/ofmeet/src/java/org/jivesoftware/openfire/plugin/ofmeet/OfMeetPlugin.java

I got the blank page. Please look into it. Thanks.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.16.0 (1513134612)
Device: iPhone X (iOS 11.2.1)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment]
Weird - it seems to work for me. Did we do something here since 1.16 @rnystrom? ![GitHawk Upload by BasThomas](https://i.imgur.com/Mrr5Xc6.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
I've just installed the latest app store build, and can view the file fine so doesn't seem to be a version dependent thing (though I know scroll performance has changed in the most recent TF build)

(6s Plus)

**Comment by rnystrom** [comment]
My guess is the memory issue which can be sporadic. Should be fixed in 1.17.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
