### ISSUE TITLE
3D Touch Quick actions (app icon) are circles

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#1374]
Names of the icons changed probably?

![GitHawk Upload by BasThomas](https://i.imgur.com/b4nPIdi.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.17.0 (1515261323)
Device: iPhone X (iOS 11.2.1)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
Is this a debug build (no beta feedback option)? Maybe a problem locally? Working for TestFlight.

![GitHawk Upload by rnystrom](https://i.imgur.com/bYQqrSs.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Can confirm mine works on TF build too!

**Comment by BasThomas** [comment]
Weird - only happening in Spotlight. Other apps work fine. Force reboot would probably fix it I guess? From the home screen it works... 🙄

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
🤷‍♀️
