### ISSUE TITLE
Review comments corner rendering off

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#1383]
![GitHawk Upload by BasThomas](https://i.imgur.com/ObYBph8.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.17.0 (1515261323)
Device: iPad7,3 (iOS 11.2.1)
TestFlight: true
</pre>
</details>

**Comment by Sherlouk** [comment]
#1376 _might_ fix this?

**Comment by BasThomas** [comment]
Seems like it does, looking at the screenshots. Closing!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
