### ISSUE TITLE
Consider adding a page for /pulls and /issues

### ISSUE THREAD

**Issue by orta** [rnystrom/GitHawk#1384]
I pretty regularly check these https://github.com/issues and https://github.com/pulls

I realize this is also the role of the notifications page - but maybe they could have a switch view. 
  

![screen shot 2018-01-08 at 10 10 11 am](https://user-images.githubusercontent.com/49038/34676868-4dffbb08-f45c-11e7-8082-7d95201cdbc0.png)
![screen shot 2018-01-08 at 10 11 50 am](https://user-images.githubusercontent.com/49038/34676874-520001c2-f45c-11e7-8d68-b923a84f8bb2.png)

**Comment by orta** [comment]
This is useful because it tells me when I should be poking people because it's been x amount of days

**Comment by Sherlouk** [comment]
Use this page all the time, would love to have it! Is this the same as #1265?

**Comment by orta** [comment]
Yep
