### ISSUE TITLE
[Request] ability to attach image to bug report

### ISSUE THREAD

**Issue by gingerbeardman** [rnystrom/GitHawk#1392]
I'm having to use imgur as a workaround.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.17.0 (1515261323)
Device: iPhone 6s (iOS 11.2.2)
TestFlight: true
</pre>
</details>

**Comment by BasThomas** [comment]
Hey @gingerbeardman - you can! If you scroll the markdown bar to the left, the upload image is revealed: ![GitHawk Upload by BasThomas](https://i.imgur.com/I6UEKhr.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
I just love how you used the feature, the talk about the feature @BasThomas 🙌 

I've also not thought about how you can use iOS 11 screenshot editor as a way to add markup, I know we wanted to add our own (and still should) but that's definitely a good solution in the meanwhile

**Comment by gingerbeardman** [comment]
Oh! I would have never guessed you could school the markdown bar.

**Comment by BasThomas** [comment]
Then we should look into making that more discoverable. 

Also fun fact: we actually use imgur for uploads as GitHub doesn’t have a public API for theirs. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
