### ISSUE TITLE
More options button “area”/view in comments off-center

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#1393]
![GitHawk Upload by BasThomas](https://i.imgur.com/15ZlTnZ.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.17.0 (1515261323)
Device: iPhone X (iOS 11.2.2)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
On purpose, right of icon aligns with padding

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
