### ISSUE TITLE
Distinguish between repository and organization

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#1408]
![GitHawk Upload by BasThomas](https://i.imgur.com/xZveydk.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.17.0 (1515882587)
Device: iPhone X (iOS 11.2.2)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
I was thinking of adding an `@` before the username. What do you think?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Yeah, I think that is a simple and OK fix. Can't think of anything better for sure.
