### ISSUE TITLE
Remove username from ... repository menu

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#1409]
Already have it in the navigation bar. 

![GitHawk Upload by BasThomas](https://i.imgur.com/KLNFSZE.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.17.0 (1515882587)
Device: iPhone X (iOS 11.2.2)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
Knew I forgot something 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
