### ISSUE TITLE
See more bubbles sometimes spawn on wrong comment

### ISSUE THREAD

**Issue by SD10** [rnystrom/GitHawk#1415]
The bubble on pyraniq's comment seems to be linked to the bubble for the main post of the PR:

![image_uploaded_from_ios_720-1](https://user-images.githubusercontent.com/7445580/34919216-3ccbc408-f925-11e7-9939-938be682db42.png)

If I expand the original post, both bubbles disappear. If I try to double tap on the bubble for pyraniq's comment, it gives the main post a thumbs up.  Using FLEX it looks like these are the same view 🤔

**Comment by Sherlouk** [comment]
We not hiding it on prepare for reuse maybe?

**Comment by rnystrom** [comment]
@Sherlouk I bet you’re exactly right

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Ahh think I found the fault: https://github.com/rnystrom/GitHawk/pull/1406/files#diff-7a2ac7b42147b46d47c53153b3ab62fbR287

We cast to a base cell, in the screenshot above it's a review cell which AFAIK is handled differently
So yea it's most likely a prepare for reuse, but caused by the above line not matching

**Comment by rnystrom** [comment]
@Sherlouk aha! Great find. Wanna PR it real quick?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Actually I was wrong, review cells **can** cast to IssueCommentBaseCell - so actually not sure

**Comment by SD10** [comment]
Update:

It seems like this bug never occurs until I go to the home screen and then re-enter the app. Every time I re-enter, the number of bubbles seems to duplicate. They disappear/reappear randomly as scrolling. If you exit / re-enter a few times, then pull down to refresh, you'll end up with like 4 bubbles.

Maybe this will help with debugging
