### ISSUE TITLE
Crash when trying to open PR

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#1427]
Opening on behalf of @SD10

App crashes when opening SwifterSwift/SwifterSwift#364

Steps included opening the PR fine initially
Beginning to write a response
Clicking a link to a file (which opened our SafariVC)
Clicked done before the file had loaded
Navigated back to index
and now can't get back into the PR

The response included a mention and some text, possibly related or maybe not
Can't reproduce on my phone (can view the PR just fine though)
Latest TF

[Crash Report](https://github.com/rnystrom/GitHawk/files/1636802/2018-01-16_12-00-51.7492_-0600-b6c4a2795aa91b15d47726e126b682ce3632b978.txt)

**Comment by Sherlouk** [comment]
REPRODUCIBLE

Step 1: Load an Issue or Pull Request
Step 2: Begin to write a new comment, make sure you **add a new line**
Step 3: Press Back to leave the Issue
Step 4: On trying to re-enter, it'll crash

@rnystrom @SD10

**Comment by BasThomas** [comment]
Crashes [here](https://github.com/GitHawkApp/MessageViewController/blob/master/MessageViewController/MessageViewController.swift#L124) because the `scrollView` is `nil`.

**Comment by Sherlouk** [comment]
Any idea on a fix, besides obviously just inserting a ? to avoid the issue 😅 

Clearly `layout` is getting called from a notification which is being triggered before `setup`

Move the observers to after we call setup?

**Comment by Sherlouk** [comment]
Link to crash on Fabric: http://crashes.to/s/34f0223ea50

**Comment by SD10** [comment]
Great work on this @Sherlouk 👏
