### ISSUE TITLE
Stop caching empty new comments

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#1428]
In my User Defaults (as viewable by using FLEX) I have a tonne of empty strings assigned to `com.freetime.MessageViewController.issue...` which is the mechanism behind filling the new comment field if you leave and re-enter.

We should only save the string if it's actually got something in there though!

**Comment by Sherlouk** [comment]
Issue is we call `cache()` [here](https://github.com/GitHawkApp/MessageViewController/blob/master/MessageViewController/MessageViewController.swift#L41)

but the cache method itself (https://github.com/GitHawkApp/MessageViewController/blob/master/MessageViewController/MessageViewController.swift#L139-L142) doesn't actually check if there's a value

We should check for the value first, otherwise remove value at key to make sure it's cleaned up!

**Comment by rnystrom** [comment]
😱 good find, this is blocking 1.17

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
