### ISSUE TITLE
Squished images

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#1437]
![GitHawk Upload by BasThomas](https://i.imgur.com/rHhEWkD.jpg)

Looks fine in NYTPhotoViewer

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.17.0 (1515991057)
Device: iPad7,3 (iOS 11.2.1)
TestFlight: true
</pre>
</details>

**Comment by Sherlouk** [comment]
Caused by the capped heights change, probably just need to change the content mode on the image view

**Comment by vanyaland** [comment]
#### How about this content mode?

![simulator screen shot - ipad pro 9 7-inch - 2018-01-17 at 13 27 59](https://user-images.githubusercontent.com/8586063/35038201-1b3a40f4-fb8b-11e7-86bc-9494ef0b1423.png)
