### ISSUE TITLE
Crash from navigating from issue to inbox

### ISSUE THREAD

**Issue by SD10** [rnystrom/GitHawk#1441]
App crashes after viewing MessageKit #449 and returning to inbox

Debug notes:
- User defaults for 449 is empty
- If I interrupt the view from scrolling to bottom when viewing the issue, it doesn’t crash on return to inbox
- After interrupting the scrolling, extra white space is rendered on GitHawk comments. The issue no longer crashes while white space is present

I think this is related to scrolling or the content size. I can prevent the crash from scrolling to the top of the issue before exiting. This issue only crashes on return to inbox. Viewing it from the repo page works fine. I noticed that entering from the repo page doesn’t scroll to bottom automatically as well. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
@SD10 do you have a trace? I’ll add you to Fabric so you can see crashes too. If you can pinpoint where this crashes that’d be great!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
What information do you need to add me to fabric? I don't have a trace but it would be super useful.

**Comment by rnystrom** [comment]
Invite sent 😄

**Comment by rnystrom** [comment]
I wonder if its this http://crashes.to/s/e89d652e6bb

**Comment by SD10** [comment]
Appreciate it 👍 Thanks Ryan 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
