### ISSUE TITLE
Allow selection in HTML / text cells

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#1445]
Would be awesome if we can just copy and paste a comment (or a part of it)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.17.0 (1515991057)
Device: iPad7,3 (iOS 11.2.2)
TestFlight: true
</pre>
</details>

**Comment by Sherlouk** [comment]
Dupe of #609 ?
