### ISSUE TITLE
Some IGListKit Objective-C files don't have code highlighting

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#1454]
Go to IGListKit/Source/IGListAdapter.h and .m, they aren't highlighted. Not sure why.

**Comment by brurend** [comment]
Cleaning derived data and building again after Xcode was done indexing fixed it for me.

**Comment by rnystrom** [comment]
@brurend this is about code highlighting in GitHawk 😋

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by brurend** [comment]
I was talking about GitHawk, I cloned the project and built it, IGListKit files weren't highlighted (some other pods weren't as well).

**Comment by LucianoPAlmeida** [comment]
Hey @rnystrom I think I found the issue
It appears that path extension "m" was not being recognized as objc language 
So I did this hardcoded test and it seems that the language it has to be passed is not file extension "m" but "objc" 
![screen shot 2018-02-19 at 21 52 18](https://user-images.githubusercontent.com/8292651/36402737-6733ce46-15bf-11e8-8dbf-5adced369bc4.png)

I'm working on a fix, it appears that this library has automatic language detection if you don't pass the language explicitly, I will do a test and if it works I'll send a PR :)

**Comment by rnystrom** [comment]
@LucianoPAlmeida awesome!!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
