### ISSUE TITLE
Take over GitHub routing internally

### ISSUE THREAD

**Issue by orta** [rnystrom/GitHawk#1459]
So if you click this link, https://github.com/jest-community/vscode-jest/issues/222

It would show the native view controller

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.16.0 (1513134612)
Device: iPhone X (iOS 11.2.1)
TestFlight: false
</pre>
</details>

**Comment by Sherlouk** [comment]
Do the following issues cover the functionality you're suggesting/

#146 
#441

**Comment by orta** [comment]
Yep :+1:
