### ISSUE TITLE
Archived notifications menu seems superfluous?

### ISSUE THREAD

**Issue by gingerbeardman** [rnystrom/GitHawk#1460]
I use archived notifications as a method of jumping to issues I'm currently dealing with. It's an inbox of read items after all. 

Currently you have to tap the triple dot and then choose Archived from the menu. What a pain 😂 

It'd be great if there triple dot, or whatever icon might make more sense, just went straight to the Archived list without the needless menu in between?

![GitHawk Upload by gingerbeardman](https://i.imgur.com/7jhFdg0.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.17.0 (1516422452)
Device: iPhone 6s (iOS 11.2.2)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
If you have unread notifications, it’ll actually show a list of repos so you can browse repo notifications 😋

![GitHawk Upload by rnystrom](https://i.imgur.com/IlwSXFc.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gingerbeardman** [comment]
Ha!
