### ISSUE TITLE
Clear text cache after sending comment

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#1461]
Now that we trim white space, it will no-op when there is no text. Meaning if you have a previous draft it will always reappear.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.17.0 (1516422452)
Device: iPhone X (iOS 11.2.2)
TestFlight: true
</pre>
</details>

**Comment by Sherlouk** [comment]
https://github.com/rnystrom/GitHawk/commit/842260dad5fed5a7f04c4ae0679b12136568a8f9#diff-e61935e8dd122c89f47fbc6eb1246fa6R142

If someone wants to pick this up, should be as simple as dropping a "userDefaults.remove(for: key)" in the guard for "isEmpty"

**Comment by rnystrom** [comment]
@Sherlouk spot on. So I fixed this locally w/ a hotfix branch and resubmitted 1.17 last night b/c this bug was driving me nuts. Now that MessageViewController has moved to an external repo, we'll need to handle it there.
