### ISSUE TITLE
Cannot sign in

### ISSUE THREAD

**Issue by yoav-kali** [rnystrom/GitHawk#1464]
I just downloaded the app, and **whenever I pressed “sign in” it just crashed**. I ended up using a personal access key instead.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.17.0 (1516591557)
Device: iPhone 6s (iOS 11.2.2)
TestFlight: false
</pre>
</details>

**Comment by rnystrom** [comment]
Got this reported on Twitter too! Going to fix this ASAP.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
[Our press team is on it.](https://twitter.com/githawk/status/955550843138445312)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
