### ISSUE TITLE
Crash on Review GH Access

### ISSUE THREAD

**Issue by dnlggr** [rnystrom/GitHawk#1471]
Hi, cool project! 😃👌

Minor bug report: If I go to Settings > Review GitHub Access, the app crashes. I‘m running the latest 1.17.0 version of GitHawk and the latest iOS 11.2.2 on an iPhone 6.

I used _sign in via GitHub_ not a personal access token, if that makes any difference.

Thanks, and keep it up! 🐙

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.17.0 (1516591557)
Device: iPhone 6 (iOS 11.2.2)
TestFlight: false
</pre>
</details>

**Comment by rnystrom** [comment]
Ack ya, we have a fix in review w/ Apple right now. #1467 kicked off a new build. Will be fixed shortly!
