### ISSUE TITLE
Optionally hide closed issues and PRs

### ISSUE THREAD

**Issue by hawkrives** [rnystrom/GitHawk#1473]
Hi all,

First off, thanks for working on this wonderful thing! _So_ much nicer than github's mobile site. 

I had a feature request (I skimmed the issues and didn't see this; apologies if it's been discussed already) – would y'all be open to a way to hide the closed issues / PRs from the list? I really just care about the open ones on my repositories :smile:

Thanks again! Have a great week.

**Comment by rnystrom** [comment]
Thanks for this! We're tracking open/closed, searching, and all sorts of filtering in #287. This is pretty high on my list of TODOs right now. I'll boost the priority on that issue.
