### ISSUE TITLE
More emoji bar oddness

### ISSUE THREAD

**Issue by gingerbeardman** [rnystrom/GitHawk#1476]
1. Tap emoji bar
2. Tap thumbsup
3. Close issue

![GitHawk Upload by gingerbeardman](https://i.imgur.com/6tMex00.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.17.0 (1516422452)
Device: iPhone 6s (iOS 11.2.2)
TestFlight: true
</pre>
</details>

**Comment by gingerbeardman** [comment]
related to: https://github.com/rnystrom/GitHawk/issues/1391 ?

**Comment by rnystrom** [comment]
Let's keep it all in one place

**Comment by gingerbeardman** [comment]
Another one

![GitHawk Upload by gingerbeardman](https://i.imgur.com/vhUy3mZ.jpg)
