### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by 1iros** [rnystrom/GitHawk#1477]
My eyes! It burns!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by viktorgardart** [comment]
Duplicate #198

**Comment by BasThomas** [comment]
@1iros in the meantime, we do support Smart Invert!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by 1iros** [comment]
Strange. I searched for dark mode in here but nothing come up. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
It's because of paging; we only check locally within GitHawk at the moment. It could use some love for sure!
