### ISSUE TITLE
@ symbol shortcut

### ISSUE THREAD

**Issue by chrissimpkins** [rnystrom/GitHawk#1481]
Great application Ryan! Just discovered it recently and love it.

This is a request for an optional `@` symbol in the shortcut bar.  Some 3rd party keyboards make this commonly used character less accessible than it should be for GitHub...

<img src="https://user-images.githubusercontent.com/4249591/35588128-b4f546fc-05cd-11e8-9674-2618da787ad4.jpeg" width="50%" />

**Comment by BasThomas** [comment]
That's actually a quite interesting idea - we could then use the normal keyboard again with the `return` key. One downside I see is that the markdown bar would get (more) confusing: it would house preview, markdown shortcuts, image upload **and** `@` / `#` (for when we implement #219)

**Comment by chrissimpkins** [comment]
I am speaking from absolutely no iOS dev experience here so take with a grain of salt because I have no idea about the amount of effort required.  Can you implement a customizable bar that allows users to select what they want to appear there from a set of useful formatting shortcuts, preview launcher, and symbols?

**Comment by SD10** [comment]
> One downside I see is that the markdown bar would get (more) confusing

I agree with this but I also have some ideas to make typing code easier. Possibly short cuts for:
`< >`, `{ }`, `[ ]`, and `( )` that when you press them it nests you inside of them. This is because typing code examples on my phone is a nightmare. 

Maybe we could add a button to the markdown bar that toggles to a different set of buttons?

**Comment by rnystrom** [comment]
I’m down with this idea! I’d actually love to have the return key back.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
