### ISSUE TITLE
Keep tweaking manage action design

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#1495]
Had an idea today. Instead of circles + labels, make a larger rounded-square that contains the icon and label. I think this would be even easier on the eye by totally containing the button.

On a related note, I need more color ideas for other actions. Idk where to find them, I need a GitHub color palette book 😄

**Comment by rnystrom** [comment]
![simulator screen shot - iphone x - 2018-02-05 at 22 27 05](https://user-images.githubusercontent.com/739696/35840797-58a1f190-0ac6-11e8-9ae1-f8ba72c0af81.png)

**Comment by Sherlouk** [comment]
GitHub Color Palette:

White
Gray
Another shade of Gray
Grey if you're American
Little green in places
Couple elements of blue

**Comment by rnystrom** [comment]
@Sherlouk I need to play with the layout a little, the buttons are really dynamic based on your permissions and type of issue, but if we can evenly fill we should 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
