### ISSUE TITLE
Markdown parser broken?

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#1500]
![GitHawk Upload by BasThomas](https://i.imgur.com/6YejZjr.jpg)
Username is not recognized 

![GitHawk Upload by BasThomas](https://i.imgur.com/9TFAj04.jpg)
Markdown not parsed

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.18.0 (1518017959)
Device: iPhone X (iOS 11.2.5)
TestFlight: false
</pre>
</details>

**Comment by rnystrom** [comment]
Looks like probably two different issues. The username one is weird, but the link is probably having a # inside it? Will investigate! Should be easy to repro with a unit test

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Referenced issues for easy nav

Moya/Moya#1565

Moya/Moya#1567

**Comment by rnystrom** [comment]
Ah so usernames still work, its just the bold style is wrong. Likely from

https://github.com/rnystrom/GitHawk/commit/220a5a3373fba8a8a250e2a3df5a20373c7334dd

**Comment by BasThomas** [comment]
Ah that makes sense yeah. Wasn't sure if they were related.

**Comment by rnystrom** [comment]
Already fixed locally

**Comment by rnystrom** [comment]
Hmm something is off still with usernames

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
