### ISSUE TITLE
File changes has content under nav bar

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#1513]
![GitHawk Upload by BasThomas](https://i.imgur.com/PuGtSvC.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.18.0 (1518216007)
Device: iPhone X (iOS 11.2.5)
TestFlight: false
</pre>
</details>

**Comment by rnystrom** [comment]
Can you scroll and see it? Or is it a bad inset?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Can scroll yeah. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
