### ISSUE TITLE
Flex not working on TestFlight build

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#1516]
@rnystrom caused by ci changes?

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.18.0 (1518216007)
Device: iPhone 6s Plus (iOS 11.3)
TestFlight: false
</pre>
</details>

**Comment by rnystrom** [comment]
Hmm probably

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Report dump is saying TestFlight false but definitely was from TF - so yea definitely points to incorrect build being uploaded!

**Comment by rnystrom** [comment]
Found it, should be fixed!
