### ISSUE TITLE
Relative URL images do not load

### ISSUE THREAD

**Issue by bobheadxi** [rnystrom/GitHawk#1518]
in READMEs, images where the src is a relative URL to an image within the repository don’t load

e.g. this [repository README](https://github.com/ubclaunchpad/inertia/blob/master/README.md)
<div>
<img src="https://user-images.githubusercontent.com/23356519/36290092-7c1e61a8-1278-11e8-9b6a-13b523e8a28d.PNG" width="40%"/>
<img src="https://user-images.githubusercontent.com/23356519/36290093-7c366cee-1278-11e8-9025-0590d216457c.PNG" width="40%"/>
</div>

**Comment by rnystrom** [comment]
Ugh, I swore we had this fixed. But I can notice it on other repos too. If anyone has a chance to take a look I’d be 🙏🙏🙏

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
Don't understand enough about how GitHawk loads HTML yet but tapping the image view tries to load the incorrect URL: `http://github.com/.static/inertia-with-name.png`. It's missing the user and repo paths.

**Comment by BasThomas** [comment]
Probably a pretty easy fix then?
