### ISSUE TITLE
Improve the new @ mention shortcut

### ISSUE THREAD

**Issue by SD10** [rnystrom/GitHawk#1521]
The current action uses `Operation.line` which is terrible IMO. This means it is useless for making mid-message mentions because `@` always gets appended to the beginning of the text. My fault for not thinking about this when submitting #1507.

I'm thinking I should revise this to insert in place. Then it can be used for other things too: email, code, etc.

**Comment by rnystrom** [comment]
Oh ya! I noticed this too. Yes pls, let’s improve.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
