### ISSUE TITLE
Super slow redraws

### ISSUE THREAD

**Issue by gingerbeardman** [rnystrom/GitHawk#1525]
Not really sure why this is happening. My phone isn't on low power mode. It's an iPhone 6s. 

Interesting to see the way the app lays things out. 

https://youtu.be/LFH0woc_Jyg

https://youtu.be/qWAMh0uPKUo

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.18.0 (1518216007)
Device: iPhone 6s (iOS 11.2.5)
TestFlight: false
</pre>
</details>

**Comment by rnystrom** [comment]
Yikes!! @gingerbeardman would you be interested in running a Time Profile to help us track down what this is?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gingerbeardman** [comment]
A reboot of my phone made this go away. But happy to run whatever you think might be useful

**Comment by rnystrom** [comment]
Hmm ok! If it comes back we can revisit 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
