### ISSUE TITLE
Title and description on image upload should be added with the image tag

### ISSUE THREAD

**Issue by gingerbeardman** [rnystrom/GitHawk#1527]
When you upload an image there's space for an (optional) title and description. Where does this content go? imgur?

I expected it to be added as part of the image markdown?

![GitHawk Upload by gingerbeardman](https://i.imgur.com/2FmEPyW.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.18.0 (1518216007)
Device: iPhone 6s (iOS 11.2.5)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment]
Yeah, goes to imgur.

**Comment by rnystrom** [comment]
We should probably change this to just be a title, and when you add a title use it as the alt text in markdown. Now that you mention it, it’s a little bizarre that these never get used on GitHub/Hawk. cc @Sherlouk

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Seems legit, marking starter task shouldn't be difficult for someone to pick up

FWIW the original plan was to support other uploading strategies like albums and such and have it link to Imgur but that never got worked on hence the confusion.

**Comment by jamuc** [comment]
I'll give it a shot
