### ISSUE TITLE
Incorrect merge status

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#1531]
![img_1866](https://user-images.githubusercontent.com/4190298/36353427-a3691ea6-14c6-11e8-9b0b-0a7bfc70fe23.PNG)
![img_c94a6af49341-1](https://user-images.githubusercontent.com/4190298/36353428-a37fb9cc-14c6-11e8-9a04-91fdc9f95f10.jpeg)

Says some checks failed when in fact all are in progress

As seen in #1530

**Comment by rnystrom** [comment]
I think this is just b/c a pending state [doesn't exist](https://github.com/rnystrom/GitHawk/blob/master/Classes/Issues/Merge/IssueMergeSummaryModel.swift#L14-L18), and that status is just a [reduction to success/failure](https://github.com/rnystrom/GitHawk/blob/master/Classes/Issues/Merge/IssueMergeSectionController.swift#L68). Should be easy to fix.

**Comment by BasThomas** [comment]
Yeah, thought so too. Looking into it. Any idea what an "[expected](https://developer.github.com/v4/reference/enum/statusstate/#expected)" commit status is?

**Comment by rnystrom** [comment]
@BasThomas lol I wondered too! I have no idea. The [docs](https://developer.github.com/v4/enum/statusstate/) leave a lot to be desired 😐

Thanks for picking this up!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Yeah exactly 😂

**Comment by BasThomas** [comment]
Unrelated, but how do you get the check image? (read: why is it a user avatar sometimes?)

**Comment by rnystrom** [comment]
Noticed that too, it’s from [this](https://github.com/rnystrom/GitHawk/blob/master/gql/Fragments.graphql).

Maybe we can find whatever the V3 API is using or figure out if it’s a bug and submit a ticket. [This is all that exists](https://developer.github.com/v4/object/statuscontext/).

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Seems to be [roughly the same](https://developer.github.com/v3/repos/statuses/#list-statuses-for-a-specific-ref) in v3.
