### ISSUE TITLE
App crashes when attempting to login

### ISSUE THREAD

**Issue by jamuc** [rnystrom/GitHawk#1535]
## Description
When tapping the login button the app crashes.

Reason: Client ID is read from the environment and it's force unwrapped: 
```swift
private let loginURL = URL(string: "http://github.com/login/oauth/authorize?client_id=\(Secrets.GitHub.clientId)&scope=user+repo+notifications")!
```

**Comment by SD10** [comment]
Hey @jamuc, sorry this happened. Could you please tell us what version of GitHawk are you using?

**Comment by jamuc** [comment]
Hey @SD10, that's a fast response time. Not as bad as I thought. Running the app locally in the simulator. Hadn't setup GitHub secret and client ID. "SET ON CI" is configured by default and then this guard clause doesn't fire:
```swift
guard let value = processInfo.environment[named] else {
            print("‼️ Missing Environment Variable: '\(named)'")
            return nil
        }
```

**Comment by jamuc** [comment]
@SD10 I can add a pr to fix that. At least so that the guard clause gets fired and makes it more clear what is happening. Just need a moment :)
