### ISSUE TITLE
Commit missing from #1536

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#1541]
#1536 is missing commits in GitHawk, no idea why?

![GitHawk Upload by BasThomas](https://i.imgur.com/IenMGlO.jpg)

![GitHawk Upload by BasThomas](https://i.imgur.com/AC3qXUu.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.18.0 (1518753170)
Device: iPhone X (iOS 11.2.5)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
They were amends. Does web show amends?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Ah. As seen in the first picture, yes. :)

**Comment by rnystrom** [comment]
Looks like GitHub just updates the timeline placement of the commit on web bc there’s still only one. We’re not doing any re ordering of timeline events, so the API would need to shift the commit placement. Maybe we can file a ticket?

Closing bc I don’t want to reorder the timeline stuff on the client (complex and error prone).

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
