### ISSUE TITLE
Search history includes auto-searched while typing

### ISSUE THREAD

**Issue by ggoofer** [rnystrom/GitHawk#1557]
Search results updated continuously while typing and are included in history. E.g. If I search “Karabiner” I get

K
Kara
Karab
Karabine
Karabiner

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.17.1 (1516660142)
Device: iPhone 8 Plus (iOS 11.2.5)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment]
This was brought up in #791 but was closed as expected behavior at that point. @rnystrom, want to revisit / reconsider?

**Comment by rnystrom** [comment]
I'm open to fixing this b/c I agree it's pretty goofy. cc @heshamsalman any ideas?

**Comment by heshamsalman** [comment]
One solution would be to only save strings for searches where the user clicks into something. 
Solutions centered around toning down the debounce time won't actually fix this problem.

**Comment by rnystrom** [comment]
Simple, love it. Let's go w/ that!
