### ISSUE TITLE
Ability to select text in a comment?

### ISSUE THREAD

**Issue by gingerbeardman** [rnystrom/GitHawk#1559]
I miss this, I often select text to copy, look-up, translate. 

Can it be added?

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.18.0 (1518753170)
Device: iPhone 6s (iOS 11.2.5)
TestFlight: true
</pre>
</details>

**Comment by Sherlouk** [comment]
Dupe of #609?

**Comment by gingerbeardman** [comment]
Yes, dupe.

Shall I close?
