### ISSUE TITLE
Nav bar title is mis aligned on iPad

### ISSUE THREAD

**Issue by rizwankce** [rnystrom/GitHawk#1570]
Happening only from search and bookmark and not in notifications.
![GitHawk Upload by rizwankce](https://i.imgur.com/YTvWYwL.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.18.0 (1519226434)
Device: iPad Pro (iOS 11.2)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
Ew!!! Ya bad bug. Lets fix before 1.18

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
