### ISSUE TITLE
Inbox Zero when all 1st page is read

### ISSUE THREAD

**Issue by flovilmart** [rnystrom/GitHawk#158]
We see the inbox zero screen when the 1st page of notifications is read. In order to see further notifications, we need to go to the 'All' section, load more pages, and then it would display correctly.

**Comment by rnystrom** [comment]
Ah, interesting! I'll have to mull over how to handle this. I wish the API gave us a total-unread meta field...

**Comment by flovilmart** [comment]
Or split in 2 calls for the sake of correctness when toggling the switch

**Comment by Sherlouk** [comment]
Notifications has now got a second "Archives" page which displays read messages resolving this issue.
