### ISSUE TITLE
Partial search results

### ISSUE THREAD

**Issue by jdisho** [rnystrom/GitHawk#1581]
I occurred a problem while searching the issues. 

1. Initial search results - 0 results 🤔

![GitHawk Upload by jdisho](https://i.imgur.com/p29z7If.jpg)

2. Press "Load more" - 2 new results 😳

![GitHawk Upload by jdisho](https://i.imgur.com/Qbwp9zt.jpg)

3. Press "Load more" **couple** of time - ...🤨🤨🤨

![GitHawk Upload by jdisho](https://i.imgur.com/6oRUUr6.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
This is b/c the search is only filtering already-loaded results. It's not actually going out to the network for new results. #287 is tracking advanced search/filter for Issues/PRs.

Would love for someone to take a crack at this!
