### ISSUE TITLE
Separation of closed/open issues & PR’s

### ISSUE THREAD

**Issue by agisilaos** [rnystrom/GitHawk#1594]
Since I started using GitHawk I thought that something was missing in the issues/ PR’s views inside a repo. Currently closed and open issues (same with PR’s) are on the same Table view and that’s a bit overwhelming. Not sure if this issue was opened before but I thought I will go ahead and write about it. 

A good solution for this issue would be to create two separate tabs for closed and open PR’s/Issues

**The current state of the view**

![GitHawk Upload by agisilaos](https://i.imgur.com/pPvcWzQ.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
The tricky part is paging with the current endpoints, which is not as easy as splitting them.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jdisho** [comment]
Isn’t this related to: https://github.com/rnystrom/GitHawk/issues/287 ?
@BasThomas 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Ya planning on improving this via filter/sort in #287
