### ISSUE TITLE
App Icon badge show 1 but no new notifications

### ISSUE THREAD

**Issue by kimdv** [rnystrom/GitHawk#1597]
Hi!

My app icon show “1” but no new notification when app open. 

I have opened GitHub on web, and see there is a new release notification. I think that’s the reason why :)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.18.0 (1519488669)
Device: iPhone 8 (iOS 11.2.6)
TestFlight: false
</pre>
</details>

**Comment by SD10** [comment]
Looks similar to #1534. @kimdv out of curiosity, do you have "Read On Open" turned on?

**Comment by kimdv** [comment]
Nope! 

I actually had one notification, fastlane made a new release and I think it was that notification that was "unread".

Because when I did a refresh, saw the "Zero indox", pressed the home button without closing it, after a while there was 1 new notification. 

Open the app, there was nothing, and the badge was gone. 

I waited a little again and the badge was 1, and then it started over.

**Comment by BasThomas** [comment]
Should be fixed: https://github.com/rnystrom/GitHawk/pull/1546 :)

**Comment by kimdv** [comment]
🚀💯
