### ISSUE TITLE
App crash when entering emojs

### ISSUE THREAD

**Issue by nathantannar4** [rnystrom/GitHawk#1599]
I can't seem to always reproduce this, but a few times I've gone to make an emoji by entering : following by ) and on the ) the app crashes. Currently running the latest Testflight build version 1.19

Anyone else getting this?

**Comment by jdisho** [comment]
Thank you for raising this issue @nathantannar4

This should be an issue of MessageViewController... @rnystrom you aware of this?

**Comment by rnystrom** [comment]
Can someone post precise repro steps? Bonus for a stack trace.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
