### ISSUE TITLE
Error loading archives

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#1615]
Prob from refactor

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.19.0 (1520219174)
Device: iPhone X (iOS 11.2.6)
TestFlight: true
</pre>
</details>

**Comment by BasThomas** [comment]
Oh and this hit [this `catch`](https://github.com/rnystrom/GitHawk/blob/master/Local%20Pods/GitHubAPI/GitHubAPI/Processing.swift#L27), but then trickled down to show a "Cannot connect to GitHub". Probably want to fix that too; shall I create another issue for it?

**Comment by rnystrom** [comment]
@BasThomas that'd be great!
