### ISSUE TITLE
Cannot edit issue title from issue page?

### ISSUE THREAD

**Issue by gingerbeardman** [rnystrom/GitHawk#1631]
Or at least I can't find a way?

I can only edit this comment. 

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.19.0 (1520219174)
Device: iPhone 6s (iOS 11.2.6)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
Nope this doesn’t exist yet. I think there’s a feature issue out there for it. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gingerbeardman** [comment]
Couldn't find anything in a search (which returned one result each time I pressed "more"!)

**Comment by BasThomas** [comment]
Rename issue/pull request: https://github.com/rnystrom/GitHawk/issues/381
Search result paging: https://github.com/rnystrom/GitHawk/issues/287

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
