### ISSUE TITLE
Links in bullet lists not handled

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#175]
Version: 1.2.0 (910)
Device: iPhone 6s Plus (iOS 11.0)

https://drive.google.com/open?id=0B8FbxFN4A3N6UFdaSFc1azZ1WVE

- [pass](https://google.com)
- [ ] [fail](https://google.co.uk)
- [ ] [fail2][fail2]

[fail2]: https://google.com

Source:
```
- [pass](https://google.com)
- [ ] [fail](https://google.co.uk)
- [ ] [fail2][fail2]

[fail2]: https://google.com
```

**Comment by lDiverse** [comment]
Messaging so it shows in app for me

**Comment by Sherlouk** [comment]
Hmm seems to just be checklists, the square brackets must break the regex used for link detection

**Comment by rnystrom** [comment]
Ack weird, will investigate. Will see how bad a bug this is, but don't want to burn tons of time for rare md bugs. Hopefully just a rendering thing and not with the parser.

**Comment by Sherlouk** [comment]
- [ ] Testing if not first [word](https://google.com)

**Comment by Sherlouk** [comment]
Based on only breaks if first word yh id say this is relatively unlikely and presumably because mmmarkdown doesn’t support checklists so doesn’t concern itself with the edge case
