### ISSUE TITLE
Bug: Part of issue appears underneath navigation bar

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#18]
In the first image below I am scrolled as far up as possible, and parts of the content has extended under the navigation bar -- second image for reference I've pulled down.

iOS 11 beta 2

![image](https://user-images.githubusercontent.com/15193942/27600656-9dc7a164-5b64-11e7-9a07-2afa90350b1d.png)
![image](https://user-images.githubusercontent.com/15193942/27600660-a1d5c48e-5b64-11e7-88c5-b8bf1cde8548.png)

**Comment by rnystrom** [comment]
@Sherlouk wait so in that first image, you haven't scrolled or anything?

**Comment by Sherlouk** [comment]
@rnystrom Nope first image is right at the top, not scrolled

**Comment by rnystrom** [comment]
Gonna chalk this up as an iOS 11 issue. If this is an issue when the GM comes out I'll prioritize, but doesn't seem to be a thing on 10.

**Comment by weyert** [comment]
Yes, I saw this topic mentioned in #116 it's discussed in: 
https://developer.apple.com/videos/play/wwdc2017/204/?time=562

They introduced UIView.safeAreaLayoutGuide and related things. They seem to have made changes for that fat navigation bar title.

**Comment by shaps80** [comment]
I'm having similar issues in a project. I found this worked for me: worth a quick shot.

```swift
if #available(iOS 11.0, *) {
    tableView.contentInsetAdjustmentBehavior = .never
}
```

**Comment by Sherlouk** [comment]
@rnystrom Should maybe look to fix this? Seems to have been in every beta so far, I feel it's relating to new "safe area" apis

**Comment by rnystrom** [comment]
Ya, not super worried about timeliness since 11 still isn't out of beta (and I use 10 😇 ) will get to it

**Comment by viktorgardart** [comment]
Still happening in iOS 11 GM

**Comment by rnystrom** [comment]
Seems weird, doesn't repel when I build with Xcode 9. I'll send out a beta using GM and see what happens.

**Comment by Sherlouk** [comment]
Haven't had it do it to me for a while

I'm on the 11 GM

**Comment by rizwankce** [comment]
Version: 1.9.0 (1513) (App store version) 
OS : iOS 11 GM
Device : iPhone 7 plus

Happening all the time. I will check with Xcode 9 and confirm back.

**Comment by rnystrom** [comment]
I just sent out a new beta built with 9. Anyone able to confirm? @rizwankce are you on test flight?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rizwankce** [comment]
@rnystrom Not yet. I have shared my email already in your twitter DM

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rizwankce** [comment]
Tested again 1.10.0 (1878). Guess it is fixed and can't reproduce it in any way. 👍 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Awesome, so iOS 11 SDK did it then.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
