### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#183]
I think adding CI would be nice. Could prevent things like #182 

---

Candidates:
- https://www.buddybuild.com/
- https://circleci.com/
- ~~https://travis-ci.org/~~ slow

*updated*

**Comment by dkhamsing** [comment]
Candidates:
- https://www.buddybuild.com/
- https://travis-ci.org/

**Comment by rnystrom** [comment]
I'm down for whatever is:

- Free
- high signal (fast, not flaky)

**Comment by dkhamsing** [comment]
I think travisci because of popularity is quite slow.. why don't you give buddybuild a try, pick start plans / free

![screen shot 2017-08-04 at 12 47 23 pm](https://user-images.githubusercontent.com/4723115/28984502-19afb886-7913-11e7-924f-27336560eb1a.png)

**Comment by BasThomas** [comment]
Circle is another option, they are free for open source projects too

**Comment by dkhamsing** [comment]
@BasThomas circle ci is great, but not free for osx :(

**Comment by dkhamsing** [comment]
actually i may be wrong about this but it's not an automated process

https://circleci.com/pricing/#faq-section-os-x
> We also offer the Seed plan for OS X open-source projects. Contact us at billing@circleci.com for access.

**Comment by BasThomas** [comment]
Yes - you'll have to send them an email. I think they respond to them pretty quickly though.

**Comment by dkhamsing** [comment]
@rnystrom ryan i think you have to enable this as the project owner

**Comment by dkhamsing** [comment]
let me know if you need help, going on the sites and connecting the repo is pretty simple

**Comment by rnystrom** [comment]
@BasThomas @dkhamsing which do you feel is the most reliable?

**Comment by BasThomas** [comment]
Both Circle and Travis have been 👍

**Comment by heshamsalman** [comment]
@rnystrom I've used Circle, Travis, and BuddyBuild.

Travis would be great, if it weren't painfully slow -- even on paid tiers. 

BuddyBuild is a super-feature-loaded service. Has a lot of cool stuff built in that you _probably won't_ need but are _nice to have_. Fast, reliable. 

Circle is a no-frills service. Fast, reliable, and lets you SSH into specific builds. 

I'm pretty partial to Circle.

**Comment by dkhamsing** [comment]
I'd vote for BuddyBuild.

**Comment by rnystrom** [comment]
All over the place! Leaning towards Circle (Travis has also been a pain with IGLK)

**Comment by rnystrom** [comment]
#

**Comment by Sherlouk** [comment]
@rnystrom Maybe be worth chucking to towards top of your to-do list? 😄

Would be nice to get a starting point to get a couple tests, and at least make sure things are building!

Maybe even hook up continuous deployment so we get faster builds out to test flight to constantly be looking at latest changes

**Comment by Sherlouk** [comment]
@rnystrom We good to close this since it should all be working now? 😄
