### ISSUE TITLE
Add more "mentionable" users to autocomplete

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#186]
The mentionable users GraphQL endpoint only gives us the first 100 people, this seems to only be people who belong to the project too. I have some ideas to make user autocomplete feel a little better:

- The author
- Anyone who has commented
- Assignees
- Reviewers
- Anyone @ mentioned in the thread (lowest pri)

Will have to collect usernames as we scan/parse timeline events.

**Comment by Sherlouk** [comment]
Related to #185 but would also be nice if we get the issue/pr's repo owner (if organisation) and give the ability to mention team names!
