### ISSUE TITLE
Keyboard when commenting should dismiss interactively 

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#187]
Version 1.3.0 (1054)
Device: iPhone 7 Plus (iOS 10.3.2) 

This was the case, but with the new commenting it seems like the keyboard can't be dismissed.

**Comment by rnystrom** [comment]
Good call, I tried using the default UIScrollView method but that doesn't seem to work w/ the Slack TV. There is panning support in the lib, but will have to play around to figure out how it works.

**Comment by rnystrom** [comment]
This is working now
