### ISSUE TITLE
Show all open issues related to Repositories I want to watch

### ISSUE THREAD

**Issue by shaps80** [rnystrom/GitHawk#191]
Currently the app only surfaces read/unread activity via GitHub's Activity API.

Often a user will have many issues still open across many repositories they are contributing to, but unless some _new_ activity occurs, these will not be surfaced.

I'm opening this issue for further discussion in terms of how this might work from both a UX and Implementation point of view.

**Comment by rnystrom** [comment]
Keeping it at 1 label for easier filtering

**Comment by Sherlouk** [comment]
Is this resolved by the introduction of Bookmarks?
