### ISSUE TITLE
Add milestone summary to issue/PR

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#208]
Simple milestone unit when issue/PR has one

- Show name
- progress bar with numbers (e.g. "5/11")
- tap to open milestone (safari for now)

GQL doesn't return milestone numbers. Idk if there's a way to link without the number (name?).

**Comment by Sherlouk** [comment]
Had considered adding this to repo view earlier and recall seeing something for milestone numbers - will av to double check

**Comment by Sherlouk** [comment]
```
milestone {
      url
      number
      title
}
```

Returns
```json
"milestone": {
      "url": "https://github.com/rnystrom/Freetime/milestone/1",
      "number": 1,
      "title": "1.0.0"
}
```

Should be all the information we need?

**Comment by rnystrom** [comment]
Ah nice, ya the number missing was b/c I'm using [MilestoneItem](https://developer.github.com/v4/reference/object/milestonedevent/) for the timeline. Glad to know the number is available here!

**Comment by rnystrom** [comment]
Bummer ya, doesn't look like there is a way to get Issues/PRs for a given milestone. That's weird. I guess we can just add the milestone along w/ pushing the milestone web page on tap for now.

**Comment by rnystrom** [comment]
[Filed](https://platform.github.community/t/milestone-timeline-events-available-on-pr-but-no-root-milestone-object/2768)

**Comment by rnystrom** [comment]
Milestone info added!!

https://platform.github.community/t/milestone-timeline-events-available-on-pr-but-no-root-milestone-object/2768/3

**Comment by rnystrom** [comment]
Close as possible, though I'd still love to be able to query open/total numbers, just having the info is good enough for now.
