### ISSUE TITLE
Add option to star on GitHub

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#210]
Put in settings after table refactor

**Comment by rizwankce** [comment]
What do you have in mind for this? Open repo URL in Safari and ask the user to start it or Use GitHub [starring](https://developer.github.com/v3/activity/starring/#star-a-repository) API?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
I'd personally much prefer to use the API

**Comment by Sherlouk** [comment]
https://developer.github.com/v4/reference/mutation/addstar/ 

There's also the V4 API we could use -- probably simpler to use V3 though and since we don't have any preference 🤷‍♂️

**Comment by rizwankce** [comment]
Need some help on brainstorming for the UI part. Quickly created something in the storyboard.
![screen shot 2017-09-18 at 9 06 02 pm](https://user-images.githubusercontent.com/12063704/30550689-d7611fb2-9cb5-11e7-99b8-bac474ccc36a.png)

- Cell under "View Source Code" to star on GitHub
- Cell has "Star on Github" and total stars 
- On Click, Call v3 API to add star
- If the user already added star ??

**Comment by Sherlouk** [comment]
Like the idea of having the total stars, maybe the button text just changes to "Unstar" or something to give the user the ability to revert the action?

**Comment by rizwankce** [comment]
"Unstar" option would be great! Let me knock this down 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Unrelated, but I feel like we should really explain the options in Settings better. "Read on Open"? "Badge Unread"? I feel these are all but obvious.

**Comment by rnystrom** [comment]
@BasThomas suggestions?

**Comment by rnystrom** [comment]
@rizwankce @Sherlouk what about making the cell dynamic in that if you've starred the repo then it disappears? That'd obvi make this page much more complicated, but would serve its purpose.

Also, IMO this is pretty low pri vs other stuff (maybe we should have priority labels? or really start using the projects tool).

**Comment by rizwankce** [comment]
@rnystrom Agree with the priority. I just filtered issues by Bugs/Feature and started looking into it. Definitely, I can check Projects and take some high pri issues.
