### ISSUE TITLE
Reconfigure date label constantly

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#218]
Need to get clever about this...

The date propert of the notification view model is an immutable date, obviously it never changes. However the date text we display constantly changes ("a minute ago" becomes "2 minutes ago" when returning >60 seconds later).

This is where something as simple as `reloadData` would be useful. However since this uses IGListKit, that's hella overkill. It would work, but can we do better?

Some ideas:

- section controllers set a timeout to reconfigure the cells 
- bake the display time into the model so railing fails when display text changes
- call `reloadData' on the collection view. Violates what we promote with IGLK but it shouldn't break anything

Should update on every view appear and app foreground, I think.

**Comment by Sherlouk** [comment]
My personal preference is number 2
