### ISSUE TITLE
Scrolling to end of issue sometimes fails. 

### ISSUE THREAD

**Issue by shaps80** [rnystrom/GitHawk#246]
When the issue has a large number of comments the scrolling code is executed before the list has fully sized (I think) causing the scroll offset to be fairly arbitrary. 

The issue below seeems to be reproducible. 

https://github.com/Quick/Quick/issues/729

Version 1.6.0 (1412)
Device: iPhone 7 Plus (iOS 11.0)

**Comment by BasThomas** [comment]
Yeah, have been seeing this as well.

**Comment by rnystrom** [comment]
I'm almost certain this is from comments w/ HTML, since those cells are sized as the cell appears, when you scroll past them that's when their size is configured. However the destination is already set, so the resize messes up the position. Will think on this one.

**Comment by shaps80** [comment]
Right makes sense.

**Comment by rnystrom** [comment]
Not actioning atm
