### ISSUE TITLE
Vanishing characters in code blocks

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#253]
GitHub
![img_1304](https://user-images.githubusercontent.com/4190298/29490232-032505c4-8536-11e7-8909-e96813976a22.PNG)
App
![img_1305](https://user-images.githubusercontent.com/4190298/29490234-034e37b4-8536-11e7-89f6-30ce69180334.PNG)
![img_1306](https://user-images.githubusercontent.com/4190298/29490233-034d6abe-8536-11e7-94f7-30420e045257.PNG)

**Comment by BasThomas** [comment]
(See: missing `&&` and `>` in `->`)

**Comment by rnystrom** [comment]
Ah nice! Yup missing escaped HTML characters. I know exactly where this is. Good find!!
