### ISSUE TITLE
Scroll inset issue

### ISSUE THREAD

**Issue by dkhamsing** [rnystrom/GitHawk#256]
For the PR and Files screens, content appears under the nav bar :(

I am running iOS 9 beta 

Video https://twitter.com/dkhamsing/status/900021256577097728

**Comment by rnystrom** [comment]
iOS 9? You mean 11? 😅

Pretty sure this is a duplicate of what @Sherlouk has already reported

**Comment by dkhamsing** [comment]
Dupe of #18
