### ISSUE TITLE
Use "Twitter" keyboard style

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#257]
Any reason we're not using this right now? Especially once #219 lands, it would make sense to me if we prefer the `@` and `#` shortcuts over the `return` (which with the `.twitter` keyboard is still accessible in were the numbers are).

AKA: want to wait for #219, do it now, or is there a reason you didn't do this @rnystrom?

**Comment by rnystrom** [comment]
I find myself using the return pretty frequently, but let's give this a try instead.

**Comment by tjvr** [comment]
Please can we have the return key back? I like using multiple paragraphs in my comments :-)

[I only just found the return key on the second keyboard page—hadn't even realised that was there!]

**Comment by BasThomas** [comment]
Yeah - you can use return on the numbers+more keyboard.
