### ISSUE TITLE
Smarter `@` autocomplete

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#258]
Not sure what request is done when typing `@`, but it seems like the retrieved list doesn't really know the context of the issue. Maybe we can bubble up users that are active in the issue and/or were mentioned?

**Comment by rnystrom** [comment]
no network request, it uses the mentionable users API for a repo, returned in the GQL issue/PR response, along w/ anyone who has commented in the thread. So this is already done, but looks like you're asking for ppl in the thread to be ranked higher. I think I can just swap arrays to make this happen.
