### ISSUE TITLE
App rating prompt will never show system

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#261]
The system prompt will only show up after the first [7 days](https://github.com/rnystrom/GitHawk/blob/master/Classes/Systems/Rating/RatingController.swift#L94). After that, the in-feed prompt has a much faster [cooldown](https://github.com/rnystrom/GitHawk/blob/master/Classes/Systems/Rating/RatingController.swift#L108-L109). However, they both share the same [stored date](https://github.com/rnystrom/GitHawk/blob/master/Classes/Systems/Rating/RatingController.swift#L53). So by that logic, the in-feed will always be exposed every 1.5 months. The native one wont ever have a chance to be displayed. I need to refactor this to use separate dates.

**Comment by kimdv** [comment]
@rnystrom are you aware of the new in-app rating guidelines on iOS11? 

https://www.macrumors.com/2017/06/09/ios-11-in-app-ratings/

**Comment by rnystrom** [comment]
Yup we had a bunch of discussions on Twitter. I don't see any issue having an in-feed dialog in addition to the prompt apple has.

**Comment by rnystrom** [comment]
Lowered system prompt min time so it appears first.
