### ISSUE TITLE
Add rage shake to report bugs

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#264]
Version 1.10.0 (1554)
Device: iPhone 7 Plus (iOS 10.3.3)

**Comment by BasThomas** [comment]
Really necessary? It has it's own button in Settings already.

**Comment by rnystrom** [comment]
I actually like the idea of not having to leave your current action to report. Plus we could auto upload screenshots maybe?

**Comment by kimdv** [comment]
Is this still in the pipeline? 😄

**Comment by rnystrom** [comment]
Closed it bc it’s probably overkill, but could be neat @kimdv if you want to peel it off 🙏

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
With both native new issue and (hopefully soon) image uploading for bug reports this is now a hella lot more simple!

**Comment by kimdv** [comment]
@rnystrom nothing is to overkill for GitHawk 🚀🚀😎😎😎

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kimdv** [comment]
I'll wait until #475 is done 🚀
