### ISSUE TITLE
Show paste menu control after inserting link

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#266]
Easier workflow to paste whatever's on the clipboard. Should paste between ( and ), e.g.

```
[google.com(PASTE HERE)
```

**Comment by SD10** [comment]
Looks like a duplicate of #1453?

**Comment by BasThomas** [comment]
Looks like it. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
