### ISSUE TITLE
license file missing

### ISSUE THREAD

**Issue by michaelochs** [rnystrom/GitHawk#274]
As this is open source software it would be interesting to know under which license this is open sourced.

**Comment by rnystrom** [comment]
😱 oops that's a pretty glaring oversight

**Comment by michaelochs** [comment]
😅 let’s say it would be very helpful 😆

**Comment by rnystrom** [comment]
So my options from [this blog post](http://blog.lazerwalker.com/cortado/2015/07/05/open-source-licenses.html) are:

### BSD style

- Pro: people can use my code freely
- Con: no legal protection from shipping this exact app

### GPL

- Pro: can't ship my app
- Con: can't use any of my code easily
- Con: App Store constraints

I'm leaning towards BSD with a "please don't be an asshole" clause in the readme (similar to the blog post).

Thoughts?

**Comment by Sherlouk** [comment]
I'd be fine agreeing to the BSD + Plea

**Comment by agisilaos** [comment]
BSD & with your comments seems a good idea to me as well @rnystrom!

**Comment by BasThomas** [comment]
BSD approach is 👍

**Comment by michaelochs** [comment]
I don't really have any legal experience, so my main question would be, can you add an additional part to BSD that forbids people from posting the exact same app? Let's be honest, people will do that if you just ask them kindly :) If you have a license that forbids that though, you can at least get these apps pulled from the App Store if it happens.

**Comment by rnystrom** [comment]
@michaelochs Probably can, but I'd honestly want to pay a lawyer to draft it b/c I have no experience w/ legalese. However I've drawn a line of not putting real money into this project (just time).
