### ISSUE TITLE
Badge unread button only tappable on "settings" label

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#279]
Version 1.10.0 (1634)
Device: iPhone 7 Plus (iOS 10.3.3)

**Comment by BasThomas** [comment]
Also doesn't have cell highlighting at that point.

**Comment by rnystrom** [comment]
Same UX as the settings app, I think this is ok. Sound good @BasThomas?

**Comment by BasThomas** [comment]
Where? Tapping eg. the whole WiFi cell navigates to the WiFi overview

**Comment by rnystrom** [comment]
Airplane mode in settings behaves the same as this. Tapping cell does nothing, have to hit switch.

Maybe I'm confused, what is your expected behavior w/ the unread cell in settings?

**Comment by BasThomas** [comment]
Ah yes - with badges it is as expected.

Scenario: I have disabled notification access, and see the "settings" on the rhs of the cell. 

Expected: tapping anywhere in the cell takes me to settings

Now: tapping anywhere other than "settings" is ignored

**Comment by rnystrom** [comment]
Ah ok, ya I'm not gonna worry about this. It'll make the cell a lot more complicated.

**Comment by BasThomas** [comment]
Fine with that. Will link it in the accessibility issue tho, it's pretty weird atm.
