### ISSUE TITLE
Repo Cleanup

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#280]
Root directory has gotten pretty messy with all the playgrounds, resources and other files being added

Think it's time we gave it a little clean up (moving playgrounds into their own file, etc)?
Maybe also use local Podspecs to reference the extra dependencies (Not a major issue at the moment, but I feel it's better if we have one approach to bringing in dependencies)

Can probably get rid of the culprits.txt now, or regen it and move it?
Move README assets into own file?

**Comment by agisilaos** [comment]
I had the same idea yesterday night, now the root directory, feels a bit overwhelming.

**Comment by rnystrom** [comment]
Go for it!

**Comment by BasThomas** [comment]
Think we can close this, or does anybody think we need more cleanup?

**Comment by Sherlouk** [comment]
Good enough for now!
