### ISSUE TITLE
Search cell truncation

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#284]
![img_0223](https://user-images.githubusercontent.com/15193942/30052045-199d51f6-921c-11e7-95f0-e3d27b6d656b.PNG)

When a repo title is too long, the language name is first to go but the color never goes. If moving the language name still doesn't fit, the center of the main title then goes.

The description is also limited to one line, should maybe let this one wrap?

Also the cell looks a bit weird IMO when it doesn't have a language & no description.

**Comment by rnystrom** [comment]
Ah, yup. I know how to fix this.

**Comment by viktorgardart** [comment]
Same issue on the notification page, the time stamp disappears. 👵

**Comment by rnystrom** [comment]
@viktorgardart yup! Fix should apply there as well. Learned a bit more about AL compression.
