### ISSUE TITLE
Empty states don't take into account tab bar

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#286]
![img_0224](https://user-images.githubusercontent.com/15193942/30052142-7749f9c6-921c-11e7-8d2f-e279a236de19.PNG)

The empty states can be scrolled down now rather than fitting in the left over space. Likely because it's not taking into account the tab bar?

Same applies to the "No Issues" & "No Pull Requests" view

**Comment by rnystrom** [comment]
Nice catch!
