### ISSUE TITLE
Add "Create Issue" button to repo view

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#288]
Once native issue creation is supported, we should replace the "Report a Bug" button in Settings with a native UI.

**Comment by rnystrom** [comment]
YESSSSS

Also we can reuse the same thing for bug reporting

**Comment by Sherlouk** [comment]
@rnystrom Gonna tackle this tomorrow, I’m thinking of just creating a UIScrollView with a couple fields and labels - obviously with a bit of finessing was this across the lines you were thinking?

Don’t wanna go completely down different route

**Comment by rnystrom** [comment]
@Sherlouk I guess all we need is:

- Title `UITextField`
- Body `UITextView`

I'd love to be able to preview the body like we do w/ issue/PR comments. Maybe still have the input accessory controls that `IssueViewController` has?

**Comment by Sherlouk** [comment]
Hmm just trying to find a nice way to lay it all out - Sensing a really complicated view controller with all the fields with validation, previewing, markdown, etc.

**Comment by rnystrom** [comment]
Ya, it could balloon really fast. Maybe check out some open source form things? Also I browse through [dribbble](https://dribbble.com/search?q=iphone+form) a lot when looking for inspiration.

**Comment by Sherlouk** [comment]
Had a gander at the major open-source form providers, but non of them give us markdown/preview functionality. Though Eureka at least does allow "custom cells". 

It may at least provide a nice wrapper around all the validation etc? Not sure if it's worth it

**Comment by rnystrom** [comment]
Ya probably more trouble than its worth. We can start super simple maybe. How about not even using `UIScrollView`. Just have a title `UITextField` at the top and a scrollable `UITextView` beneath it? Size it so it responds to the keyboard. Then put the input controls as the accessory view, and preview button as a nav item bar button item?

**Comment by Sherlouk** [comment]
Got a little something in progress now, will ping some screenshots soon!

**Comment by Sherlouk** [comment]
Slightly bigger issue, there's no GraphQL API for new issues 🙄

**Comment by rnystrom** [comment]
Lol welcome to my hell. GitHawk atm uses a mixture of v3 and v4 APIs to work. In v4 (GQL) you can add comments and reactions, but you can't add labels or close issues... 🤷‍♀️ 

We'll have to use [this API](https://developer.github.com/v3/issues/#create-an-issue) to create issues.

[Here's how I mix v3 and v4 in Issues](https://github.com/rnystrom/GitHawk/blob/master/Classes/Issues/GithubClient%2BIssues.swift#L158-L176).
