### ISSUE TITLE
Email addresses not displayed 

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#289]
Version 1.10.0 (1698)
Device: iPhone 7 Plus (iOS 10.3.3) 
![img_1363](https://user-images.githubusercontent.com/4190298/30079252-e46c6ddc-927f-11e7-9d0b-65a011fc2593.PNG)
![img_1364](https://user-images.githubusercontent.com/4190298/30079253-e4861c5a-927f-11e7-950a-3c745e6f21b6.PNG)

**Comment by rnystrom** [comment]
done
