### ISSUE TITLE
List + url markdown issue

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#295]
![img_1376](https://user-images.githubusercontent.com/4190298/30123009-dbf6c51a-9330-11e7-8c1a-d11f17b57838.PNG)
![img_1377](https://user-images.githubusercontent.com/4190298/30123011-dc796af6-9330-11e7-837f-056de7902328.PNG)

Version 1.10.0 (1698)
Device: iPhone 7 Plus (iOS 10.3.3)

**Comment by Sherlouk** [comment]
Dupe of #175

**Comment by BasThomas** [comment]
Closing in favor of #175 then.
