### ISSUE TITLE
Split view to single does not dismiss tab bar

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#296]
![img_1391](https://user-images.githubusercontent.com/4190298/30240831-1480a9de-9578-11e7-8ed0-8cd29c9e1d59.PNG)
Version 1.10.0 (1698)
Device: iPhone 7 Plus (iOS 10.3.3) 

Steps to reproduce:
1. Go to split view
2. Go back to single (issue) view

Not reproducable the other way around (first issue view, then split and back)

**Comment by rnystrom** [comment]
Oh dang nice!
