### ISSUE TITLE
Show spinner while loading more issues/repos in search

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#298]
Version 1.10.0 (1698)
Device: iPhone 7 Plus (iOS 10.3.3) 
Now, especially on slow networks, there is no indication something is actually happening

**Comment by rnystrom** [comment]
Killed the load more on search

**Comment by BasThomas** [comment]
Why? And some goes for loading next notifications.

**Comment by rnystrom** [comment]
Scrolling beyond 100 search results seems a little silly to me, needless complexity. Agree on notifications tho, lets track that separately.

**Comment by BasThomas** [comment]
Was looking for a specific issue earlier, think it might be nice to search for a specific issue/PR then maybe?

**Comment by rnystrom** [comment]
Ya I'd like to extend with issue and user results (doable via gql) with a scoped seg control on the search bar.
