### ISSUE TITLE
Spinner when loading issue / PR in search might not animate

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#302]
Version 1.10.0 (1770)
Device: iPad Pro (iOS 10.3.3)

**Comment by rnystrom** [comment]
@BasThomas which spinner? Just checked and both the spinner in the middle of the view on search and the PTR spinner on repo are animating. Am I looking at the wrong one?

**Comment by BasThomas** [comment]
Steps to reproduce:

1. Open the search tab
2. Search for eg "IGListKit"
3. Open a repo
4. Open the "issues" or "Pull Requests" segment
5. Tap on of the issues / PRs
6. The spinner will not be animating

**Comment by BasThomas** [comment]
So it's the PTR on the issue/PR itself

**Comment by BasThomas** [comment]
This is really weird - I can't seem to replicate when doing this in eg. Moya
