### ISSUE TITLE
On iPad, there's no cancel button for the search bar in Search

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#305]
Version 1.10.0 (1770)
Device: iPad Pro (iOS 10.3.3)

**Comment by rizwankce** [comment]
It's a system restriction. Check Apple documentations for [setShowsCancelButton(_:animated:)](https://developer.apple.com/documentation/uikit/uisearchbar/1624293-setshowscancelbutton?language=swift) method

> Cancel buttons are not displayed for apps running on iPad, even when you specify true for the showsCancelButton parameter

**Comment by rnystrom** [comment]
Probably ok since you can dismiss the kb. Cool to close @BasThomas?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
No; you can't go back to your list of saved searches now.
![img_0347](https://user-images.githubusercontent.com/4190298/30436767-4c5a0a00-996d-11e7-8588-585693fda639.PNG)

**Comment by rizwankce** [comment]
Agree with @BasThomas 
What are the options we have now to get back saved searches? I'm thinking of listening to keyboard dismiss or clear button.

**Comment by rnystrom** [comment]
Ahh ok. I'll remove the results when the text field is cleared.

**Comment by rizwankce** [comment]
@rnystrom I will send a PR soon for this.
