### ISSUE TITLE
New error alert

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#313]
iPhone X makes the status bar alert outdated. Need to find something new. Any ideas?

**Comment by Sherlouk** [comment]
Same style of alert but pops up as a toast above tab bar or cover nav bar? Or we just address it on a case by case basic and try to give more contextual error messages

**Comment by rnystrom** [comment]
Really like the toast idea. Lets go hunting!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
https://github.com/devxoul/Toaster - Very quick search is showing this, gives appareance overrides so with a couple factory methods we can distinguish between errors/other messages?

**Comment by kimdv** [comment]
I have made a pull request #483 that implements https://github.com/devxoul/Toaster 

I looks nice, maybe some more minor layout changes

**Comment by kimdv** [comment]
As @rnystrom mentioned in #483 we should make our own. 😄

**Comment by rnystrom** [comment]
Started work on this on the flight home. Will have something pretty soon! Came up w/ some fun ideas. Building it in a way so it can be a separate pod. Love @BasThomas's idea.

**Comment by rnystrom** [comment]
Quick preview of what I've got in action:

![wgde5803](https://user-images.githubusercontent.com/739696/31521875-36da2bd4-af79-11e7-9e4b-b99801b50676.gif)

Features:

- Totally configurable (text, font, colors, layout spacing)
- Interactive
  - Rubber-band effect when swiping up
  - Swipe down to dismiss

TODO:

- Auto dismiss after duration
- Delegate when tapping button
- Fix multi-line label
- Tune physics

Learned quite a bit about UIDynamics and Auto Layout w/ this. Been fun!

**Comment by BasThomas** [comment]
Oh wow, looks great! Looking forward to seeing how you implemented it 😀

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
That image was very confusing from the app's point of view, it just looks like an image 😅

Looks great though! (when looked at on GitHub)

**Comment by BasThomas** [comment]
Yeah, the “Quick preview of what I’ve got in action:” definitely helped though. Gif support please! 😁

**Comment by Sherlouk** [comment]
It's weird though because NY photo viewer supports GIFs, so... it should've worked 🤔 Maybe we have to enable it some how

https://github.com/rnystrom/GitHawk/blob/master/Podfile.lock#L17-L22

**Comment by BasThomas** [comment]
Oh that's weird. No idea.

**Comment by Sherlouk** [comment]
@BasThomas Looks like you have to add `ANIMATED_GIF_SUPPORT` as a compiler flag to get it working. If you get five minutes 😉 

https://github.com/NYTimes/NYTPhotoViewer/blob/master/NYTPhotoViewer/NYTScalingImageView.m#L21

**Comment by BasThomas** [comment]
Can we close this now, @rnystrom?

**Comment by BasThomas** [comment]
@Sherlouk that gives me a "no such file or directory" 😂
What am I missing?

<img width="1512" alt="screen shot 2017-10-13 at 10 11 05" src="https://user-images.githubusercontent.com/4190298/31536434-e3520410-affe-11e7-9758-412717830403.png">
<img width="1512" alt="screen shot 2017-10-13 at 10 11 08" src="https://user-images.githubusercontent.com/4190298/31536435-e38965e0-affe-11e7-801f-ba6957e250b9.png">

**Comment by Sherlouk** [comment]
For reasons I don't understand, ya have to prefix them with `-D` so `-DANIMATED_GIF_SUPPORT`

**Comment by BasThomas** [comment]
🤔, it seems like it should already work though: https://github.com/NYTimes/NYTPhotoViewer/blob/14458e8ed8065c3cf31fe0744db9fd4c506e4cfe/NYTPhotoViewer.podspec#L25

**Comment by Sherlouk** [comment]
I don't understand because we don't even specify a subspec: https://github.com/rnystrom/GitHawk/blob/master/Podfile#L12

and it doesn't specify a default subspec 🤔 Maybe reference the `NYTPhotoViewer/AnimatedGifSupport` directly?

**Comment by Sherlouk** [comment]
Also @BasThomas https://bugs.swift.org/browse/SR-909 -- Is this applicable?

**Comment by BasThomas** [comment]
Doesn't look like it. `#if ANIMATED_GIF_SUPPORT` is true.

**Comment by Sherlouk** [comment]
Not too familiar with ObjC, is `#ifdef` handled differently?

Is it getting to https://github.com/NYTimes/NYTPhotoViewer/blob/master/NYTPhotoViewer/NYTScalingImageView.m#L125?

**Comment by BasThomas** [comment]
Let's move this over to #75
