### ISSUE TITLE
Page Switcher

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#319]
Just been taking a look at the app and how we navigate around and we're using the segment view quite a lot to change the page (switch between issues/prs, unread/read notifications etc) and I'm not sure if this is going to (or already) exceeded what it should

In my opinion the picker view is good for switching between states of content, so unread/read is okay and open/closed issues would also be good but I think for something like what page in the repo view to be looking at (Overview, Issues, Pull Requests, Projects, etc) we should look for some other method

At a quick search I found https://github.com/PageMenu/PageMenu and wondered what people thought about it (and the issue as a whole)

**Comment by rnystrom** [comment]
I've been exploring the exact same thing. Seg control probably makes sense on notifications, but a page control on repos would feel better. Same with a profile view.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
#336

**Comment by Sherlouk** [comment]
Marking this as done since we now have the tab bar, this will obviously evolve but the foundation is there
