### ISSUE TITLE
App Preview

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#322]
Put together a rough app preview video to see if having a video impacts downloads at all. Very open to criticism on the video, and would love to discuss effectiveness of having one. All the ASO blogs I've read say you should definitely have one, but lots of "big" apps don't.

Any ideas?

[View on YouTube](https://youtu.be/REWBqrVedvw)

**Comment by Sherlouk** [comment]
Is it just me or is it flashing like a mad man?

Using my face to growth hack any app is a great idea 🤔

**Comment by rnystrom** [comment]
Great idea @Sherlouk! Also yes lol you've become the poster child for this app, hope you don't mind 😇

I might pull the video and add text, really think that'd pull it all together.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Are we good to close this now? Initial preview has been created, further changes can be discussed in growth hacking issues?
