### ISSUE TITLE
Readme Empty view to check state

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#324]
With larger README's and on slower networks when you load a repository you just see the empty view without any real indication it's being loaded

Empty state should only show if we've got a response back?

**Comment by BasThomas** [comment]
You mean that it shows there's no README while loading? Yeah, that should go.

**Comment by rizwankce** [comment]
There is a fraction of a second empty state is being displayed while loading the README file. It's not happening if we load same repo second time onwards. 

Able to reproduce all the time.

Version: 1.10.0(1878) from TF
Device: iPhone 7 plus 

So either we can add a new loading activity indicator or stop refresh control only after loading README (only if available)

**Comment by Sherlouk** [comment]
The fraction of a second didn't bother me, but when loading large README's with a lot of HTML etc it takes noticeably longer (Had it visible for well over a second when loading Alamofire's)

I think the refresh control would be fine for now, just don't stop it until it's ready to show

**Comment by rnystrom** [comment]
I think this is because the readme and issue requests are different, issues finishes first, by the whole list is updated. Ya need a check that readme response hasn't come back.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Note that this will be solved w/ the repo Tabman migration

**Comment by rnystrom** [comment]
No longer a problem now that readme has its own VC
