### ISSUE TITLE
DOES NOT WORK ON iOS 11 PLEASE FIX URGENT ASAP UBN

### ISSUE THREAD

**Issue by jessesquires** [rnystrom/GitHawk#325]
![](http://174.142.61.111/forum/files/trollface.large_426.png)

jk. miss you. 😘

**Comment by BasThomas** [comment]
Classic Jesse

**Comment by rnystrom** [comment]
Lol god dammit, made me panic 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jessesquires** [comment]
lolololololololololololololololo

😗
