### ISSUE TITLE
Type check limit

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#329]
![image](https://user-images.githubusercontent.com/15193942/30637912-ad44ba4e-9df1-11e7-84a1-81639cf07a40.png)

In relation to #114 I tried adding the `-Xfrontend -warn-long-function-bodies=100` flag to see what was causing issues and looks like the `accessibilityLabel` functions that we've added are one of the main culprits. I'm wondering if there's a more efficient way to do this, or just by giving the compiler a bit more information?

cc: @BasThomas

**Comment by BasThomas** [comment]
Yes, I think we should remove all the plusses to concatenate strings at least, and use interpolation instead.
