### ISSUE TITLE
Simplify developer environment setup

### ISSUE THREAD

**Issue by matt-holden** [rnystrom/GitHawk#332]
### Issue
After creating an OAuth application and modifying `Secrets.swift`, I have to constantly make sure I don't accidentally commit that file.

I also had to have the app identifier in the .pbxproj, so I could create a provisioning profile with my developer account and run on my device – so I had to be careful not to commit that as well.   The result is a lot of git stash-ing when hopping between branches, etc.

### Initial thoughts

Regarding `Secrets.swift`, the most simplistic approach would be to include it in the `.gitignore`. If you wanted to truly make an update and commit it upstream, you'd need to manually add your change.

Giving the .pbxproj dynamic values is much more involved -- I've been able to accomplish something like this years ago (I believe it involved preprocessor macros in the Info.plist file, defining constants that can be included in the build configuration).  It was difficult to manage, as I recall.

**Comment by rizwankce** [comment]
As a workaround for OAuth application, I use GitHub's personal access token with notifications, repo and user persmissions

**Comment by Sherlouk** [comment]
Agree with the `Secrets` change, but honestly I find once I'm logged in the client details in that file are not even used and so I rarely even have to populate that file!

**Comment by BasThomas** [comment]
See also https://github.com/rnystrom/GitHawk/pull/197 :)

And @Sherlouk's tip is also pretty useful.
