### ISSUE TITLE
Pop from a full screen (UIWebView) in iPad will make the caller Modal full screen until animation is finished

### ISSUE THREAD

**Issue by mohpor** [rnystrom/GitHawk#333]
iOS 11.0  - didn't test iOS 10, can't say if it is the case there too.

Steps to reproduce:
Put iPad in Landscape, open up Settings. Select any fullscreen item (like Review GitHub Access), try to get back to previous page (Done), the rewind transition will get back to a fullscreen Settings (not a modal) at first and when the transition animation is finished, Settings will become a modal again.

**Comment by BasThomas** [comment]
I believe this is a bug in UIKit, not GitHawk :(
