### ISSUE TITLE
Comments are not fully visible on issues

### ISSUE THREAD

**Issue by rizwankce** [rnystrom/GitHawk#334]
Device: iPhone 7 plus iOS 11
Version : 1.10.0(1878) from TF

![121505968121_ pic_hd](https://user-images.githubusercontent.com/12063704/30678986-c7a4dbae-9eb3-11e7-845f-01242402e139.jpg)

**Comment by rizwankce** [comment]
These are the issues for which I can reproduce this issue from the app.
 - #332 
 - https://github.com/apollographql/apollo-ios/issues/147

**Comment by Sherlouk** [comment]
Sorry I'm confused what the issue is here? You mean how the text stops shortly after the "Initial thoughts" header?

If so, this is completely intentional! Comments have a maximum height, after that you need to tap on it to expand the message to see the full thing

**Comment by rizwankce** [comment]
Closing this issue. Didn't check the default behaviour
