### ISSUE TITLE
Comment bar is broken

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#338]
Version 1.10.0 (1878)
Device: iPhone 7 Plus (iOS 11.0) 
The bar to add bold / italics / whatever doesn’t respond at all

**Comment by rnystrom** [comment]
Shit, pulling 1.10.0 from submission and fixing this. Can't believe I didn't catch this.

**Comment by rizwankce** [comment]
Kalpana 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
