### ISSUE TITLE
Swift 4 Migration

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#339]
😱

**Comment by rnystrom** [comment]
I know I keep putting this off. I'm scared.

**Comment by Sherlouk** [comment]
Recently finished the conversion at work, it wasn't anywhere near as bad as updating from Swift 3 - don't think it'll cause us many issues on this size of codebase

but now that Xcode 9 has been released, don't see why not!

**Comment by BasThomas** [comment]
At least we don’t gave Obj-C... `@objc` x 100

**Comment by BasThomas** [comment]
Wanted to tackle this, but the build at compiling source files - but only when trying to migrate. Any of you have the same issue? I am trying to update only the Freetime + FreeTimeTests targets

**Comment by Sherlouk** [comment]
Haven't tried this project, but other ones have been fine -- I'll give it a run later see how it goes

**Comment by Sherlouk** [comment]
@BasThomas Issue is caused by Apollo, the version we have doesn't have a compatible version for us so we need to update. They have fixed it but I do recall @rnystrom saying something is wrong with the newer versions (Can't recall what)

**Comment by rnystrom** [comment]
Only that newer versions break everything. I'll file a task to upgrade apollo vers.

**Comment by Sherlouk** [comment]
Oh not much then 😂 

Having a quick look now to see what can be done, but it's not looking good 😞

**Comment by rnystrom** [comment]
done 😄
