### ISSUE TITLE
Scroll to bottom not working in issues / PRs in search

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#349]
Version 1.10.0 (1878)
Device: iPhone 7 Plus (iOS 11.0)

**Comment by BasThomas** [comment]
Or is that intended bahavior? Now that I think of it... 🤔

**Comment by rnystrom** [comment]
Intended! Coming from notifications it should auto scroll (should be something new). But coming from repo it should stick to the top.

**Comment by Sherlouk** [comment]
Can we keep track of the last comment users saw using the app? Won’t be 100% accurate but should give a better picture than arbitrarily tossing them to the bottom?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
@Sherlouk ya that should be easy I think. We could also make all data serializable and save the last one to disk.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Curious how that would feel in practice, as the scrolling logic would then be different from web (GH knows which comment it should load / start at).

Also, it might be confusing when using app -> web -> app and then rereading stuff read on web.

**Comment by BasThomas** [comment]
Depending on the issue, I just scroll up until I end up where I wanted to end up.

**Comment by BasThomas** [comment]
On GH, I only scroll up when I need to reread for context.
