### ISSUE TITLE
Duplicated signature

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#353]
Version 1.10.0 (1878)
Device: iPhone 6s Plus (iOS 11.0) 

If I send a comment, but it fails (went into train tunnel) the comment box is populated with the original message and the signature ready to resubmit. This will then add the signature again!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

:trollface:

**Comment by rnystrom** [comment]
Oops, nice find!!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
