### ISSUE TITLE
Internal Settings Page

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#355]
Little bit of talk about this here: https://github.com/rnystrom/GitHawk/pull/354#issuecomment-331295321

We should add a new cell to the "Settings" page which is only visible for builds with the DEBUG/TESTFLIGHT compiler flags (See FlexController.m for similar situation)

This page should contain the rate limit information for the v3 and v4 GitHub endpoints:
v3 https://developer.github.com/v3/rate_limit/
v4 https://developer.github.com/v4/guides/resource-limitations/

This will give us insights into how much we're depleting of our limits which will guide usage for new features and where we can afford to be a bit more lenient and return more values for a better user experience or where we should tone it down!

Maybe we could also dump the current user defaults values?

Open to ideas for other things we could add in here!

(Note we should also now have access to Flex for some other debugging stuffs)

**Comment by BasThomas** [comment]
Can't think of anything to add really (although the UserDefaults is a good one!), but just wanted to say that we can and totes should use that information also when people create an issue for debugging purposes.

**Comment by Sherlouk** [comment]
Super easy to do that with new issue stuff :D

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
User defaults browsing is available in FLEX FYI

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
FLEX is a lot more powerful than I thought 🤔 

Has a lot of cool stuff, pretty much just want rate limit info and I'll be happy 😂 

Shame we can't add our own cells to their controller, because would save us a bit of effort trying to build it into our page

**Comment by Sherlouk** [comment]
One possible solution would be to just chuck it into the system log when we detect the user enters into the explorer menu?

**Comment by Sherlouk** [comment]
Gonna close this as it's super unnecessary now that we have FLEX. You can view the notification rate limit by looking at the response from the network manager.
