### ISSUE TITLE
Build Number Auto-increment

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#356]
Honestly the auto-incrementing build number has always been an annoyance in team projects because every PR immediately has a conflict and while it takes two seconds to fix I'd rather not have it 😂 

Obviously this is complete personal preference but an alternative solution would be to do it based on git:

```shell
#!/bin/sh

# Retrieve git information
commitHash=$(git rev-parse --short HEAD)
commitCount=$(git rev-list HEAD --count)

if [ $CONFIGURATION = "Release" ]
then
    echo "RELEASE BUILD"
    bundleVersion=$commitCount
else
    echo "DEVELOPMENT BUILD"
    bundleVersion=$commitHash
fi

# Update Build Identifier
echo "CFBundleVersion = $bundleVersion"

if [ -f "${BUILT_PRODUCTS_DIR}/GitHawk.appex/Info.plist" ]; then
    /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $bundleVersion" "${BUILT_PRODUCTS_DIR}/GitHawk.appex/Info.plist"
else
    echo "GitHawk not found so bundle update not applied to that plist"
    echo "- ${BUILT_PRODUCTS_DIR}/GitHawk.appex/Info.plist"
fi
```

So this does add another dependency (which we could/should store in the repository) but with this as a runtime script it doesn't directly alter the info.plist, it changes the one in the actual build product ultimately meaning we never see it increment and therefore no conflicts

@rnystrom Happy to close this as a non-issue if you're happy with it as is but thought I'd raise an alternative solution regardless!

**Comment by rnystrom** [comment]
What's the dependency?

**Comment by Sherlouk** [comment]
PlistBuddy is the dependency, used to manipulate the Info.plist after the fact.

Which having just checked we already use, so fun fact no new dependencies. So this can be as complicated or as simple as you make it, as an open-source app it might actually be nice to use the hash as it's publicly available and makes it clear what's included in the production app!

**Comment by rnystrom** [comment]
IMO let's move to hash, I think that's a neat idea. Really ties the whole open source bit together nicely!

**Comment by Sherlouk** [comment]
`commitHash=$(git rev-parse --short HEAD)` returns the 7 character hash which GitHub handles fine

**Comment by rnystrom** [comment]
🚀🚀🚀 lets do it!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Closing as this seems to be done and working now
