### ISSUE TITLE
Move duplicate UIAlertActions to AlertActions enum/struct

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#359]
Let's prevent some duping there.

See https://github.com/rnystrom/GitHawk/blob/cd269665df4521da338b00206c2d27d24406bed7/Classes/Issues/IssuesViewController.swift#L212-L241 & https://github.com/rnystrom/GitHawk/blob/cd269665df4521da338b00206c2d27d24406bed7/Classes/Repository/RepositoryViewController.swift#L87-L112

**Comment by vanyaland** [comment]
Closed in #431
