### ISSUE TITLE
Add badge icon next to tabs in repo view

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#378]
Similar to desktop UI, I think it'd be nice to know how many open issues/prs/projects there are!
Same could go for notifications (how many unread)

**Comment by rnystrom** [comment]
Oh cool, hadn't thought of this. Absolutely!

**Comment by Sherlouk** [comment]
Looks great!, but re-opening to address adding badges to issues/pull requests like desktop 😄

**Comment by rnystrom** [comment]
@Sherlouk lets track that in another issue. Trying to keep each issue focused.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
