### ISSUE TITLE
Navigation bar missing in detail view on iPad

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#388]
![e68b5f05-2538-4940-af4d-ae5c54e63a8f](https://user-images.githubusercontent.com/4190298/30776020-e60a7382-a09e-11e7-9730-bacc23fb7b61.png)

**Comment by BasThomas** [comment]
This happens when pushing a second vc (eg. an issue reference) from another detail view

**Comment by rnystrom** [comment]
Ew! Nice find.
