### ISSUE TITLE
App might crash when using the emoji key on the iPad Pro keyboard

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#390]
Version 1.10.0 (1899)
Device: iPad Pro (iOS 11.0) 
Not been able to reliably reproduce this, but it’s been happening a few times. Kinda hard to reproduce / debug probably. Maybe try a search on Google.

**Comment by rnystrom** [comment]
@BasThomas is this different from #396?

**Comment by BasThomas** [comment]
Maybe; not sure

**Comment by rnystrom** [comment]
Closing b/c its the same crash.
