### ISSUE TITLE
External issues should load natively

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#392]
Version 1.10.0 (1899)
Device: iPad Pro (iOS 11.0) 
Eg the one over at Apollo in https://github.com/rnystrom/GitHawk/issues/367. Is this because we can’t recognize this is an issue yet?

**Comment by Sherlouk** [comment]
Do you mean how tapping the issue number in your original comment opens the issue, but remote ones open in Safari?

If so this is dupe of #146 but also the one explicitly in the example you gave is a full URL which GitHub compresses down into a short link. So we need to do some detection and see if the URL matches a given regex and treat it natively

**Comment by BasThomas** [comment]
Let’s track in #146
