### ISSUE TITLE
Add share option to comments

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#393]
Version 1.10.0 (1899)
Device: iPad Pro (iOS 11.0) 
When we add the “More Options” to comments, we should the ability to share specific comment urls

**Comment by rnystrom** [comment]
Sadly the [IssueComment Object](https://developer.github.com/v4/reference/object/issuecomment/) doesn't include the comment number (linkable id) nor the resource URL :/

**Comment by Sherlouk** [comment]
Whaaaaa 😕 That feels like an oversight if I've ever seen one

**Comment by Sherlouk** [comment]
@rnystrom Okay clutching at straws here but you can get the "ID" which is a base64 encoded string which formats like this:

012:IssueComment331668957
Tada, the number at the end is the Issue Comment ID we can use to link 😂 

Super roundabout but yh...

**Comment by rnystrom** [comment]
@Sherlouk omg! If this is true then you're my hero! The v3 notifications API has the comment # on it, so we could actually scroll to the new comment!!

**Comment by Sherlouk** [comment]
I have a weird obsession of detecting Base64 strings and wanting to decode them to see what they say 😂 

The same weird obsession that means I can read binary code

**Comment by Sherlouk** [comment]
Also I've become your hero twice this week, I'm on a roll 😂

**Comment by rnystrom** [comment]
Amazing

🥇🎖🏅

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Omg, amazing @Sherlouk 😂

**Comment by Sherlouk** [comment]
https://platform.github.community/t/enable-getting-comment-url/3943/2

Look at these jokers doing it the easy way 🙄 No fun! 😂
