### ISSUE TITLE
Cannot close the ... menu

### ISSUE THREAD

**Issue by kimdv** [rnystrom/GitHawk#407]
Version 1.10.0 (1900)
Device: iPhone 7 (iOS 11.0) 

There is no way to dismiss the ... menu. 

Search for GitHawk -> select the repo -> press the ... menu. 

You cannot close it now.

**Comment by Sherlouk** [comment]
Fixed in https://github.com/rnystrom/GitHawk/commit/cd269665df4521da338b00206c2d27d24406bed7

Unfortunately that doesn't appear to be in the version pushed out!

**Comment by rnystrom** [comment]
Closing since this is fixed upstream 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
