### ISSUE TITLE
Add release tagging to fastlane

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#410]
When `fastlane appstore` is run it should increment the build version assuming a 

We should have a new lane which is run like: `fastlane appstore 1.11.0`.

It should ensure there are no uncommitted changes:
[`ensure_git_status_clean`](https://docs.fastlane.tools/actions/ensure_git_status_clean/)

It should ensure we're on master:
[`ensure_git_branch`](https://docs.fastlane.tools/actions/ensure_git_branch/)

It should update the project file to have the specified version:
[`increment_version_number(version_number: "1.11.0")`](https://docs.fastlane.tools/actions/increment_version_number/)

It should build this version of the app:
[`gym(scheme: "Freetime")`](https://docs.fastlane.tools/actions/gym)

It should commit that change:
[`commit_version_bump(message: "Version Bump")`](https://docs.fastlane.tools/actions/commit_version_bump/)

It should create a new version on GitHub:
[`set_github_release`](https://docs.fastlane.tools/actions/set_github_release/)

It should send it to the app store:
[`deliver(skip_screenshots: true)`](https://docs.fastlane.tools/actions/deliver)

I may have missed some steps, so this is open to creative interpretation
https://docs.fastlane.tools/actions/

**Comment by rnystrom** [comment]
What happens if you have to pull a build and resubmit? Also does this mean we can’t bump version numbers for new TF builds?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
If you have to pull a build and resubmit with the same tag, then we could just add a step before `set_github_release` which is to remove any release that exists with the same name first (ensuring the tag is at the correct location)

This is only for the appstore lane, this won't affect test flight builds (they will not have tags, etc) unless obviously that's something you want!

**Comment by rnystrom** [comment]
Just thinking about this latest release, I had to dev-reject 1.10.0, fix w/ a patch and resubmit. That means I'd run `appstore` once, dev reject, then run `appstore` again.

Also the issue w/ TF is that we'd submit 1.10.0, but then new TF builds are still 1.10.0 even tho we're technically now testing 1.11.0 features.

Make sense?

**Comment by Sherlouk** [comment]
Makes complete sense and will work with this workflow - TestFlight will be unchanged at the moment so you can push out what ever version you want when ever but it won't be tagged up. Only app store releases will be tagged!

**Comment by rnystrom** [comment]
not releasing w/ fastlane anymore, using BB
