### ISSUE TITLE
UISwitch colour should match API status green

### ISSUE THREAD

**Issue by dylanslewis** [rnystrom/GitHawk#413]
Version 1.10.0 (1900)
Device: iPhone 7 Plus (iOS 11.0) 

I believe the app’s styling would feel more consistent if the tint colour of the UISwitch matched the API status “Good” green. Happy to submit a PR if you agree

![2692fffc-35c2-4111-8fbe-0064fc9dc22c](https://user-images.githubusercontent.com/8267782/30781367-a9d26c9a-a115-11e7-8220-b5adaf0de7b7.png)

**Comment by rnystrom** [comment]
Lovely detail! Good eye

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dylanslewis** [comment]
Raised PR: https://github.com/rnystrom/GitHawk/pull/421
