### ISSUE TITLE
Image height always 200 irrespective of aspect ratio

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#417]
In apollographql/apollo-ios#152 I added an image which is super small in height, but as we use a fixed height of 200 and the mode is designed to fit the image you basically get a whole bunch of empty space (see the image below)

![image](https://user-images.githubusercontent.com/15193942/30786131-2aee0764-a169-11e7-959e-df4a16b879f0.png)

May be an extension to the work to have proper image placeholders (#361) and to update the cell size once we know more information (such as the aspect ratio) obviously we need a max-height still but in this example it should collapse down!

**Comment by rnystrom** [comment]
Changing b/c this isn't a bug, its on purpose atm 😉 

Def open to fixing tho. Could do something similar to how we handle web views.
