### ISSUE TITLE
iOS 11 should use SFAuthenticationSession for login

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#426]
The changes to `SFSafariViewController` now mean that you are stuck w/ w/e user you logged in as. For instance, my simulator is now stuck logged in as my test user. If I log out, the safari VC is already auth'd to GitHub w/ the test user so it immediately redirects back to the app and logs in. Even if I open Safari.app and log out of everything.

**Comment by BasThomas** [comment]
Logged out, logging back in again the first time no-opped for some reason. Killed app, worked like a charm afterwards!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
