### ISSUE TITLE
Add issue title to navigation

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#428]
Version 1.10.0 (1899)
Device: iPhone 7 Plus (iOS 11.0) 
Especially on long issues where you get scrolled down automatically, it’s hard to get context quickly without the title. Might work nice with the navigation bar changes in iOS 11?

**Comment by rnystrom** [comment]
I purposefully chose not to do this b/c of how long the titles can get.

> Might work nice with the navigation bar changes in iOS 11?

What changes?

**Comment by BasThomas** [comment]
Huh, nevermind on those "changes". Don't know what I was thinking there. Let's close for now 👍

**Comment by BasThomas** [comment]
I just came across what I was referencing - not an iOS 11 thing (but new in Calendar.app I think). What do you think about this?

![image](https://user-images.githubusercontent.com/4190298/31551552-383af8c0-b035-11e7-81ad-ced9658e5878.gif)

**Comment by BasThomas** [comment]
Still cuts off when it gets too long (...), but I think this might be better than nothing.

**Comment by rnystrom** [comment]
@BasThomas is this a native feature on iOS 11?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
I don’t think so. :/

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
