### ISSUE TITLE
PBXCp Error: No such file or directory

### ISSUE THREAD

**Issue by vanyaland** [rnystrom/GitHawk#429]
Hey, @rnystrom !

I think this is the question rather than an issue.

I tried to build and run GitHawk locally, but get error with message `No such file or directory` for below frameworks:
- SlackTextViewController.framework
- MMarkdowm.framework
- SwipeCellKit.framework

```
error: /Users/ivanmagda/Library/Developer/Xcode/DerivedData/Freetime-
cvrrtucuxrxxjcekpeclzfyxyovx/Build/Products/Debug-
iphonesimulator/SlackTextViewController.framework: No such file or directory
```

- Xcode 9.0
- run `npm install`
- run `pod install`

I was able to successfully build and run the project, by deleting this frameworks in the `Embed Frameworks` section of the target.

Is it ok to do the actions above?

Thanks!

**Comment by rnystrom** [comment]
Ya this is a bug atm, I _just_ pushed a fix to master. Pull/rebase and you should be good.
