### ISSUE TITLE
Enforce Swift style and conventions

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#433]
https://github.com/realm/SwiftLint

Bound to get a whole load of warnings on first usage but think it would be worthwhile getting things a bit more readable and consistent!

If we do it, I'd vote for putting the portable binary into the repo like `license-plist` so we don't have issues of users have different versions of swiftlint installed

**Comment by rnystrom** [comment]
As long as it doesn’t get in my way then it’s probably fine 😆

I’m pretty conservative about dependencies and am starting to get a little anxious about all the stuff we’re adding. Just don’t want to get bogged down with scattered deps/tools that don’t actually increase the quality of the delivered app.

Agree this could help other contributors stay consistent tho.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
@rnystrom Completely up to you at the end of the day, it's not going to [improve the app](https://github.com/rnystrom/GitHawk/labels/feature), nor [help prevent bugs](https://github.com/rnystrom/GitHawk/issues/183) but it does help against every contributor having their own standards of how things should be laid out.

Ultimately if you're happy with the state of the repo then we can continue as is and just leave this issue until a point where it's felt necessary

**Comment by rnystrom** [comment]
@Sherlouk what'd win me over is seeing what this looks like in practice. Maybe we start _really_ lightweight, only linting really "obvious" common stuff. Then as things repeatedly come up we can opt into more lints?

**Comment by BasThomas** [comment]
Agree with @rnystrom - it's easier to add rules if we feel the need then adding them all at once (or even removing some at some point). Let's start easy.
