### ISSUE TITLE
Table layout broken

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#438]
![img_5934](https://user-images.githubusercontent.com/739696/30894009-18018a5c-a30f-11e7-9fb1-15d48bdc06e8.PNG)

**Comment by weyert** [comment]
:( `UICollectionView` glitch?

**Comment by rnystrom** [comment]
Looks more like the height of each cell isn’t rounding and the height of the containing cell is.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
