### ISSUE TITLE
Navigating to commit message looks strange

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#442]
![image](https://user-images.githubusercontent.com/15193942/30912517-c128baea-a384-11e7-9688-99557949daa2.png)

See screenshot, this is going from a notification to a commit message

**Comment by rnystrom** [comment]
Bc of the double nav bar right? Ya this looks weird.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Yea the double nav, and tbh also the double tab bar at bottom looks a bit weird

**Comment by rnystrom** [comment]
Lol ya it does. It’s probably pushing a VC or something instead of presenting. Should be an easy fix.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Wait weird, this code is all the same (pushing profile, etc)

https://github.com/rnystrom/GitHawk/blob/master/Classes/View%20Controllers/UIViewController%2BSafari.swift#L23-L26

So why do commits behave differently??

**Comment by BasThomas** [comment]
wut, that's weird

**Comment by BasThomas** [comment]
Do we actually use that method? Maybe it's duplicated code?

**Comment by BasThomas** [comment]
You closed a previous issue about this [here](https://github.com/rnystrom/GitHawk/issues/124#event-1262109697); any idea what you changed?

**Comment by rnystrom** [comment]
@BasThomas nothing, that issue was about the title missing right? I think that’s from the `SFSafariViewController` handling of the page title. The double nav/tab didn’t exist then.

Also ya that’s the method that gets called.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
