### ISSUE TITLE
Disappearing reaction button when device rotates

### ISSUE THREAD

**Issue by SD10** [rnystrom/GitHawk#457]
Hey everyone @ **GitHawk**,
Great work on this!! I just started using it today.

I noticed if the emoji reaction bar is visible while the device experiences a rotation it causes the add reaction button to disappear.

### Steps to reproduce
1. Navigate to a comment
2. Click on the add reaction/emoji button to display the emoji menu
3. While the menu is open, rotate the device (Any direction, into landscape or portrait)
4. Rotate the device back to the original orientation

### Environment
Device: iPhone 7
iOS Version: iOS 10.3
GitHawk Version: 1.10

### Extra
This only affects one comment at a time. Therefore, you can toggle which comment experiences the bug by reproducing the steps on another comment.

### Screenshot of Issue
![img_0336](https://user-images.githubusercontent.com/7445580/30951637-b81c1842-a3e9-11e7-88d7-0bb549d603b2.PNG)

**Comment by BasThomas** [comment]
I think this might be a UIMenu default behavior, and we should respawn it after rotating. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Tbh this is such a benign behavior that I think the fix has a higher risk of breaking or annoying maintenance cost than I think is worth it.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
Sorry, I didn't mean to report such a nit bug. I thought it was better to report than to say nothing, but its really not affecting my app experience.

**Comment by rnystrom** [comment]
@SD10 np! All bugs welcome

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Yep! Definitely prefer to submitting any issues you find, never hurts!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
