### ISSUE TITLE
List item count incorrect

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#458]
See #456

In my comment in 456 on GitHawk the numbers go 1. 1. On the website they go 1. 2. (As they should)

🤔

? 1. test
2. test
3. test

edit// looks like it's when a list starts without the number being right at the beginning of the line

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.11.0 (1942)
Device: iPhone 6s Plus (iOS 11.0)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
I'm gonna close this b/c tbh that formatting _shouldn't_ work. The `1.` is part of the paragraph. I don't think that's MD spec lol.

**Comment by Sherlouk** [comment]
Cool all good, was just confusing switching between desktop and mobile and seeing different!

**Comment by BasThomas** [comment]
Yeah, it's a little weird - if you have a list that starts with 2., markdown converts it to 1. anyway. But as @rnystrom - that's markdown for you. GitHub probably wasn't happy with it and changed that.

3. test
6. test
