### ISSUE TITLE
App icon badge count not updated

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#460]
Seems to always be zero?

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.11.0 (1942)
Device: iPhone 7 Plus (iOS 11.0.1)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
Hmm this def isn’t the case for me. You have the permission enabled right? Are you on the latest TF? The tab should also be badges. If they both aren’t then something might be off (but it’s working for me right now)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
> Are you on the latest TF?

If you click the bug report dump it tells you the version 😉

**Comment by BasThomas** [comment]
Oooops. Had it disabled. Then enabled it in Settings - but that doesn't enable it in the app (the `UISwitch` will still be off).

Needs a refresh of the list after that to be updated though - we might want to force update (if possible) when the user switches the switch.
