### ISSUE TITLE
Comment ... not centered vertically

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#461]
<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.11.0 (938)
Device: iPhone 7 Plus (iOS 11.0.1)
TestFlight: false
</pre>
</details>

**Comment by rizwankce** [comment]
Guess comments bullet icon centered correctly but comment text cell top inset is 0.

**Comment by rnystrom** [comment]
Aha, that's right, I added some whitespace padding to make self-comment background work. This makes sense. Easy fix.
