### ISSUE TITLE
Comment cell bigger then necessary

### ISSUE THREAD

**Issue by weyert** [rnystrom/GitHawk#462]
If you go to the ticket Proper Implementation in IGListKit my comment looks much bigger then necessary.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.11.0 (1942)
Device: iPhone 6s (iOS 10.3.3)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
@weyert screenshot? Is this a design critique or bug? It looks fine to me. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
![img_0235](https://user-images.githubusercontent.com/15193942/30971648-6b65ba7c-a460-11e7-9343-22cb08f00c54.PNG)

@rnystrom This definitely doesn't look right, assuming it's the same issue

**Comment by Sherlouk** [comment]
Granted the entire issue has a tonne of HTML and various markdown elements, so wouldn't be surprised if that's acting up - Definitely worth a look

**Comment by BasThomas** [comment]
What's the HTML? Is it related to https://github.com/rnystrom/GitHawk/issues/389?

**Comment by Sherlouk** [comment]
Instagram/IGListKit#949 - Nah it's very different, all proper code and the issue in hand (I checked the source) ends where it should

**Comment by BasThomas** [comment]
Checked out the issue, but can't see the raw Markdown :p

**Comment by Sherlouk** [comment]
You not a collaborator over there to see raw comment? Regardless can just use GitHub explorer to see it! 😄

**Comment by weyert** [comment]
Yes, didn't know how to add an image via GitHawk! But looks like you got a screenshot :)

**Comment by BasThomas** [comment]
We do not support it yet :)

**Comment by rnystrom** [comment]
Ok now I see it

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by weyert** [comment]
Soon 🤗 Sorry, I was travelling to Antwerp :) I don't think the Markdown is anything special!! GitHawk generated it :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Fixed along w/ #495
