### ISSUE TITLE
Comment more options should use blue as a color

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#463]
Looks disabled now.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.11.0 (1942)
Device: iPhone 7 Plus (iOS 11.0.1)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
At first I disagreed, now I can’t unsee. Might change to the hollow ones, just a smaller version. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Actually nvm, tried blue and its way too busy. Gray is good.

**Comment by BasThomas** [comment]
Cool, thanks for checking @rnystrom!
