### ISSUE TITLE
IPad - Navigation bar is missing in issues/PR from notifications

### ISSUE THREAD

**Issue by rizwankce** [rnystrom/GitHawk#465]
Looks like recent changes broke nav bar on iPad

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
TestFlight? Master branch?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rizwankce** [comment]
Master branch from iPad pro. Found the fix
