### ISSUE TITLE
Load page x keeps incrementing even when nothing can be retrieved 

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#47]

**Comment by rnystrom** [comment]
Hmm, will investigate. Def shouldn't increase pages when there is nothing, tho sometimes you can keep loading stuff and its all under "Read" (b/c its filtered when you're on Unread). 

I might need to tweak the design to make this more obvious. Maybe even an alert after 1-2 pages that's like "New stuff is under Read" or w/e.

Or maybe I put a count under read/unread and you can also see that increment? Dunno.

**Comment by Sherlouk** [comment]
Just checked this and on both unread and read, the number is just constantly incrementing!

Also on the unread tab, if there are no new notifications then you have to scroll down a tiny bit to see the pagination button.

IMO: The load page button should only show if it's applicable to the content you're viewing - if there isn't 2 pages of unread notifications then don't show it (but then give me the option to when I toggle over to read ones)

**Comment by rnystrom** [comment]
Tracked down & fixed

**Comment by BasThomas** [comment]
This seems to have resurfaced?

**Comment by rnystrom** [comment]
@BasThomas are you sure it's just not loading stuff that is unread?

**Comment by BasThomas** [comment]
Nope, and disappeares after 3. Really strange.

**Comment by BasThomas** [comment]
Looking in to this it seems like it now only shows the load next (2), then disappears.

`po`ing the link first gives:

```
"<https://api.github.com/notifications?access_token=xxx&all=true&page=2&participating=false&per_page=100>; rel=\"next\", <https://api.github.com/notifications?access_token=xxx&all=true&page=2&participating=false&per_page=100>; rel=\"last\""
```

Then after tapping load page 2:

```
"<https://api.github.com/notifications?access_token=xxx&all=true&page=1&participating=false&per_page=100>; rel=\"first\", <https://api.github.com/notifications?access_token=xxx&all=true&page=1&participating=false&per_page=100>; rel=\"prev\""
```

I almost think this is a GitHub API issue?

**Comment by rnystrom** [comment]
Ya, I've done some digging here and am almost positive its a GH issue. The `Link` header isn't consistent whatsoever.

**Comment by BasThomas** [comment]
Haven't being seeing this lately, could it be that this has been fixed?

**Comment by Sherlouk** [comment]
I think by breaking up the requests this no longer happens!
