### ISSUE TITLE
Ratings logic??

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#472]
I know I’ve mentioned this to Ryan on twitter before and it all looked good - but I’ve had the ratings prompt (in app not system) twice on simulator but never once on my actual device...

☹️ I wanna rate too!

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.11.0 (1942)
Device: iPhone 6s Plus (iOS 11.0)
TestFlight: true
</pre>
</details>

**Comment by BasThomas** [comment]
Never seen on device nor sim. Maybe because switching between App Store / Testflight?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
I’ve not installed App Store version for ages just  stay on TestFlight, equally it’s all stored in user defaults which is persisted so shouldn’t affect it

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
I've seen it on device. Also we're getting good volume of ratings, so it must be working.

Maybe it's disabled on TF? You can use FLEX to check your user defaults too. Just look for [these keys](https://github.com/rnystrom/GitHawk/blob/master/Classes/Systems/Rating/RatingController.swift#L30-L32).

**Comment by Sherlouk** [comment]
https://drive.google.com/open?id=0B8FbxFN4A3N6WnJubDd3WmNyMTA that’s my values - I can guarantee you though I’ve not woken up at 7am in months, not a clue where it’s got that date from 🤔

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Can someone give me a hand here I'm having a mental breakdown trying to work this out

https://github.com/rnystrom/GitHawk/blob/master/Classes/Notifications/NotificationsViewController.swift#L188

This guard is saying you must have **more than** 0 `viewModels` otherwise return an empty array.

https://github.com/rnystrom/GitHawk/blob/master/Classes/Notifications/NotificationsViewController.swift#L197

This if statement is checking that if you have 0 `viewModels` then return the empty key.

How on earth is the second if statement getting called, if the `viewModels` count is 0.

**Comment by rnystrom** [comment]
@Sherlouk those times are probably GMT, just putting `Date()` in there, not localized.

You're missing the `hasError` check.

- If `hasError` and `viewModels` is empty, return an empty array so the [empty view is displayed](https://github.com/rnystrom/GitHawk/blob/master/Classes/Notifications/NotificationsViewController.swift#L234-L243)
- The [emptyKey](https://github.com/rnystrom/GitHawk/blob/master/Classes/Notifications/NotificationsViewController.swift#L198) is used to display the [inbox zero section controller](https://github.com/rnystrom/GitHawk/blob/master/Classes/Notifications/NotificationsViewController.swift#L219-L223). We don't want to display that if there was a networking error.

**Comment by Sherlouk** [comment]
That's not how guard works though is it? Guard is all the values must be true in order to continue.

So it must have no error, and have some viewModels in order to move onto other executions. If there was an error OR viewModels is empty, then return an empty array

**Comment by rnystrom** [comment]
Oh right, ya so the empty feed doesn't show up correctly. Easy fix. Looks like I didn't have a local build on my device so it looks like it was working.

**Comment by Sherlouk** [comment]
Sorry I was looking at how we insert the ratings token into the notifications objects array when I was following the flow and saw that. There was a loose connection 😉

**Comment by rnystrom** [comment]
Created this script to test:

```swift
func test(err: Bool, arr: [Int], run: String) {
	guard err == false || arr.count > 0 else {
		print("\(run) hit guard")
		return
	}
	print("\(run) finished")
}

test(err: false, arr: [1, 2, 3], run: "1")
test(err: false, arr: [], run: "2")
test(err: true, arr: [1, 2, 3], run: "3")
test(err: true, arr: [], run: "4")
```

Output:
```
1 finished
2 finished
3 finished
4 hit guard
```
