### ISSUE TITLE
Test Image Upload

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#474]
So who thinks this’ll work?

![GitHawk Upload](https://i.imgur.com/rgnBZ2b.jpg)

🤞🏻

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.11.0 (950)
Device: Simulator (iOS 11.0)
TestFlight: false
</pre>
</details>

**Comment by Sherlouk** [comment]
@rnystrom @BasThomas 😉 😉

**Comment by rnystrom** [comment]
Sweet!!!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Nice! Compression isn’t too bad, either 👍

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
