### ISSUE TITLE
Big (?) files do not render

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#476]
https://github.com/apple/swift-evolution/pull/751/files

In app:

![2814dcdd-22bc-4b1d-8dbc-5d1e9c8b3fd8](https://user-images.githubusercontent.com/4190298/31041684-d128de5e-a599-11e7-9ae0-f7c6411d08dc.png)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.11.0 (1)
Device: Simulator (iOS 11.0)
TestFlight: false
</pre>
</details>

**Comment by rnystrom** [comment]
Ya this is def a perf limitation, or something. To optimize the text rendering and enable h and v scrolling, it’s all put into one huge bitmap. For huge file changes something gives out (tho doesn’t OOM?).

Probably needs some instrumenting.

We could also switch to `UITextView` but then we lose h scrolling in favor of word wrapping. Maybe that’s a decent compromise?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
If you put a `UITextView` inside a `UIScrollView` with some sizing calculations it's possible to still keep horizontal scrolling. Not sure on the perf of it for large files but on a small scale I tried it ages ago.

**Comment by rnystrom** [comment]
Fixed w/ text view conversion
