### ISSUE TITLE
Thoughts on NotificationsViewController

### ISSUE THREAD

**Issue by vanyaland** [rnystrom/GitHawk#477]
Hey @rnystrom !

What do you think about grouping notifications per project, like GitHub's notification tab? For me this is more convenient rather than all notifications ordered by time.

Maybe add some option to the `SettingsViewController` -  `group` or `all`.

**Comment by BasThomas** [comment]
Think this is a dupe of #61, but definitely a good idea!

**Comment by vanyaland** [comment]
Sorry, I miss #61.

**Comment by rnystrom** [comment]
I originally started out by doing a this, but things got complicated fast as soon as you add paging. Either you have to go and fetch notifications for each repo (multiple, probably wasteful requests) or you get the inbox of everything.

And even the paging we have now is a little confusing (separating read and unread).

I think for now we probably don’t want to fiddle with it too much, for the sake of simplicity.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
