### ISSUE TITLE
Landscape view overlap for Login

### ISSUE THREAD

**Issue by ajfigueroa** [rnystrom/GitHawk#480]
This looks like a constraint issue in LoginSplashViewController.
Note: Only affects iPhone, iPad is fine. 

## Steps to Reproduce
1. Launch app in unauthenticated state or log out
2. Rotate the screen if you're in portrait orientation
3. Observe that the subtitle label overlaps the sign in button.

### iPhone 6S
![simulator screen shot - iphone 6s - 2017-10-01 at 14 24 56](https://user-images.githubusercontent.com/3321592/31057674-e5e74a58-a6b4-11e7-8bdc-492c31d29309.png)

### iPhone 6S+

![simulator screen shot - iphone 6s plus - 2017-10-01 at 14 27 18](https://user-images.githubusercontent.com/3321592/31057676-e869c544-a6b4-11e7-869e-af958e39e0ad.png)

Version 1.10.0 (1900)
Device: iPhone 6s (iOS 10.3.3) 
TestFlight: false

**Comment by ajfigueroa** [comment]
A simple approach I took was to use size classes and approximately halve the constraint values for Landscape.

Let me know what you all think?
![simulator screen shot - iphone 6s - 2017-10-01 at 16 40 58](https://user-images.githubusercontent.com/3321592/31058831-996ad316-a6c8-11e7-8862-0bc85f918f19.png)

**Comment by Sherlouk** [comment]
You're more than welcome to submit a pull-request and I'll take a look at it - probably won't get merged for another week or so though until Ryan get's off his holiday!

The screenshot definitely looks better though!
