### ISSUE TITLE
Xcode taking significant energy/CPU 

### ISSUE THREAD

**Issue by rizwankce** [rnystrom/GitHawk#482]
Does anyone else is having this issue? While running Githawk project (from master) MacBook (late 2017 model) CPU is reaching its maximum and fans are starting blowing. Note that this only happening when testing/debugging Githawk project, other projects are working fine

With the help of Activity monitor app found out that `SourceKitService` is taking 100% CPU. 
![screen shot 2017-10-02 at 1 58 19 pm](https://user-images.githubusercontent.com/12063704/31069613-d4c2eac2-a77a-11e7-94b2-4088dd37c31d.png)

By following [this](https://stackoverflow.com/questions/26151954/sourcekitservice-consumes-cpu-and-grinds-xcode-to-a-halt) StackOverflow answer was able to solve this temporarily. But still wondering Am I the only one who is facing this issue?

Might be related to #440 but not sure

**Comment by Sherlouk** [comment]
I sense this is related to https://github.com/apollographql/apollo-ios/issues/151 - Apollo has major issues when it comes to performance. The update as you say in #440 has definitely helped with this, but by no means completely solved it.

It mainly comes down to the massive API.swift file which Xcode has a meltdown when it tries to compile it.

Hopefully once 440 goes in it'll be a bit more manageable, but we're sort of waiting on Apollo unfortunately!

**Comment by weyert** [comment]
Anyone else have issues with Xcode 9 that it's becomes unresponsive while it's Indexing or Prebuilding? I have to Force Quit en restart Xcode to get going again

**Comment by Sherlouk** [comment]
Not had issues with the GitHawk project, but in my personal project and at work I've had Xcode 9 freak the hell out on multiple occasions. Think it's just an Xcode issue 🙄 Might give the beta a try

**Comment by weyert** [comment]
Hah, don't bother. Happens in the Xcode 9.1 beta too. I am wondering if Apple eats it's own dog food. If so, this would already be fixed 😜

**Comment by rizwankce** [comment]
Closing this issue as its a but on xcode not related to this project. I guess xcode is mining some Coins occasionally 😜

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
