### ISSUE TITLE
Search filter for inbox

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#485]
Easy way to search for stuff. No server search, just filter local stuff.

Filter for:

- Title
- Number
- Owner
- Repo

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.11.0 (1943)
Device: iPhone 7 Plus (iOS 11.0.1)
TestFlight: false
</pre>
</details>

**Comment by weyert** [comment]
Can I pick this one up?

**Comment by rnystrom** [comment]
@weyert sure!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by weyert** [comment]
I am working on this issue at the moment. I was wondering what the best place would be to put the `UISearchBar`? Do we want to search query to be depending on the selected segment or apply to whatever we have selected? 

Currently, thinking of creating a new section controller and add the `UISearchBar` in there and then filter the `viewModels` in the `func objects(for listAdapter: ListAdapter)`-method with the search query.

**Comment by rnystrom** [comment]
Sounds pretty solid to me. I think starting with just filtering the current selected items is fine.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by weyert** [comment]
I have created a first version of the search, now it will filter out items from `viewModels` array when they don't meet the search criteria. If the search query is numeric we search by the issue number.

Some questions, are you happy with the `searchQuery`-property or should it be wrapped into a view model similar `SegmentControlViewModel` which only contains the query?

**Comment by weyert** [comment]
![Image](https://i.imgur.com/bDMhh2n.png)

**Comment by BasThomas** [comment]
What's with the white sim? 😮

**Comment by weyert** [comment]
I like it this way! If you create a `/AppleInternal` directory you get an `Internal`-menu in the simulator where you can enable the color of the bezel. You can even customize the `chrome color`!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Gonna tweak the UI a little so its a bit more consistent, but this looks great
