### ISSUE TITLE
Load issue from cache then network

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#488]
Snappier time to content

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.11.0 (1943)
Device: iPhone 7 Plus (iOS 11.0.1)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment]
Might get tricky with scrolling to latest comment maybe?

**Comment by rnystrom** [comment]
Oof good point @BasThomas! Lets hold on this then.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
