### ISSUE TITLE
Command + Enter to send message

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#489]
<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.11.0 (1942)
Device: iPad Pro (iOS 11.0.2)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
Won’t that prevent newlines?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Oops. Meant command+enter (on physical keyboard). But will add it to the keycommand (#234) issue and close this one. 👍
