### ISSUE TITLE
Cache bug isn’t gone

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#490]
Bg task is fetching 12 new items, load app and says 9...

😭

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.11.0 (1943)
Device: iPhone 7 Plus (iOS 11.0.1)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment]
Noooooooo

**Comment by Sherlouk** [comment]
Just had the app say 6 items, loaded GitHub and 9 items 😢 

It definitely refreshed as well

**Comment by BasThomas** [comment]
Yep, that’s exactly the bug in question. 😐

**Comment by rnystrom** [comment]
Too mysterious, haven't hit in a long time. Going to leave open but remove milestone.

**Comment by BasThomas** [comment]
Haven't had this in a long time either. 🤞
