### ISSUE TITLE
Tap reaction to +1 and the use menu for same emoji lets you react twice

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#492]
API figures this out and negates the second, but our UI +1s twice which is wrong.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.11.0 (1943)
Device: iPhone 7 Plus (iOS 11.0.1)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment]
Uh-oh.

**Comment by BasThomas** [comment]
Should it noop or remove the +1?

**Comment by Sherlouk** [comment]
https://github.com/rnystrom/GitHawk/blob/a904020a1c2c7a2b2d1d233451be60cc418d92d2/Classes/Issues/Comments/Reactions/IssueCommentReactionCell.swift#L102

Could we just not add items to the action array if it already exists in the tray? Keep it as a purely "add a new reaction"?

Out of curiosity what's stopping us from just having all of the reactions visible but with the label at 0 and slightly faded? 🤔 

Additionally the desktop UI just removes the +1 if you already have it selected. Similar problem? Same solution?

**Comment by Sherlouk** [comment]
Maybe better still:

https://github.com/rnystrom/GitHawk/blob/a904020a1c2c7a2b2d1d233451be60cc418d92d2/Classes/Issues/Comments/Reactions/IssueCommentReactionCell.swift#L117-L125

We could return false here if the user has already selected it, this essentially disables the button but keeps it visible?

**Comment by rnystrom** [comment]
All the reactions visible looks super sloppy. Puts more strain on you to find what is the most popular reaction, etc. Im also trying to keep GitHawk’s UI consistent with GitHub so you don’t have to learn new behaviors.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
You can even get up to 1000 reactions atm if you want 😁
