### ISSUE TITLE
Global cache HTML sizes

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#495]
Too many cache misses. Should be a singleton. Cache on html string and width. Maybe we can shorten the string or grab some substr so we aren’t keying with huge strings.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.11.0 (1943)
Device: iPhone 7 Plus (iOS 11.0.1)
TestFlight: false
</pre>
</details>

**Comment by Sherlouk** [comment]
Can we not just use the hash value of the html as the key?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Ya that’ll work! Even `“\(width)\(html.hash)”` would be perfect.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
