### ISSUE TITLE
GitHub introduces GraphQL changelog

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#497]
Just thought I'd share this for those who haven't seen it:

https://developer.github.com/v4/changelog/

Blog post introducing: https://developer.github.com/changes/2017-10-05-introducing-the-graphql-changelog/

Should make it a lot easier for us to keep on top of the changes they're making and identify bug fixes etc 😃 

@rnystrom

**Comment by rnystrom** [comment]
Thank god. But pls fix PR threads 😭

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
