### ISSUE TITLE
Rename Strings to Constants

### ISSUE THREAD

**Issue by viktorgardart** [rnystrom/GitHawk#498]
Either rename `String` to `Constants` and store both links and localized string etc. Or create a new file called `Constants` to store the urls.

See comment: https://github.com/rnystrom/GitHawk/pull/494#discussion_r143076287

**Comment by rnystrom** [comment]
Slightly off topic, @BasThomas what's the hacktoberfest label?

**Comment by viktorgardart** [comment]
@rnystrom: #507 
https://hacktoberfest.digitalocean.com
