### ISSUE TITLE
Animated GIFs not animated

### ISSUE THREAD

**Issue by weyert** [rnystrom/GitHawk#499]
If you have a README which contains a GIF which is animated it's not showing the animation / other frames.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by viktorgardart** [comment]
@weyert Could you provide an example of a repository with a GIF in the README?

**Comment by weyert** [comment]
https://github.com/Ramotion/folding-cell :)

**Comment by Sherlouk** [comment]
Dupe of #75? We could quite easily add support for GIFs using FLAnimatedImage which is part of SDWebImage (which we have).

Just need to update to use the right image views 😄

**Comment by rnystrom** [comment]
Yup dupe
