### ISSUE TITLE
Consider renaming Notifications to Inbox

### ISSUE THREAD

**Issue by weyert** [rnystrom/GitHawk#500]
Would be useful to rename the /directory/ Notifications to Inbox so you can much easier find the relevant code for the Inbox screen?

**Comment by rnystrom** [comment]
Ya, maybe. Has to be done carefully (eg preserve got history). Also super super low pri. Lots of other things could use a rename, like the whole project still being “Freetime” 😜

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
