### ISSUE TITLE
The app does not respect the safe area on iPhone X (landscape)

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#508]
Eg. all lists / issues contents reach to the end of the screen
<img width="964" alt="screen shot 2017-10-09 at 11 56 34" src="https://user-images.githubusercontent.com/4190298/31333038-ec8f812e-ace8-11e7-855b-fafbf8575927.png">

**Comment by rnystrom** [comment]
Adding iPhone X tag. We should probably aim to get these fixed in the 1.12 release (or ASAP).

**Comment by viktorgardart** [comment]
@rnystrom 
#507 
https://hacktoberfest.digitalocean.com

**Comment by BasThomas** [comment]
@rnystrom: I think this would be an IGListKit issue even, right? Example project there is also not respecting the safe area.

**Comment by Sherlouk** [comment]
Not an IGLK issue as it's completely dependent on the cells themselves. We just need to update the constraints to be against the safe area guides rather than the contentView for it to work

**Comment by BasThomas** [comment]
Do we want to extend the cell background to the edges here? If not, it can be closed.
