### ISSUE TITLE
Repo issues/PRs should show label summary (dots) on list view

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#511]
Helps when browsing

**Comment by BasThomas** [comment]
Maybe tricky when we have quite a bit of them. Thought about that case?

**Comment by rnystrom** [comment]
I think its ok if we just show the dots (like we do in Issues w/out expanding them). If there are a ton, I think it's fine to just set a limit.

**Comment by BasThomas** [comment]
![2decf390-5911-442f-9590-f78b47fc0189](https://user-images.githubusercontent.com/4190298/31339888-a2c19fde-ad04-11e7-8b6c-228a34726a74.png)
Something like this?

**Comment by rnystrom** [comment]
lol I love it, yes exactly!

**Comment by joerocca** [comment]
Working on this!

![labeldots](https://user-images.githubusercontent.com/10346184/31793608-b6e667f6-b4ed-11e7-9cb7-bb7a196a8806.gif)

**Comment by rnystrom** [comment]
Woooo awesome!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Looking good!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
