### ISSUE TITLE
Sign Out button lacks destructive coloring

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#515]
@rnystrom Super minor but storyboard says it should be red 🤔 Weird one

(Latest TF build)

**Comment by weyert** [comment]
Ain't this because of `textLabel?.textColor = Styles.Colors.Gray.dark.color` in `StyledTableCell`?

**Comment by tjvr** [comment]
Looks like @rnystrom's done this :-) <https://github.com/rnystrom/GitHawk/pull/516#issuecomment-336583594>
