### ISSUE TITLE
UITextView for viewing code (changes, browsing files)

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#520]
Looking at Working Copy, this looks super clean and would make the implementation **so much** simpler.

![img_6364](https://user-images.githubusercontent.com/739696/31396086-6ed7769c-adb0-11e7-949b-e5f21c4f5721.PNG)

**Comment by Sherlouk** [comment]
Linking to #59 as well because we'd obviously want syntax highlighting on this!

If we do go ahead and use Highlightr, we can take advantage of their real-time highlighting [here](https://github.com/raspu/Highlightr#codeattributedstring). So that you can edit code and have it highlight right there and then!

I do recall (#443) you mentioning wanting something similar with Markdown. Could maybe fork or make our own version as our own module (#512)

**Comment by rnystrom** [comment]
Ya I think Hightlightr is the way to go (its also what WC uses according to their OSS attribution).

**Comment by weyert** [comment]
Interesting. I guess a custom `UITextView` with a `UITextView` and a custom view for drawing the editor gutter?

**Comment by weyert** [comment]
@rnystrom @Sherlouk I have been working on this, it's part of the pull request #537. See an example below.
![Image](https://i.imgur.com/kdY6y2w.png)

I only noticed that it won't draw background to the full line something to look at in the future. Let me know, what you think of it so far :)

**Comment by Sherlouk** [comment]
It's looking amazing! can't wait!

I agree about the full line background, that'd be a huge thing!

Also it would be nice if we could make text-wrap optional? If it's all in a scrollView we should be able to do horizontal and vertical scrolling.

At line 9 in your example it displays part of the patch context  - That's not actually part of the file so shouldn't have it's own line number and needs to be formatted appropriately

A feature request, but fully understand if it's out of scope would be to highlight what's actually different (à la GitHub). So on line 32/33 the background behind attributeView/codeTextView is slightly darker.

Equivalently, as line 32 was replaced with line 33, the line number shouldn't increase

**Comment by weyert** [comment]
Currently, I have added the gutter with line numbers to the `UITextView` which is just counting all lines which are given to the `attributedText`-field. I guess an even more customised `NSLayoutManager` which supports `diff patches`. If I understand text rendering `NSLayoutManager` is not `UITextView` thing as the default implementation is already used in `NSAttributedStringSizing`. 

The background color line issue might be fixable by somehow using paragraphs or maybe check if there is only one background color attribute for a line and then fill up the whole space. 

I think it's one step more towards awesomeness :)

**Comment by Sherlouk** [comment]
Another thing; would also be nice if the title was just the file name, similar to Working Copy (original comment)

**Comment by weyert** [comment]
@Sherlouk  Added via pull request #555 :)

**Comment by weyert** [comment]
@Sherlouk @rnystrom @BasThomas Any of you aware of a class or some code snippet for Swift/Objective-C that parses these diff patch files? I have found the following page describing the format: https://stackoverflow.com/questions/987372/what-is-the-format-of-a-patch-file

**Comment by Sherlouk** [comment]
@weyert I suspect a regex would do this fairly simply, have you a snippet of what the diffHunk is?

**Comment by weyert** [comment]
Yes, I have attached it. I have found a Node.js package [1] which parses it so I could port that really just trying to avoid work 😅 

[1] https://github.com/sergeyt/parse-diff
[ParseDiffPatches.playground.zip](https://github.com/rnystrom/GitHawk/files/1384629/ParseDiffPatches.playground.zip)

**Comment by Sherlouk** [comment]
Genuinely don't think we need a full diff parsing, GitHub trims down the fat, pretty much we just need a simple regex which picks up on this line:

`@@ -22,14 +21,21 @@ final class IssuePatchContentViewController: UIViewController {`

The important bit is the first number from the two separate blocks, are the start line numbers

https://github.com/rnystrom/GitHawk/pull/537/files
^ Look here for comparison sake

`-22,14 +21,21` is 22 on left and 21 on the right (as the file has been changed further up)
Other intricacies are like the + and - mean how many lines are changed etc but we genuinely don't care.

**Comment by weyert** [comment]
The Node.js library is using `^@@\s+\-(\d+),?(\d+)?\s+\+(\d+),?(\d+)?\s@@`

**Comment by weyert** [comment]
@Sherlouk I have it all working also parses out the chunks correctly. Only I am having trouble to size the `UITextView` correctly so I can throw them in a `UIStackView`. Probably have to fix some issues with my `CodeTextView` hack. Next task, would be to fix the line highlighting. Now I am going to take a little break and wait for some feedback from all of you :)

(Image)[https://i.imgur.com/8W1lEEV.png]

**Comment by rnystrom** [comment]
done
