### ISSUE TITLE
Browse files/code in repo

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#521]
Couldn't find an issue for this. Pretty obvious. Want this for next release to even out the paging space on repo view. Already WIP.

**Comment by Sherlouk** [comment]
@rnystrom What's the scope of this card? Are we closing this based on what's already done, or did you want to add support for other things? (Like rendering image/markdown files?)

**Comment by rnystrom** [comment]
I’m gonna close for now and then we can track missing stuff in granular issues.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
