### ISSUE TITLE
New iOS 11 nav bar titles?

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#523]
Would this looks good?

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.11.0 (1997)
Device: iPhone 7 Plus (iOS 11.0.2)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment]
Oh lol. https://github.com/rnystrom/GitHawk/pull/522#discussion_r143846185

Think it would look good, at least for the root vcs!
