### ISSUE TITLE
Gitter / Slack / Discord channel for Githawk

### ISSUE THREAD

**Issue by weyert** [rnystrom/GitHawk#538]
Would it be an idea to create a Gitter/Slack/Discorc channel for Githawk?

**Comment by Sherlouk** [comment]
I'm not saying no to a Slack team, but on a project of this scale what are the benefits over leaving the discussions public and in issues/prs so that if somebody picks up a piece of work they have all the information?

**Comment by rnystrom** [comment]
Ya I’m in favor of keeping comms in one place.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
