### ISSUE TITLE
App crashes when adding a comment

### ISSUE THREAD

**Issue by weyert** [rnystrom/GitHawk#539]
App crashes when adding a comment

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.11.0 (1993)
Device: iPhone 6s (iOS 10.3.3)
TestFlight: true
</pre>
</details>

**Comment by BasThomas** [comment]
Should be fixed in new TF that Ryan said he would send out like 2 days ago 😁

**Comment by BasThomas** [comment]
https://github.com/rnystrom/GitHawk/issues/514

**Comment by rnystrom** [comment]
Lol bit busy at Instagram, planning season. Will send build eventually.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
