### ISSUE TITLE
Reaction detail label incorrect

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#541]
Latest TF version

When 4+ people reacting it should say `name, name, name and x others`, but it seems to just stop after 3 here 🤔 

https://github.com/rnystrom/GitHawk/blob/master/Classes/Issues/Comments/Reactions/IssueCommentReactionCell.swift#L156-L176

![img_0250](https://user-images.githubusercontent.com/15193942/31535043-5dbbc1b8-aff1-11e7-9cc7-7fc62e65ed37.PNG)

**Comment by BasThomas** [comment]
OK, so `users.count` is definitely just 3 there. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
We use `model.count` for the actual label - which is (correctly) 5. Where does the `.users` come from?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Model comes from here: https://github.com/rnystrom/GitHawk/blob/1c38ff4d5c600be43b6a25c77052ca7a58758705/Classes/Issues/IssueViewModels.swift#L26-L46

It gets the first three names fine, don't know why it would suddenly not get the rest

**Comment by Sherlouk** [comment]
Ahh found it

**Comment by Sherlouk** [comment]
Ahh okay found it, so the GQL is limited to only 3 logins (correct) but the logic has been changed to switch on the `users.count` (which caps at 3) rather than `model.count` (which has no cap). Just need to change that 😄

**Comment by BasThomas** [comment]
OK so:

```
(lldb) po group.users.nodes?.count
▿ Optional<Int>
  - some : 3

(lldb) po group.users.totalCount
5
```

**Comment by BasThomas** [comment]
Aha! Why?!?! And how would you fix it then?

**Comment by Sherlouk** [comment]
https://github.com/rnystrom/GitHawk/blob/master/Classes/Issues/Comments/Reactions/IssueCommentReactionCell.swift#L156

Literally just change that line to use `model.count` not `users.count`

**Comment by BasThomas** [comment]
Ah wait, we never show more than 3 usernames. 😛

**Comment by Sherlouk** [comment]
I still feel it should be the 3 latest, not the first 3 but yea - intentional

**Comment by BasThomas** [comment]
OK, so I found another bug, but it's probably not worth fixing.

I removed my thumbs up in said comment, but the hover will still say "BasThomas, viktorgardart, Palleas and 1 other". 🤷‍♂️

**Comment by Sherlouk** [comment]
@BasThomas Raise it separately, should fix! 😄

**Comment by BasThomas** [comment]
Ah, it actually never updates locally. Bit trickier / more overkill when would technically have to do another network request in the scenario above, though.
