### ISSUE TITLE
Cancel networking when cancelling search before the request completes

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#549]
Steps to reproduce:

1. Search something
2. Tap cancel
3. The "Recent searches" are shown
4. The request finishes, and the view is replaced with the results

4 shouldn't happen when you cancelled already

**Comment by rnystrom** [comment]
Ya good call. Searches could also race. Def need to cancel previous.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
