### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#554]
And maybe add Danger as well to make sure we don't forget adding actual changes? :)

**Comment by Sherlouk** [comment]
https://github.com/dblock/danger-changelog

**Comment by rnystrom** [comment]
Eventually, maybe. With the current rate of change this will be more overhead than I can process.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Fair enough. Closing for now. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
