### ISSUE TITLE
Turn off autocomplete when typing username

### ISSUE THREAD

**Issue by bigfish24** [rnystrom/GitHawk#565]
Whenever I use “@“ then click the username iOS autocorrects this and I have to delete and try it again, where the OS then doesn’t do the autocorrect the second time.

Version 1.10.0 (1899)
Device: iPhone 7 Plus (iOS 11.0.3)

**Comment by rnystrom** [comment]
I've seen this before too, should be easy to do I think?

**Comment by bigfish24** [comment]
Yeah it seems like the behavior described here isn't working: https://github.com/slackhq/SlackTextViewController/blob/master/Source/SLKTextViewController.h#L457

**Comment by bigfish24** [comment]
```objc
- (BOOL)shouldDisableTypingSuggestionForAutoCompletion
{
    if (!_registeredPrefixes || _registeredPrefixes.count == 0) {
        return NO;
    }
    
    return YES;
}
```
In the implementation of that method if you are using `registeredPrefixes` then this would disable the behavior, which a simple override and return `YES` should solve. If not then perhaps the controller is broken for iOS 11?

**Comment by bigfish24** [comment]
👏🙏

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
