### ISSUE TITLE
Clear cache option on settings

### ISSUE THREAD

**Issue by rizwankce** [rnystrom/GitHawk#570]
We are saving (tend to save) a lot in caches. So it would be better to have an option to clear cache. Might be beneficial for users with less storage devices.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.11.0 (2023)
Device: iPhone 7 Plus (iOS 11.0.3)
TestFlight: true
</pre>
</details>

**Comment by Sherlouk** [comment]
Considering we avoid the cache for all networking tasks, I think the only thing that's being cached are the images? (via SDWebImage)

**Comment by rizwankce** [comment]
Yes. Anything which is takes some memory With a long time usage. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by weyert** [comment]
We also caching the size of strings in `NSAttributedStringSizing` and the same for webkit views

**Comment by Sherlouk** [comment]
That's all in memory though, not dependent on the storage capabilities of the device - just need to close the app and it'll clean all that.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rizwankce** [comment]
if closing the app cleaning up all web image cache, then no need for this issue. Maybe we can come back when we have more caches.
