### ISSUE TITLE
Layout warning when displaying a pull request

### ISSUE THREAD

**Issue by weyert** [rnystrom/GitHawk#572]
Looks like the constraints set in `IssuesViewController` on line 131 is failing in the iPhone X simulator in Xcode 9 not sure if this is related to the `safeAreaInsets` changes for this device. Potentially related to #509.

```
2017-10-15 18:15:14.342273+0200 Freetime[98887:6899182] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x60400009fbd0 UIView:0x7ff1267653b0.height == 0   (active)>",
    "<NSLayoutConstraint:0x6040002838e0 V:|-(0)-[Freetime.IssueTextActionsView:0x7ff12675e070]   (active, names: '|':UIView:0x7ff1267653b0 )>",
    "<NSLayoutConstraint:0x604000283a20 Freetime.IssueTextActionsView:0x7ff12675e070.height == 30   (active)>",
    "<NSLayoutConstraint:0x604000283a70 V:[Freetime.IssueTextActionsView:0x7ff12675e070]-(4)-|   (active, names: '|':UIView:0x7ff1267653b0 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x604000283a70 V:[Freetime.IssueTextActionsView:0x7ff12675e070]-(4)-|   (active, names: '|':UIView:0x7ff1267653b0 )>
```

**Comment by rnystrom** [comment]
I’ve seen this too. I’m honestly an auto layout noob and not totally sure what to do about it, or if it actually matters?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by weyert** [comment]
I am quite an auto layout noob too but that's why I like `wtfautolayout.com` see attached results. Maybe the issue that the view wants be height=0 while the actions wants to height=30 + 4 pixels bottom spacing?  See below. I am always getting confused by the visual format.

![https://i.imgur.com/toy4NAA.png](https://i.imgur.com/toy4NAA.png)

**Comment by weyert** [comment]
I think you could fix it by changing the prioriteit of onze of the layout constraints

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
