### ISSUE TITLE
Githawk.com button misalignment

### ISSUE THREAD

**Issue by joerocca** [rnystrom/GitHawk#574]
Took a quick look and seems like it may be related to padding.
This is on the Nexus 6P(411 x 731 dp).

![image](https://user-images.githubusercontent.com/10346184/31587668-914196de-b1b3-11e7-9a78-80f70caeb51d.png)

**Comment by rnystrom** [comment]
Dang, might be a browser consistency thing. Been a while since I’ve done web lol.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by joerocca** [comment]
All fixed! Buttons + padding were just greater than width.
