### ISSUE TITLE
Repo menu bar too tall

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#575]
![img_962d37b06d62-1](https://user-images.githubusercontent.com/15193942/31589379-67b9c710-b1f8-11e7-8ae1-8f3cacf16216.jpeg)

Image is scrolled right to the top, notice the large gap.

Also notice the scroll indicator, pretty far down

**Comment by rnystrom** [comment]
Ah this and #576 are from a last-second refactor for `safeBounds` that I trusted too much. That's what I get for deploying before running through stuff locally.
