### ISSUE TITLE
App crashes while selecting a notification

### ISSUE THREAD

**Issue by weyert** [rnystrom/GitHawk#578]
If I try to select a notification by tapping it on the overview screen. The app crashes.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
What do you mean exactly? Can't seem to reproduce. Version info?

**Comment by weyert** [comment]
The latest one from TestFlight 1.11.0 (2075) using iOS 10.3.3 on an IPhone 6s

**Comment by weyert** [comment]
Sweet :)
