### ISSUE TITLE
Search "background" is grey (iPhone X)

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#579]
![simulator screen shot - iphone x - 2017-10-16 at 11 42 33](https://user-images.githubusercontent.com/4190298/31605710-354b3fb0-b267-11e7-9825-d0d970b76489.png)

**Comment by Sherlouk** [comment]
Somethin' funky with this page 🤔

**Comment by weyert** [comment]
Maybe the dark background is also the reason why it's so dark #576?

**Comment by BasThomas** [comment]
Think so
