### ISSUE TITLE
Events with long usernames run off screen

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#58]
Even on a plus-sized device. Haven't tested 320 width phones...

Will become an even bigger issue w/ dynamic type.

**Comment by BasThomas** [comment]
These as well. Not sure if you knew this yet, or if you are referring to this?
![img_1153](https://user-images.githubusercontent.com/4190298/28128438-ffc922ee-672f-11e7-8aa6-03cb6e36ad70.PNG)

**Comment by rnystrom** [comment]
Yup this is an example of one. For an easy fix:

- I could cap the width of the name and either truncate or adjust font size
- Embed in a scroll view

Leaning towards capping width

**Comment by BasThomas** [comment]
Was looking into this - it seems like this has been solved with things like renaming, but the issue still persists here? Not seeing why.

**Comment by rnystrom** [comment]
Good point we can clean up. Also not totally fixed, I just cheated and made everything smaller lol.

**Comment by Sherlouk** [comment]
I think the difference is you can just use an attributed string for things like renaming, it's all pretty much one string but with a bit of bolding in places (easily done)

The label in this string has the background which is pretty difficult to do (but not impossible; I did have a project that achieved the same design) meaning it's hard to let everything wrap nicely

Doesn't mean there isn't minor changes to make it wrap a bit nicer though

**Comment by rnystrom** [comment]
Seems fixed?
