### ISSUE TITLE
"Proper" way to fix iPhone X insetting

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#581]
So I cheated and and pinching in the collection view by the left/right `safeAreaInsets` which results in funky looking views like this:

![simulator screen shot - iphone x - 2017-10-16 at 08 34 00](https://user-images.githubusercontent.com/739696/31612153-cc07c9e8-b24c-11e7-821e-28b628869fd5.png)

Whereas the table view in settings looks clean:

![simulator screen shot - iphone x - 2017-10-16 at 08 34 40](https://user-images.githubusercontent.com/739696/31612170-deb39450-b24c-11e7-812a-fc77210dd58e.png)

Any tips on the best way to handle this?

In writing this up, I wondered if cells have the layout guide available already...

https://github.com/SnapKit/SnapKit/issues/448

I'm going to blow away the `safeBounds` stuff and fix w/ this.

**Comment by Sherlouk** [comment]
I think the issue might be that we don't correctly use the contentView inside of cells, cells themselves do have a safe layout guide that we should be using which gives the effect like on Settings

**Comment by BasThomas** [comment]
See https://developer.apple.com/videos/play/fall2017/201/?time=472

**Comment by rnystrom** [comment]
@Sherlouk can you explain a bit more about what we aren’t doing with the contentView?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
So I think the issue is with SnapKit we're doing:
`make.top.equalTo(Styles.Sizes.rowSpacing)` which looking at there [docs](http://snapkit.io/docs/) doesn't seem to be the right way to do for hierarchy constraints like this

It should be (I think):
`make.top.equalTo(contentView).offset(Styles.Sizes.rowSpacing)`

**Comment by rnystrom** [comment]
@Sherlouk interesting, it probably doesn't make a difference in the end b/c that should translate to a top position of `rowSpacing` relative to the superview, no?

It looks like `UITableView` gets some magic w/ safe insets that `UICollectionView` _does not_ receive. See [insetsContentViewsToSafeArea](https://developer.apple.com/documentation/uikit/uitableview/2921665-insetscontentviewstosafearea?language=objc).

`UICollectionViewFlowLayout` has [sectionInsetReference](https://developer.apple.com/documentation/uikit/uicollectionviewflowlayout/2921645-sectioninsetreference?language=objc), but that insets the entire cell, not just the `contentView`.

An option I see is to add a base `UICollectionViewCell` class that lays out the `contentView` based on the `safeAreaInsets`. That might do the trick more broadly.

**Comment by Sherlouk** [comment]
That could be true, I didn't know if SnapKit was just doing the offset relative to it's root container, but that would make more sense.

Subclass could work!
