### ISSUE TITLE
October Maintainers hangout

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#582]
Calling all collaborators! I'd love to schedule a 30min hangout to talk about ongoing stuff w/ GitHawk, what everyone is working on, and priorities. That way we can meet each other face-to-face and get alignment on priorities!

What days and times work best for everyone?

_Don't feel like you have to attend either, remember this is all for fun!_ 😇

cc @Sherlouk @BasThomas @weyert @rizwankce @shaps80 @gtchance

**Comment by Sherlouk** [comment]
What timezones are people in as well? Brit over here 🌧 

I can do most evenings (after ~5PM) or Sunday afternoon

**Comment by rnystrom** [comment]
EST for me. Wednesdays during the workday or Saturdays+Sundays all day are good.

**Comment by BasThomas** [comment]
GMT+1, after 6pm on weekdays or Sat+Sun are all fine! :)

**Comment by Sherlouk** [comment]
If we're doing Wednesday, ideally 5PM to 11PM (BST) is equal to 12PM to 6PM (EST)

GMT+1 = BST (Same as me) for Bas

**Comment by BasThomas** [comment]
Then it is BST+1 (or GMT+2) for me. Timezones 🤷‍♂️

**Comment by Sherlouk** [comment]
If you're BST+1 then that means you can do from 5PM BST so equal with me 😄 

Is it 3PM where you're at @BasThomas?

**Comment by weyert** [comment]
I am in the same timezones as @Sherlouk and @BasThomas just depends where I am at that time: UK or The Netherlands

**Comment by BasThomas** [comment]
Yep @Sherlouk :)

**Comment by Sherlouk** [comment]
Proposing 5:30pm BST / 12:30pm EST

https://www.worldtimebuddy.com/?qm=1&lid=2643743,5,122&h=2643743&date=2017-10-16&sln=17.5-18.5

How does this work for everyone?

**Comment by rizwankce** [comment]
🇮🇳  GMT+5:30 here. I'm on work from home so anytime (except midnight) works for me.

12:30PM EST / 5:30PM BST / 10:00PM IST (kind of late but works for me 👍 )

**Comment by weyert** [comment]
Hello

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by weyert** [comment]
Ffdfdfd

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
@Sherlouk works for me!

**Comment by Sherlouk** [comment]
@rizwankce If others can, I can push back about another 30 minutes but before that I'll be at work!

**Comment by rizwankce** [comment]
@Sherlouk That would be nice! Since it's 30 mins call I guess i can make it for 5:30PM BST

**Comment by Sherlouk** [comment]
@rnystrom Looks to be a relatively good time for everyone, wanna handle invites given you have all of our TF emails?

**Comment by rnystrom** [comment]
Yup! I’ll set something up.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Pinging @rnystrom - I haven't missed any invitations or whatever, have I?

**Comment by rnystrom** [comment]
Nope! Sending this am.

**Comment by BasThomas** [comment]
Thanks @rnystrom for setting this up and @Sherlouk @rizwankce @weyert for joining! :)
