### ISSUE TITLE
Slack UITextView input accessory needs to respect bottom safe area

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#583]
Need to inspect and locally patch slackhq/SlackTextViewController#619

**Comment by rnystrom** [comment]
Anyone have any interest fixing this? I'd love 1.11 to be iPhone X ready. I can peel it off later this week. @BasThomas @Sherlouk ?

**Comment by BasThomas** [comment]
🤔, patching SlackTextVC does not work as we use the markdown bar. Should fix there probably.

**Comment by rnystrom** [comment]
Ahhh good to know. That might make it easy then, just make [this constraint](https://github.com/rnystrom/GitHawk/blob/master/Classes/Issues/IssuesViewController.swift#L134-L139) respect the bottom safe area layout guide?
