### ISSUE TITLE
Make @rnystrom send PRs

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#585]
I think this will be good for me and the project. It's hitting a stage where I think changes are big and require a bit more scrutiny + planning.

- Review my own stuff
- Be more careful w/ code changes instead of wild-wild-west
- Teaching op to others (lol maybe)

**Comment by BasThomas** [comment]
What do you mean with “teaching op” if I may ask?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Opportunity for me to show PR style, things to watch for, etc. Show ppl the hinges I value so I request hanged from others less often.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by weyert** [comment]
@rnystrom: Sounds like a great idea! :+

**Comment by Sherlouk** [comment]
Also be nice to see WIP stuff! (e.g. the file browser stuff you teased 😉)

**Comment by BasThomas** [comment]
File browser is already in?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by weyert** [comment]
Yes

**Comment by Sherlouk** [comment]
I meant in the time when it wasn't, it all came into master as one big chunk rather than something we could watch!

Sometimes its helpful to see the order in which people tackle issues etc

**Comment by weyert** [comment]
Definitely is interesting to see that! Right, time to head back to line fragment rectangles
