### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#59]
Not sure how to do this yet. Wonder if I can do some fancy find & replace of https://github.com/isagalaev/highlight.js and convert parts of it to Swift. Looks like its really just loads of regex? Might be easy. All I need to do is turn it into an `NSAttributedString`.

**Comment by Sherlouk** [comment]
Just looked and this library may do what you're wanting?
https://github.com/raspu/Highlightr

From a quick nosey at the code it looks to use `JSContext` and evaluates the contents of `highlight.js`'s script and converts that into `NSAttributedString`

Can specify language or emit it for automatic detection, using GitHub markdown you can get the language from that or just auto detect

**Comment by Sherlouk** [comment]
Created a [branch](https://github.com/Sherlouk/Freetime/tree/syntaxhighlightr) with it working in it's simplest form

Genuinely for the amount of features we require from it, we could get away with writing a slim wrapper ourselves considering it's just JavaScript core and injecting the highlight.js files!

Built-in GitHub theme also isn't a 100% likeness (likely changed since the style was created for highlight.js) but wouldn't take long to update!

cc @rnystrom

**Comment by rnystrom** [comment]
Bumping this again. I think we could do some very simple regex to get this working for v1. Can take `highlight.js` patterns and change them to Swift. I actually don't think it'll be all that hard. I was told not to bother w/ parsing or ASTs, just regex.

**Comment by Sherlouk** [comment]
Reminder that my branch is still hanging around with all this working - not against a regex approach but wonder how big that’ll get over time 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Oh ya! I hadn't actually looked at Highlightr before. Again still pretty nervous about taking another dependency, esp one that relies on JSC lol. Have seen plenty of trouble w/ that.

> not against a regex approach but wonder how big that’ll get over time

Probably don't need to go over-the-moon w/ support, just some basics to begin w/. Not planning on making an IDE or anything.

---

Let's give Highlightr a try tho. As long as things seem stable, we can probably ship it.
