### ISSUE TITLE
Buddybuild badge not loading on the GitHawk repository

### ISSUE THREAD

**Issue by weyert** [rnystrom/GitHawk#591]
Buddybuild badge not loading on the GitHawk repository overview screen:

bindViewModel() nil Optional(Error Domain=SDWebImageErrorDomain Code=0 "Downloaded image has 0 pixels" UserInfo={NSLocalizedDescription=Downloaded image has 0 pixels}) SDImageCacheType Optional(https://dashboard.buddybuild.com/api/statusImage?appID=59d904ff8588d60001729c4e&branch=master&build=latest)

**Comment by weyert** [comment]
Oh, looks like this is a SVG document, maybe that's the problem

**Comment by Sherlouk** [comment]
We added a small bit of logic which is if the file name contains SVG then load it using a web view - that URL doesn't actually say it's an svg hence fails

I know we don't like dependencies, but we might wanna explore something like SVGKit to handle it properly, or do a request and check the mime type

**Comment by rnystrom** [comment]
This is tricky b/c the URL doesn't say what type of image it is. Maybe we need to check the URL and if it doesn't have a supported extension, render it as HTML instead?

**Comment by rnystrom** [comment]
BB going away
