### ISSUE TITLE
Search while typing broken (Search tab)

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#596]
Only searches when tapping search

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.11.0 (2092)
Device: iPhone 7 Plus (iOS 11.0.3)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
This actually never worked 😊 didn’t feel like dealing with race conditions and stuff yet. App Store only searches once you hit search, figure I can get away with it for a while.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
But @joerocca says the opposite in #569. Do we want this eventually or is it a non-goal?

**Comment by joerocca** [comment]
I'm only referring to notifications/issues/pr searching in #569.
The repo search only searches when hitting search so the done return key does not apply there :)

**Comment by BasThomas** [comment]
Well, ignore me in that case. 😅
