### ISSUE TITLE
Optimistic State Manager

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#597]
A lot of actions have now got optimistic states, where we assume the network request will be successful and update the UI accordingly and then revert the change if we receive an error

The current solution isn't really scalable and is pretty easy to make mistakes with (Found that out the hard way 😅)

In most cases we only have one case of storage for a change, for example locking/closing. If you close and then open a issue you only see one view added to the timeline (open) because that's all we keep track of. If you refresh the feed, they all appear.

Just wondering if there's a better way to be doing this?

Some considerations:
- When we know it was successful, actually commit the change to the main model?
- The same model might be added multiple times (new comments, open/close, etc)
  - They might pass/fail in a different order than they were triggered
- Scalability for new actions

**Comment by BasThomas** [comment]
> When we know it was successful, actually commit the change to the main model?

This seems like a great start.

**Comment by rnystrom** [comment]
I wonder if we can merge this into a master in-memory storage, similar to this blog post:

http://khanlou.com/2017/10/the-flat-cache/

Apollo has a memory cache w/ signals about changes, but that wont work for us b/c of how we intermingle the V3 (REST) and V4 (GraphQL) GitHub APIs. A great example is comment editing: read w/ GQL, mutate w/ V3... 🤢

If we had a centralized store, we could add mutations to the store, the store emits changes w/ new, immutable models to listeners, and UIs can update.

> When we know it was successful, actually commit the change to the main model?

As long as we can do this in a way that doesn't introduce mutable models. There are already some mutable states in the app that I'm a little on the fence about (`NSAttributedStringSizing` being the biggest). _Some_ mutation is obviously unavoidable, but we def want to minimize.

**Comment by rnystrom** [comment]
Further good reading from that article

http://redux.js.org/docs/recipes/reducers/NormalizingStateShape.html

https://facebook.github.io/relay/docs/thinking-in-graphql.html

**Comment by rnystrom** [comment]
Started tinkering with this. My biggest dilemma is dealing with changes at the list-level.

Lets say the notifications VC listens for changes on `NotificationViewModel`s. When you change one to read = true, we mutate the cache, it sends an event, and the VC updates. Great.

But what about when you reload notification data? That would send an individual update event for every single one. We don’t want to spam with updates. In that case, we’d want to batch.

Maybe we can build update listeners in a way that they are individual or batches?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by weyert** [comment]
I think you could handle it on the VC side but have one simple lister notificationsUpdated which takes an array of `NotificationViewModel`. Guess we could use a enum for this .listChanged, itemChanged(let item) which basically means if nil whole list changed otherwise one item changed. If I remember correctly this how we did it in back in the Delphi days

**Comment by rnystrom** [comment]
Awesome idea

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Also instead of a singleton, I should attach the cache to GithubClient so we can dependency inject it, but also destroy models when switching accounts.

I’m also partly concerned about memory build up from `NSAttributedStringSizing`. Maybe I’ll pull that off of models and make it is own cache? Or move the bitmap cache to its own thing. Idk yet.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
