### ISSUE TITLE
Expanding and collapsing device info

### ISSUE THREAD

**Issue by viktorgardart** [rnystrom/GitHawk#598]
Expanding and collapsing device info doesn’t resize back.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.11.0 (2092)
Device: iPhone 7 Plus (iOS 11.1)
TestFlight: true
</pre>
</details>

**Comment by viktorgardart** [comment]
The “bug report dump”

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Dupe of #371

**Comment by viktorgardart** [comment]
Sorry about that one! Thanks! 👍
