### ISSUE TITLE
Cancel on Edit Comment UI should diff against original

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#599]
If you try to cancel from the edit comment UI, with no changes, it'll say that there are unsaved changes.

This should be changed to compare the new text value against the original comment, to see if there actually is changes!

Ref: #594

**Comment by rnystrom** [comment]
Wanna just move this to the PR since it isn’t merged?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Can do, raised it separately in case you weren't too bothered about it 😄
