### ISSUE TITLE
Hammer GitHawk 1.11.0 on the iPad

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#606]
Our iPad usage is really low (8%) but not-nothing. Also, we should be good app-citizens and work on iPad. That being said, I don't really use mine enough. Would love extra eyeballs & QA on 1.11.0 before I submit/release it this week!

Let's prioritize carefully too. Small nitpicks don't need to be fixed, but def need to fix any major bugs (VC presentation, popovers, split VC, etc).

<img width="513" alt="screen shot 2017-10-18 at 4 05 27 pm" src="https://user-images.githubusercontent.com/739696/31740149-680fa1bc-b41e-11e7-8137-10070254ad93.png">

**Comment by BasThomas** [comment]
Think we're doing pretty good here already, will do some thorough testing 👍

**Comment by Sherlouk** [comment]
I should really buy an iPad 🤔 Think my bank needs to wait for next years though 😅

**Comment by rizwankce** [comment]
We are already doing pretty good. I have been doing my features development with iPad SIM and use TF version on iPad Air 2 👍  
Also is it okay to have a new label for iPad issues?

**Comment by BasThomas** [comment]
Feel free to add a label,  @rizwankce 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rizwankce** [comment]
Access restrictions. 🙁  I don't have "New Label" button in this project

**Comment by BasThomas** [comment]
Ah. I’ve added it.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Closing this for now; looking good!
