### ISSUE TITLE
Make HTML template a Swift 4 String

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#608]
We can do multiline strings like python now, right? [This is gross](https://github.com/rnystrom/GitHawk/blob/master/Classes/Issues/Comments/Html/IssueCommentHtmlCell.swift#L25-L53).

**Comment by viktorgardart** [comment]
Will fix this with #600

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
