### ISSUE TITLE
Support for filtering/grouping of notifications by repository

### ISSUE THREAD

**Issue by indyfromoz** [rnystrom/GitHawk#61]
Freetime currently displays a list of notifications from a user's public repositories (notifications from private repositories are currently not displayed, see #60 for a discussion). These notifications are ordered via their timestamp in chronological order. The list may contain several hundred read/unread notifications. 

It will be great if we could apply a "filter" to select one or more repositories the user is subscribed for notifications and show notifications from only the selected repositories. In addition, notifications can possibly be grouped by repositories 🤔 . This will probably make things complicated as we would want pagination of notifications. 

![image](https://user-images.githubusercontent.com/315443/27887420-0313c960-6224-11e7-997e-2e3d2332e43c.png)

**Comment by rnystrom** [comment]
I actually had this originally but pulled it b/c of paging. It's a great idea tho. I could add a new segment that is like "Repos" that groups them or something.

I can also request notifications per repo.

**Comment by indyfromoz** [comment]
Having a segment for repositories will be awesome! I see two major benefits - 

1. List of repositories user is currently receiving notifications for, along with basic metadata for each repository.
2. A quick menu or something that one can use to show/hide notifications within the "Unread" (perhaps even the "All) segment.

**Comment by rnystrom** [comment]
I think we can use the same design from #1267 and display a dropdown of all your watched repositories. Tapping one pushes a new VC of notifications only for that repo.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
What about doing what GitHub does, sorting per repo and ordering by last updated? Should also be pretty easy to do (and we can make this an option in Settings)

**Comment by rnystrom** [comment]
Thats actually how it worked back in the Freetime days. 

Paging becomes really complicated and confusing. That, or we have to send separate requests for each repo you watch, and that gets gross fast (dealing with errors).

The biggest lesson I’ve learned in building this app is to not try to bend the API. Make the UI reflect how the API works and what it provides. Then the code _and_ UI is stays simple.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
I mean we can just group what we get from the API?

**Comment by rnystrom** [comment]
That’s the paging complexity I was talking about. If we put a single “load more” at the bottom, then on update the different sections get filled in, gets really confusing to use.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
What about not supporting paging when sorting? Do you think that would be too niche? It would work for me, as I frequently visit the site and clean up my notifications 😇
