### ISSUE TITLE
Resign first responder on iPad when dismissing kb (when using an external keyboard)

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#610]
<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.11.0 (2101)
Device: iPhone 7 Plus (iOS 11.0.3)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
Which view? I’m confused how this is a thing. Doesn’t resign happen when you dismiss the kb?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by heshamsalman** [comment]
@BasThomas is this what you're talking about?

**Comment by BasThomas** [comment]
Kind of, @heshamsalman. I’ll try to post a video to explain the issue. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
![image](https://user-images.githubusercontent.com/4190298/31765981-92a4820a-b4c6-11e7-89b6-5f6fbef23986.gif)

**Comment by rnystrom** [comment]
Oh, so maybe we need to add `resignFirstResponder` when the view disappears?

**Comment by BasThomas** [comment]
Yep, that would be a way of fixing it 👍

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
