### ISSUE TITLE
No way to exit description view

### ISSUE THREAD

**Issue by nathantannar4** [rnystrom/GitHawk#617]
Version 1.10.0 (1900)
Device: iPad Pro (iOS 11.1) 

Perhaps this is more of a UI/UX improvement but when you select the “eye” icon to view the styled text that you have input there is no way to go back to editing the message without reselecting the issue from the table view.

**Comment by rnystrom** [comment]
Oh crap! Good find

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rizwankce** [comment]
@nathantannar4 which screen are we talking about? Did you try the new version 1.11.0?
I cannot reproduce this with new version 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nathantannar4** [comment]
Oh yea just updated I see that issue was patched 😊
