### ISSUE TITLE
Recently Viewed repos mixed in with recent searches

### ISSUE THREAD

**Issue by heshamsalman** [rnystrom/GitHawk#619]
Similar to the Facebook screen-cap below:

<img width="446" alt="screen_shot_2017-10-20_at_1_27_17_am" src="https://user-images.githubusercontent.com/3388381/31806457-f739db9c-b535-11e7-8b06-e348ad5ca21f.png">

**Comment by rnystrom** [comment]
Yaaaa good call! I like this

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by heshamsalman** [comment]
![2017-10-21 12_10_17](https://user-images.githubusercontent.com/3388381/31853582-d6909fa6-b658-11e7-8a2b-d10df1fedc55.gif)

Feature-complete right now, but gotta clean up the styling a bit.
