### ISSUE TITLE
Inbox tab redesign

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#620]
Alongside #491, I'm going to update the inbox and remove the segmented control to switch between unread and all. Instead, I'm going to default the list to be **only unread** and add a left nav item for "All" (or maybe "Archived"?). This will:

- Simplify the VC
- Make toggling read/unread states bubbling up to the VC way simpler (e.g. swipe action)
- Make the app icon badge # match exactly what is shown on launch (same network request)
- Simplify the UI (no seg control)

**Comment by rnystrom** [comment]
I think I’m going to try out iOS 11 nav style and put the search bar in the nav item too.

Not totally sure how this will look iOS <11 tho.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
FWIW, you can of course check iOS 10 on the iOS 10 sim.
