### ISSUE TITLE
New screenshots for 1.12.0

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#621]
- iPhone X in screenshots
- Include new inbox redesign #620 
- Include bookmark tab #601

**Comment by Sherlouk** [comment]
@rnystrom Maybe we should use milestones and add a description to them to list the major priorities for them? Be good to see how far away certain features are in your mind! (e.g. Image upload, syntax highlighting etc)

**Comment by rnystrom** [comment]
Ya, I'll spend some time this weekend outlining a roadmap

**Comment by rnystrom** [comment]
I LOVE the screenshots on this [Reddit client](https://itunes.apple.com/app/id979274575).

**Comment by rizwankce** [comment]
We can get inspired some more stuffs from that reddit client. I love that dynamic markdown and kamoji features

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Any feedback?

![shots](https://user-images.githubusercontent.com/739696/32262714-6b3072a2-be93-11e7-93ac-1aac575028fa.png)

**Comment by BasThomas** [comment]
Fast markdown “rending”?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rizwankce** [comment]
Looks so cool with the iPhone X. 👍 

Do we have someplace where we can add some points on iPad friendly, native markdown, image upload?

**Comment by rnystrom** [comment]
@rizwankce love the idea. We'd have to cut one of the screenshots to add a "works on iPhone + iPad" shot. Is there one that you think iPad+iPhone would be more valuable?

Bear in mind, iPad is like 7% of active sessions. Not sure how worth it is.

**Comment by rizwankce** [comment]
7% better than having 0%. IMO. 
No need to cut the screenshots we have already. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Might also be worth updating the screenshots on the website? They haven't even got the tab bar in!

**Comment by rnystrom** [comment]
Lol good call, they are ANCIENT at this point!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
