### ISSUE TITLE
Edit comment needs autocomplete

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#627]
<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1051)
Device: iPhone 7 Plus (iOS 11.0.3)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment]
Also Twitter keyboard 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
This is done in #1326 (not the Twitter keyboard though - do we still want that? Would obviously be super quick)

**Comment by rnystrom** [comment]
Ya lets change it really quick!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
