### ISSUE TITLE
 Buggy Readme scrolling

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#629]
![image](https://user-images.githubusercontent.com/4190298/31853158-6b902772-b684-11e7-8f0f-cc92e3fa3b46.gif)
Not exactly how / what is happening, but text/images are clipping while scrolling. Super weird.

**Comment by rnystrom** [comment]
I see it too. It’s an HTML cell that is changing layout based on the safe area changing. I thought I removed top/bottom from `UICollectionViewCell` content view layout.

https://github.com/rnystrom/GitHawk/blob/master/Classes/Issues/Comments/Html/IssueCommentHtmlCell.swift

https://github.com/rnystrom/GitHawk/blob/master/Classes/Views/UICollectionViewCell%2BSafeAreaContentView.swift

I’ll have to poke around at this.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
