### ISSUE TITLE
Searching from empty state never finishes

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#638]
Some bug with the search changes maybe. On a clear search it doesn’t finish loading and just spins forever. Once you cancel recent results display then everything works fine.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1063)
Device: iPhone 7 Plus (iOS 11.0.3)
TestFlight: false
</pre>
</details>

**Comment by heshamsalman** [comment]
Feels like something intro'd with all the branches coming together. 

👁

**Comment by heshamsalman** [comment]
Was able to trigger this again under slightly different circumstances.
