### ISSUE TITLE
HTML loses styles

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#639]
Probably from the change to selection. Seems I some of the web view stuff isn’t styled anymore. Noticeable on GitHawk bug reports with collapsed `<details>` stuff.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1063)
Device: iPhone 7 Plus (iOS 11.0.3)
TestFlight: false
</pre>
</details>

**Comment by Sherlouk** [comment]
Can you confirm the original bug is fixed? It's no longer Times New Roman!

**Comment by rnystrom** [comment]
Dang close being broken is cramping my style.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
