### ISSUE TITLE
Tapping repo search result doesn’t animate push

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#640]
VC just snaps into place

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1063)
Device: iPhone 7 Plus (iOS 11.0.3)
TestFlight: false
</pre>
</details>

**Comment by joerocca** [comment]
This is somehow related to calling `adapter.performUpdates(animated: false)`. When I set animated to true or I replace it with `adapter.reloadData(completion: nil)` the push is animated correctly. Seems like an IGListKit bug?

**Comment by rnystrom** [comment]
Aha! It’s cause we disable global animations! Great find. Idk if it’s a bug in IGListKit, but we can fix this ourselves.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
@joerocca which call did you change to `false` to get it to start working? Digging atm, but confused what is tripping the animation up.

**Comment by joerocca** [comment]
I actually changed these calls to `true`. Wasn't sure how to fix this, but curious to know if you do!
https://github.com/rnystrom/GitHawk/blob/master/Classes/Search/SearchViewController.swift#L288
https://github.com/rnystrom/GitHawk/blob/master/Classes/Search/SearchViewController.swift#L330

**Comment by rnystrom** [comment]
Aha right, awesome

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
