### ISSUE TITLE
Change “Mark All” to icon + “All”

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#642]
Maybe “✔️ All”?

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1063)
Device: iPhone 7 Plus (iOS 11.0.3)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment]
For the swipe cell? Why would we want to change it?

**Comment by rnystrom** [comment]
Nah the button in nav bar. “Mark All” just looks wordy now.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
I think an emoji would be out of place as well, but we can try!

**Comment by rnystrom** [comment]
Haha ya I meant use an image icon, not the literal check emoji 😄

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
