### ISSUE TITLE
Keyboard handling changes

### ISSUE THREAD

**Issue by Austinate** [rnystrom/GitHawk#653]
Right now details screen on iPad is not handling keyboard when search field is first responder (like on screenshot).
I'm not sure how to fix yet since i'm not that familiar with SLKTextViewController but if anyone can give me an advice on place from which i should start — i can help with this :)

<img width="887" alt="screen shot 2017-10-22 at 20 21 12" src="https://user-images.githubusercontent.com/4790464/31864491-c2f0af18-b766-11e7-863f-700eeec3cc98.png">

**Comment by rnystrom** [comment]
@Austinate you mean when the keyboard displays the scroll view for issues doesn’t adjust? Is that the issue? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Austinate** [comment]
@rnystrom exactly :)
