### ISSUE TITLE
Create UIScrollView category to automatically handle insetting with keyboard

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#655]
Basically put all of this PR's code into an extension so we can do something like

```swift
collectionView.insetOnKeyboard()
```

https://github.com/rnystrom/GitHawk/pull/652

**Comment by Austinate** [comment]
@rnystrom we can also extract Keyboard notifications subscription and management to specific object which will be easy for reuse.

Previously i've used something similar to:
`internal class KeyboardHandler : NSObject {

    internal typealias KeyboardEventCallback = (_ willShow: Bool, _ keyboardFrame: CGRect) -> Void

    internal var enabled: Bool

    internal init(enabled: Bool = default, before: KeyboardEventCallback? = default, animations: KeyboardEventCallback? = default, completion: KeyboardEventCallback? = default)

    internal func keyboardWillShow(_ notification: Notification)

    internal func keyboardWillHide(_ notification: Notification)
}
`
but we can rethink this if needed

**Comment by rnystrom** [comment]
we have this now
