### ISSUE TITLE
Suggestion: use FBSnapshotTestCase

### ISSUE THREAD

**Issue by Austinate** [rnystrom/GitHawk#656]
Hello!
Just wanted to ask what do you think on testing UI with [FBSnapshotTestCase](https://github.com/facebookarchive/ios-snapshot-test-case).
If you think it's fine — i can prepare initial PR with example and we can start to cover everything.
From personal experience — such tests are pretty easy to create and they do test both module initialization + UI states.

Want we need to decide is:
— Devices which we will be testing on.

**Comment by rnystrom** [comment]
I'm down @Austinate! Ironically was just thinking about this today. A _perfect_ first candidate would be this:

https://github.com/rnystrom/GitHawk/blob/master/Classes/Views/AttributedStringView.swift

**Comment by rnystrom** [comment]
added, but commented out atm
