### ISSUE TITLE
Empty state for Bookmarks

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#658]
Needs a friendly UI about adding stuff to bookmarks

**Comment by heshamsalman** [comment]
I imagine this would look pretty identical to `SearchEmptyView` (https://github.com/rnystrom/GitHawk/blob/master/Classes/Search/SearchEmptyView.swift).

Probably be a good time to make that template generic.

**Comment by rnystrom** [comment]
@heshamsalman yes! +1 generic. Let's do it.
