### ISSUE TITLE
Image upload preview background color incorrect

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#664]
Should be consistent w/ the rest of the app. Probably ok to just get rid of the background and borders entirely.

**Comment by Sherlouk** [comment]
I'm not too sure tbh, without it - it would just be an image view hovering in the center. Personally feel it's better to have a small indication of where the bounds are!

**Comment by rnystrom** [comment]
Hmm, maybe a white bg then? The 3 shades of grey (bg, separator, and cell bg) make me uneasy lol

**Comment by Sherlouk** [comment]
Oh I fixed this earlier as well, it's white now 😄
