### ISSUE TITLE
Image upload cancel button doesn't work

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#665]
Hitting the "X" does nothing. Should give an "Are you sure?" style alert before discarding.

**Comment by Sherlouk** [comment]
Huh, at some point I must've accidentally deleted the IBAction connection.

https://github.com/rnystrom/GitHawk/blob/master/Classes/Image%20Upload/ImageUploadTableViewController.swift#L99-L121

All the code is there for this already, with logic for "Are you sure" if you've defined either a title or description. I felt if you haven't defined text, you've not gone too far down the rabbit hole - just gotta reselect the image and you're back to where you were
