### ISSUE TITLE
Search in sim is triggering debug menu often

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#675]
Can't even search atm, pretty annoying.

**Comment by rnystrom** [comment]
Debug menu == FLEX?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Yep!

**Comment by BasThomas** [comment]
![simulator screen shot - iphone x - 2017-10-22 at 21 57 10](https://user-images.githubusercontent.com/4190298/31865744-0963f3bc-b774-11e7-9307-74772f21cbd0.png)
![simulator screen shot - iphone x - 2017-10-22 at 21 57 13](https://user-images.githubusercontent.com/4190298/31865745-097a8096-b774-11e7-8981-3a8aea64adec.png)
See the offset cursor. Typing doesn't end up in search, often triggering FLEX.

**Comment by rnystrom** [comment]
If you disable this option, should go away. Started happening to me too.

<img width="621" alt="screen shot 2017-10-28 at 10 57 58 pm" src="https://user-images.githubusercontent.com/739696/32140313-874d7398-bc33-11e7-9c3b-4f0b519a785a.png">
