### ISSUE TITLE
'Local Pods' question

### ISSUE THREAD

**Issue by Austinate** [rnystrom/GitHawk#679]
@rnystrom, am i right that 'Local Pods' are somehow modified copies of libraries?
If so i think that in long-term perspective this 'll bring too much pain since it'll be hard to keep them up-to-date and make additional changes.

I suggest flow where:
— We try to isolate and get shared knowledge of which modifications were made to those libs
— We create fork per library and try to merge our needed change to upstream if possible (if not — just keeping our forks up-to-date)

**Comment by rnystrom** [comment]
re: changes, those are easy to find via the history:

https://github.com/rnystrom/GitHawk/commits/master/Local%20Pods/SlackTextViewController

re: fork, I'm ok with this but also don't want to be the one to do it 😆 I'm more concerned about keeping this project moving w/out getting distracted. If you want to manage it, you've got my support!

Some notes:

- SlackTextViewController is basically dead
- My changes to SwipeCellKit are basically copy/pasting and replacing `UITableViewCell` with `UICollectionViewCell`. I tried finding an easy change to contribute back, but the lib is pretty coupled to UITVC, and I didn't want to spend weeks just for this.
- My changes to MMMarkdown break its behavior (some things commented out, replaced) but most updates would be great upstream (e.g. Swift interop). Lib is hella old and has no CocoaPods.

Maybe a better idea is to fork them to the @githawkapp org and maintain them there?

**Comment by BasThomas** [comment]
+1 on moving forks to @GithawkApp if we take that route 👍

**Comment by Austinate** [comment]
not sure who should get an ownership for forks. Maybe there is a need to setup Organization for GitHawk?

**Comment by rnystrom** [comment]
@Austinate see @githawkapp 😉

**Comment by Austinate** [comment]
@rnystrom ah, silly me! 🙃

**Comment by Austinate** [comment]
so i'm in for switching to forks and can't take this. Won't be easy, but better to make it now than later

**Comment by rnystrom** [comment]
Ya, I'm down w/ this

**Comment by Austinate** [comment]
awesome, i'll start playing around with forks while someone will manage Organization access and forks on it's side
