### ISSUE TITLE
Namespace bookmarks per account

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#701]
Right now bookmarks are global. These need to be per account otherwise is kind of confusing bc there is no indication who you are commenting as.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1079)
Device: iPhone 7 Plus (iOS 11.0.3)
TestFlight: false
</pre>
</details>

**Comment by rizwankce** [comment]
I created #695 for the same
