### ISSUE TITLE
Searched bookmark persisted during search after removing all

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#705]
Steps to repro:

- Add bookmark (eg. Moya/Moya)
- Search in Bookmarks (for something matching that bookmark, in this case eg. "M")
- Clear all bookmarks

Expected: bookmarks are removed, also from the filter
Actual: bookmark stays until dismissing search

(Latest TF, v1.12.0 (1079)), iPhone 7 Plus

**Comment by rizwankce** [comment]
Fixed with #720
