### ISSUE TITLE
Refactor shortcut VC indices

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#708]
This is way too brittle and will be super easy for someone to break.

https://github.com/rnystrom/GitHawk/blob/980fba6cc03cbfef39fb16fb8956e41b5d58807c/Classes/Systems/ShortcutHandler.swift#L13

Need another way to map VCs to tabs that will be caught by the compiler.

**Comment by BasThomas** [comment]
Not sure if we can do that much here. Initial thought: a dict w/ index+vc. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rizwankce** [comment]
Kickstarter has a good way of handling this shortcut and deep linking with an `enum`. This [episode 49](https://talk.objc.io/episodes/S01E49-deep-linking-at-kickstarter) from objc.io talks about it.

- A route enum with entry points
```swift
enum Route {
    case modal
    case tab(TabBarViewController.Tab)
}
``` 
 - Initialiser for deeplinking or shortcut urls

``` swift
    init?(url: URL) {
        switch url.absoluteString {
        case "\(scheme)://tab1": self = .tab(.tab1)
        case "\(scheme)://tab2": self = .tab(.tab2)
        case "\(scheme)://modal": self = .modal
        default: return nil
        }
    }
    init?(shortcutItem: UIApplicationShortcutItem) {
        switch shortcutItem.type {
        case "io.objc.deeplinking.tab1": self = .tab(.tab1)
        case "io.objc.deeplinking.tab2": self = .tab(.tab2)
        case "io.objc.deeplinking.modal": self = .modal
        default: return nil
        }
    }
```

checkout Kickstarter deep-linking enum cases [here](https://github.com/kickstarter/ios-oss/blob/996ba3d8990c85ac9b47dc15e6362a23af49ed69/Library/Navigation.swift)
