### ISSUE TITLE
Unify swipe to delete

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#709]
Bookmarks is different from recent searches

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by heshamsalman** [comment]
I’ll pick this up later tonight or tomorrow. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Ya, should be consistent. SwipeCellKit yo the rescue.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by heshamsalman** [comment]
Actually I'm going to hold off on this until there's a bit less code churn going on in the Bookmarks view controller. 

I think what I may do here is create a generic `SwipeDeletionDelegate` object that accepts a closure for additional actions to perform during the deletion step (deleting something from a store, etc).
