### ISSUE TITLE
New Issues view can appear under the navigation bar

### ISSUE THREAD

**Issue by heshamsalman** [rnystrom/GitHawk#713]
<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1079)
Device: iPhone 7 (iOS 11.0)
TestFlight: true
</pre>
</details>

**Comment by heshamsalman** [comment]
![b6769d95-6f03-4790-a68e-e296a9e30a94](https://user-images.githubusercontent.com/3388381/31917564-35aecfb6-b826-11e7-8509-3a9142b0c6c4.png)

**Comment by BasThomas** [comment]
Yeah, saw this a few times too. Any idea what causes it?

**Comment by rnystrom** [comment]
Same, I think the iOS 11 header is to blame...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Yeah, I think it is involved. But haven't seen the issue anywhere else (in my apps / other apps using the new headers)

**Comment by Sherlouk** [comment]
Yeah I've seen this as well - May be completely coincidental but I was seeing it more when the loading spinner was visible and then navigating to it (so the soft reload mechanism)

🤷‍♂️

**Comment by BasThomas** [comment]
Yeah, feels like it's happening upon reload. Think I saw it a few times after closing and reopening the app I think.

**Comment by rnystrom** [comment]
Maybe the refresh-on-open trigger is firing too early for UIKit to handle? I’ll try delaying it somehow.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
