### ISSUE TITLE
Issue label occasionally doesn’t appear visible

### ISSUE THREAD

**Issue by heshamsalman** [rnystrom/GitHawk#715]
<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1079)
Device: iPhone 7 (iOS 11.0)
TestFlight: true
</pre>
</details>

**Comment by heshamsalman** [comment]
There’s space for it in the “New Issues View can appear under...” cell. 

![88a234d0-a4b1-4869-89fa-f5d63fab628e](https://user-images.githubusercontent.com/3388381/31918126-09001eae-b829-11e7-940e-934a64c5f530.png)

**Comment by rnystrom** [comment]
Yuck. Bad height calculation?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by joerocca** [comment]
Whoops! I didn’t check if label arrays were equal in the isEqual method. Will submit a fix!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
