### ISSUE TITLE
Inconsistent nav bar back button  

### ISSUE THREAD

**Issue by rizwankce** [rnystrom/GitHawk#718]
In some place, we show nav with a left button with text as "Back". In some place, we just show without the text.

Also, we do have a `UIViewController` extension `makeBackBarItemEmpty` to make it empty and it is used in less place. Is it expected? or we should be using empty back button throughout the app.

**With Text**

![screen shot 2017-10-24 at 10 36 48 am](https://user-images.githubusercontent.com/12063704/31925608-a07429c8-b8a7-11e7-99fe-be8371a15d1e.png)

**Without Text**
![screen shot 2017-10-24 at 10 37 18 am](https://user-images.githubusercontent.com/12063704/31925609-a0b679a4-b8a7-11e7-898f-2740a1dff259.png)

**Comment by BasThomas** [comment]
I feel like we should default to what the system gives us; which means to not make it empty on purpose.

**Comment by rizwankce** [comment]
I like nav bar back without the text. It gives more space for our title

**Comment by BasThomas** [comment]
Yes - but the system will remove the back bar if it would need more space for the title automatically. :)

**Comment by rnystrom** [comment]
We should

- Clear the text in almost all cases (use the extension)
- Keep the text for root > next transitions (eg Inbox > Archive transition)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
