### ISSUE TITLE
Haptic feedback when closing issue?

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#721]
<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1079)
Device: iPhone 7 Plus (iOS 11.0.3)
TestFlight: false
</pre>
</details>

**Comment by heshamsalman** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/9281517-126668513_5-s1-v1.png?transparent=1&palette=1&width=246)

**Comment by BasThomas** [comment]
Warning / error / success?

**Comment by rnystrom** [comment]
Success I think

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
