### ISSUE TITLE
Adding label then refreshing issues doesn’t add label dot

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#722]
![GitHawk Upload by Sherlouk](https://i.imgur.com/EUSHySD.jpg)However it does increase the size of the cell.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1079)
Device: iPhone 7 Plus (iOS 11.0.3)
TestFlight: false
</pre>
</details>

**Comment by rnystrom** [comment]
Scrolling back does update the cell tho. Seems like the model is missing labels in its equality check.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by heshamsalman** [comment]
duplicate #715?

**Comment by joerocca** [comment]
Fixed in #716

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by heshamsalman** [comment]
Closing as a dupe of #715

**Comment by rnystrom** [comment]
😍

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
