### ISSUE TITLE
Pull Requests controller sometimes doesn’t re-adjust after pull to refresh

### ISSUE THREAD

**Issue by heshamsalman** [rnystrom/GitHawk#723]
Tough to repro, I've only seen it a few times. Figure that makes this the _lowest_ of low priority

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by heshamsalman** [comment]
![a91ee69d-5b6b-4103-bd6d-2744bba563a1](https://user-images.githubusercontent.com/3388381/31959231-215ca62c-b8c2-11e7-8303-e3bcf6be971b.png)

**Comment by rnystrom** [comment]
I bet this and #490 are related... I hate this bug

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
😭 How do you think they are related tho @rnystrom?

**Comment by rnystrom** [comment]
Oh I read this as “update” not adjust, lol. Ignore me.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
