### ISSUE TITLE
iOS 10 audit

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#730]
Re: https://github.com/rnystrom/GitHawk/issues/728#issuecomment-339216031

We should do some (more) testing on iOS 10 before shipping a release.

**Comment by BasThomas** [comment]
Do you have numbers on iOS version usage, @rnystrom?

**Comment by rnystrom** [comment]
Agreed, using the new headers will def require more of an audit. I'm inching closer and closer to backing out of them lol.

However, very few ppl are using GitHawk on iOS 10. Will only continue to drop.

<img width="1045" alt="screen shot 2017-10-25 at 11 13 11 am" src="https://user-images.githubusercontent.com/739696/32006717-85799f6c-b975-11e7-9c1d-bc961a02ae6b.png">

---

Side note, I started using handoff w/ Chrome a lot more. It's great 🙏

**Comment by BasThomas** [comment]
Happy to hear that Handoff is working for you! Regarding supporting multiple iOS versions: as it’s a GitHub I was expecting this. Awesome. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by heshamsalman** [comment]
Pre-release, someone ping me to do a quick smoke of the test-flight release candidate. I've got an iPhone 5S on iOS10 lying around.

**Comment by BasThomas** [comment]
Seems 👍 on iPad and iPhone
