### ISSUE TITLE
Remove search from bookmarks?

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#734]
Maybe we add this once people are adding hundreds of bookmarks? Idk, seems like a waste of space atm. Thoughts?

**Comment by BasThomas** [comment]
I think we shouldn’t remove it, but rather tuck the searchBar underneath the nav bar by default (like Settings.app)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Because... how would you “know” when people are adding many items there?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rizwankce** [comment]
Agree with @BasThomas. Also, I made a fix on #729 which hides search under the nav bar.

This is how it looks. You can get the search bar just by swipe down. (W/ a free transition from nav bar on iOS 11)
![screen shot 2017-10-25 at 7 54 38 pm](https://user-images.githubusercontent.com/12063704/32003993-5fe14bd0-b9be-11e7-931f-d3d5c1970e7d.png)
