### ISSUE TITLE
Bookmark quick action has no icon

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#736]
<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1106)
Device: iPhone 6s Plus (iOS 11.1)
TestFlight: true
</pre>
</details>

**Comment by rizwankce** [comment]
You mean 3D touch icon?

**Comment by Sherlouk** [comment]
Yup

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
