### ISSUE TITLE
Evaluate “open in Safari” button on PR review cell

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#741]
Would this be something to add in the meantime we can’t access PR review comments? I’m conflicted about it though as it would mark issues as read. 😕

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1106)
Device: iPhone 7 Plus (iOS 11.0.3)
TestFlight: true
</pre>
</details>

**Comment by Sherlouk** [comment]
We could just show the threads natively 😉

**Comment by BasThomas** [comment]
Yep!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
