### ISSUE TITLE
2x settings icon is cut off at the bottom

### ISSUE THREAD

**Issue by joerocca** [rnystrom/GitHawk#742]
<img width="62" alt="screen shot 2017-10-25 at 4 52 28 pm" src="https://user-images.githubusercontent.com/10346184/32023974-f8c47e32-b9a8-11e7-93ae-ac24b97ec901.png">
<img width="194" alt="screen shot 2017-10-25 at 5 19 54 pm" src="https://user-images.githubusercontent.com/10346184/32023976-fa0aa2a8-b9a8-11e7-9833-6ced565d0950.png">

**Comment by rnystrom** [comment]
Oops

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
