### ISSUE TITLE
Tab bar search item has two icon sizes

### ISSUE THREAD

**Issue by heshamsalman** [rnystrom/GitHawk#744]
Selected state & deselected state are _slightly_ different sizes.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1106)
Device: iPhone 7 (iOS 11.0)
TestFlight: true
</pre>
</details>

**Comment by BasThomas** [comment]
I think this *might* be intended as a selected/deselected state is quite tricky for search. Not sure though. @rnystrom?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Yup this is intentional

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
