### ISSUE TITLE
Create UITableViewCell subclass for code browsing cells

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#749]
We should move the setup for the code browsing cells to a separate subclass to not overcomplicate the ViewController.

Code is [here](https://github.com/rnystrom/GitHawk/blob/master/Classes/Repository/RepositoryCodeDirectoryViewController.swift#L102-L112).

**Comment by Nixsm** [comment]
I want to try this

**Comment by rizwankce** [comment]
You mean table view cell right? Becuase for now we use table view for code browsing 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Oops, of course @rizwankce
