### ISSUE TITLE
Gif support

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#75]

**Comment by Sherlouk** [comment]
So we do actually already have half support for GIFs because we have NYTPhotoViewer, it brings with it `FLAnimatedImage`.

SDWebImage also supports `FLAnimatedImage`.

If we change our `UIImageView`s out to be the `FLAnimatedImageView` we could begin to get them working throughout comments.

Additionally if we add `ANIMATED_GIF_SUPPORT` as a compiler flag - NYT should start showing them as GIFs also (see code below)

https://github.com/NYTimes/NYTPhotoViewer/blob/master/NYTPhotoViewer/NYTScalingImageView.m#L21

**Comment by BasThomas** [comment]
Ref #313

**Comment by BasThomas** [comment]
Test
![giphy](https://user-images.githubusercontent.com/4190298/31536967-e293e1ea-b000-11e7-975c-ef80ac526e9e.gif)

**Comment by BasThomas** [comment]
OK, so I thought maybe the size would be an issue. Maybe not.

**Comment by BasThomas** [comment]
Re: Is it getting to https://github.com/NYTimes/NYTPhotoViewer/blob/master/NYTPhotoViewer/NYTScalingImageView.m#L125?

Yes, when you tap on the image; not before.

**Comment by BasThomas** [comment]
Also interesting: The `NYTPhotoViewer` master doesn't actually compile, and errors on `FLAnimatedImage`.

<img width="1512" alt="screen shot 2017-10-13 at 10 33 12" src="https://user-images.githubusercontent.com/4190298/31537328-fcb19922-b001-11e7-87a7-b56f298692b1.png">

**Comment by BasThomas** [comment]
OK, so I had to do a `carthage bootstrap`. 🙄

It works in their example app. Maybe the issue is GitHub-related?

**Comment by Sherlouk** [comment]
Try overriding the URL to a GIF hosted directly on Imgur or something (removing the parsing from Markdown or GitHub being an issue)

**Comment by BasThomas** [comment]
```
/**
 *  The image data to display.
 *  
 *  This property's value, if non-`nil`, is preferred over `-image`. This allows clients to provide image data for FLAnimatedImage when the library is compiled with `ANIMATED_GIF_SUPPORT` defined.
 *
 *  Note that if you're working with a non-animated image, using a native `UIImage` will provide better performance. Therefore, it is recommended to return `nil` from this property unless this photo is an animated GIF.
 */
```
Aha!

**Comment by BasThomas** [comment]
So I can't seem to get it to work at this point, but this should be good enough of a pointer for someone else to pick this up. 😇

**Comment by Sherlouk** [comment]
Ahh good spot! I know what it wants, and know how to do it -- Will pick this up 😄

**Comment by BasThomas** [comment]
FWIW, just passing it

```swift
self.imageData = image.sd_imageData()
```

didn't work either, and then I didn't want to look into it further.
