### ISSUE TITLE
Unify image colors

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#752]
The repository image in Search is grey, but in Bookmarks it is blue.

**Comment by rizwankce** [comment]
so what to change here.

Option 1: Bookmarks image color to grey 
Option 2: Search repo image color to blue

**Comment by BasThomas** [comment]
I would opt for blue!

**Comment by rizwankce** [comment]
I would opt for blue as well. Let's hear from @rnystrom as well.

**Comment by rnystrom** [comment]
Blue sounds good. Should prob also add the icon to actual search results too.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
