### ISSUE TITLE
Add image upload to comments

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#758]
<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1106)
Device: iPhone 7 Plus (iOS 11.0.3)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
@Sherlouk what was the reason not to do this by default?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Just wanted to wait until we had tested it a little, absolutely zero reason otherwise!

**Comment by Sherlouk** [comment]
@rnystrom 1.12.0 or na? It's a one liner to change!

**Comment by rnystrom** [comment]
@Sherlouk let's do it!
