### ISSUE TITLE
Nav bar hairline not visible

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#759]
![GitHawk Upload by Sherlouk](https://i.imgur.com/ZvYiLaz.jpg)Might be related to the nav bar clipping maybe?

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1106)
Device: iPhone 7 Plus (iOS 11.0.3)
TestFlight: true
</pre>
</details>

**Comment by BasThomas** [comment]
@Sherlouk “GitHawk upload by Sherlock”. Did you hardcode this 😂

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Na I uploaded your image for you? 😂 

Sooooo basically in amidst my refactor I remember "temporarily" changing it to Sherlouk while I fixed a bug. If you check like all of the first commits I had it coming from the login manager. Evidently I forgot to put that logic back in 😂 

OOPSSS SORRY

**Comment by rnystrom** [comment]
I have no idea how this happened. We don’t mess with the nav bar. @BasThomas can you consistently repro? If not let’s close.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
No, but it’s happening quite a bit. Seems like once it’s happening, only a force quit and relaunch fixes it. I’ll keep an eye on it and see if I can narrow it down. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Only in the issue view? You might be able to use FLEX and find out where it went.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
