### ISSUE TITLE
Image preview before uploading

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#760]
Adding an image is not really viewable, as it is super small

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1106)
Device: iPhone 7 Plus (iOS 11.0.3)
TestFlight: true
</pre>
</details>

**Comment by Sherlouk** [comment]
The original intention was to allow tapping on the image to open it in a full screen viewer with markup support. A quick win could be to use NYTPhotoViewer for now? and add markup as a later feature?

**Comment by BasThomas** [comment]
Yeah, I was thinking that would work too. Or a separate step after picking a photo? So pick -> edit -> upload?

**Comment by BasThomas** [comment]
Agree that markup would be awesome, but it's shouldn't block this.
