### ISSUE TITLE
Code file viewer loading while already showing contents

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#764]
<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1106)
Device: iPhone 7 Plus (iOS 11.0.3)
TestFlight: true
</pre>
</details>

**Comment by rizwankce** [comment]
when is this exactly happening? Maybe step to reproduce would help.

**Comment by BasThomas** [comment]
Seems like it's happening quite a lot, especially when reloading (so if you viewed said file before).

So, steps to reproduce:

Open code browser
Open file
(optionally) go back and open the same file

**Comment by rnystrom** [comment]
Does the loading indicator go away? What exactly is the issue?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
It does, just weird that it seems to be loading still when the file’s already there. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
There’s a min delay on the refresh indicator, prevents it from flickering closed when the response is quick. We could change this to how Feed.swift does it and wait for the didAppear event, check if loading, then display. That’ll stop it from appearing at all when the network is snappy.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
