### ISSUE TITLE
Image upload alt text hardcoded to me

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#765]
https://github.com/rnystrom/GitHawk/blob/012a5b32169982eb1fb939fccf87f9d255360185/Classes/Views/TextActionsController.swift#L63-L65

😂 Oops...

https://github.com/rnystrom/GitHawk/issues/759#issuecomment-339803210

Gets compile issue, hard codes it, doesn't go back and fix it. Tell me I'm not alone? Please? 😞

**Comment by heshamsalman** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/9725180-126668513_14-s1-v1.png?transparent=1&palette=1&width=246)

**Comment by BasThomas** [comment]
I was legit not able to stop laughing at this last night 😁

**Comment by Sherlouk** [comment]
I'm human! 😞
