### ISSUE TITLE
User profile avatar not updating

### ISSUE THREAD

**Issue by rizwankce** [rnystrom/GitHawk#769]
When user changes the avatar, Githawk is not updating and uses old avatar. 

**From Githawk** :
![GitHawk Upload by Sherlouk](https://i.imgur.com/nGx6lux.jpg)

**From Github**: 
![GitHawk Upload by Sherlouk](https://i.imgur.com/Q1A4l4x.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1106)
Device: iPhone 7 Plus (iOS 11.0.3)
TestFlight: true
</pre>
</details>

**Comment by BasThomas** [comment]
Should just be caching; it's updated for me. Not sure what we could do here; probably not worth tossing away cache every single time.

**Comment by rizwankce** [comment]
Agree on - " tossing away cache is not good idea"

**Comment by Sherlouk** [comment]
You'd think the URL would change clearing the cache 🤔

**Comment by BasThomas** [comment]
What is the URL we get from the API? Because there’s this url (view image from profile): https://avatars2.githubusercontent.com/u/4190298?s=460&v=4 but it seems to be generated somehow by this static url: "https://github.com/basthomas.png?size=100"

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
GraphQL url:

https://avatars0.githubusercontent.com/u/4190298?v=4

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Closing bc I don’t think we should much with the cache. It updated after a day for me.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Yeah, think it’s no big deal. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
