### ISSUE TITLE
Specify that image upload title and message are optional

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#771]
![GitHawk Upload by Sherlouk](https://i.imgur.com/IiQPWAV.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1106)
Device: iPhone 7 Plus (iOS 11.0.3)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
Agree

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
