### ISSUE TITLE
Add sucess haptic after new issue created

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#772]
Especially since we are waiting for a spinner, it would be nice to get some extra feedback.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1106)
Device: iPhone 7 Plus (iOS 11.0.3)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
Idk of this is totally necessary since the view gets pushed

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Yeah, was actually thinking about not doing this. Overdoing might make using it more unclear. Closing. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Ya def wanna be careful about overdoing the haptics

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
