### ISSUE TITLE
Bookmarks do not update until view is reloaded

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#773]
If you add a bookmark from within a detail view with bookmark as the master view, the list will not directly update

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1106)
Device: iPad Pro (iOS 11.0.3)
TestFlight: true
</pre>
</details>

**Comment by rizwankce** [comment]
Any idea how we can tackle this? Sending `NSNotification` maybe?

**Comment by BasThomas** [comment]
That could work 👍

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Please no notifications. Explicitly wire up listeners with the announcer pattern we’re using in the client and flat cache. We could come up with a generic version of it if necessary.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Btw listeners will be much more doable now that I threaded a single store object to everything.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
