### ISSUE TITLE
Can we rename Notification model name?

### ISSUE THREAD

**Issue by rizwankce** [rnystrom/GitHawk#774]
[Notification.swift](https://github.com/rnystrom/GitHawk/blob/ced86af943458feaad8ce24e8ec52c7b6e10e5a7/Classes/Models/Notification.swift) hides [Notification](https://developer.apple.com/documentation/foundation/notification) class from swift.

Shall we rename it to something like `NotificationModel`?

**Comment by rnystrom** [comment]
Sgtm, or “NotificationResponse”

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
