### ISSUE TITLE
Add image upload at last insertion point

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#776]
Or at least at the bottom instead of the top.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1106)
Device: iPhone 7 Plus (iOS 11.0.3)
TestFlight: true
</pre>
</details>

**Comment by Sherlouk** [comment]
It should be based on where your cursor is, given it's using the same methods as markdown 🤔

**Comment by rnystrom** [comment]
done
