### ISSUE TITLE
First ITC upload from buddybuild

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#782]
More of a PSA than issue. Going to try this. Lmk if anything explodes.

**Comment by rnystrom** [comment]
> Dear developer,
> 
> We have discovered one or more issues with your recent delivery for "GitHawk for GitHub". To process your delivery, the following issues must be corrected:
> 
> Invalid Pre-Release Build - The CFBundleVersion key in the app’s Info.plist file contains a build number (16) that’s lower than the latest build number (1106) that’s been submitted for the app version '1.12.0'.
> 
> Once these issues have been corrected, you can then redeliver the corrected binary.
> 
> Regards,
> 
> The App Store team

Need to disable BB from messing w/ the build #. Brb.

**Comment by Sherlouk** [comment]
When you set it up to do deployments it asks you how to handle the build number. At the bottom there's an option to "Not touch it" which would let it use our script. Otherwise it has other ways to manage it which would work better for us (including using the timestamp, will always be higher!) (unless we timetravel)

**Comment by Sherlouk** [comment]
Heads up btw I've been getting private builds for a while now 😅  Forgot to make them open but they get distributed every couple days if something's changed. Kinda nice!

**Comment by rnystrom** [comment]
Yup it’s set to “no touching” but the script set the commit count to 16. I’ll need to dig further.

What do you mean getting private builds?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
https://dashboard.buddybuild.com/apps/59d904ff8588d60001729c4e/testers

Under "Deploy with Buddybuild" on Mondays and Thursdays if there have been new changes pushed to master then I get an email with a new build installed via Buddybuild 😅 Currently only sent to my email but yaa I don't mind builds all the time as I like to be testing the latest stuff on my device! (And don't have the same BS issues as iTC)

Maybe allow Buddybuild to take control of the build version, it has an option "use commit count" and see what that does? When I played around with it before it seemed to get the full count, but maybe I was wrong. If it doesn't just try a different option? As long as someone is maintaining it (either our script or BB) does it really matter?
