### ISSUE TITLE
Tone down recent searches

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#791]
![GitHawk Upload by Sherlouk](https://i.imgur.com/YFgQrSb.jpg)

This were my recent searches after typing IGListKit with some typos. Maybe make sure the search is longer than an x amount onscreen?

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1106)
Device: iPhone 7 Plus (iOS 11.0.3)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
This is exactly the same as Spotify recent search works and I think it’s pretty good. Maybe my only suggestion would be to separate strings and recently viewed? 

Or we do away with the search string in general and just store what you tapped.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
I feel like it's a bit much, but would love to get some more opinions on this. Especially from people that use search quite a bit.

**Comment by Sherlouk** [comment]
I used to use recent searches as a bit of a bookmarks tool, but tbh now that I have bookmarks I basically don't use search 🤷‍♂️ 

Genuinely I feel like there's not much use of recent searches over bookmarks, I don't often search for something and then want to re-see the results. I search for a repo, and then want to go back to it again.

Maybe if it was like "Trending Searches" or something, I could get behind that but yh
