### ISSUE TITLE
Scroll to bottom on issue close/lock

### ISSUE THREAD

**Issue by joerocca** [rnystrom/GitHawk#793]
<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
What about top or bottom, w/e you're closer to? Or just top? We change the top status cell as well.

**Comment by joerocca** [comment]
To me It seems more natural to scroll to bottom for latest, but typically when closing an issue you no longer need to view the latest comments/actions so I’m not sure. Maybe if top status cell is visible we don’t scroll? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
