### ISSUE TITLE
Big IPA?

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#798]
I'm uploading to TestFlight and the IPA is a whopping 124mb! 😱 

<img width="402" alt="screen shot 2017-10-29 at 10 16 28 pm" src="https://user-images.githubusercontent.com/739696/32155864-55eff824-bcf7-11e7-8c39-d0323eecb4fe.png">

Trying to brainstorm if something changed or what could have caused this. Build 1106 was uploaded on 10/24 with only 19.4mb App Store size.

<img width="350" alt="screen shot 2017-10-29 at 10 19 01 pm" src="https://user-images.githubusercontent.com/739696/32155850-3e94cbe6-bcf7-11e7-809a-0215436118d0.png">

**Comment by rizwankce** [comment]
Easiest way would be `UnArchive` the IPA and select app file under Payload. Then right click “show package content” and go through the files.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
SwiftLint binary?

**Comment by heshamsalman** [comment]
@Sherlouk y'know, in retrospect maybe it should've been flagged as a debug only include

**Comment by Sherlouk** [comment]
@heshamsalman Probably not a disastrous idea, but I feel like someone on SwiftLint's idea would've identifier this and thought "maybe this isn't a great idea"?

Personally I'd move the SwiftLint binary into it's own directory (See how I've done [`license-plist`](https://github.com/rnystrom/GitHawk/tree/master/tools/bin)) and avoid the issue entirely?

**Comment by heshamsalman** [comment]
@Sherlouk definitely the right move if that's actually the culprit

**Comment by Sherlouk** [comment]
@heshamsalman Updated my original comment (should've posted new comment in hindsight) but looks like SwiftLint is only 16MB on my local machine. That doesn't account for any archival weirdness Xcode does but I doubt it's causing over 100MB increase in IPA size.

I might download an IPA later and see if I can identify any big files!

**Comment by Sherlouk** [comment]
Okay further analysis:

I've expanded the IPA, SwiftLint is *not* in the frameworks list so it must get compiled out somewhere somehow.

In the IPA the culprits are the dylib files, specifically: `libswiftCore.dylib`, `libswiftFoundation.dylib` making just under 100MB between them.

Hazarding a complete guess here, I wonder if this is something to do with the version of Xcode being used? Or more likely updating to Swift 4? 🤷‍♂️ 

From what Buddybuild is printing under "iTunesConnect IPA" it's been 124MB since we started creating builds on it. Granted this doesn't tell us much since we've been using it only since we've been on Xcode 9.

**Comment by BasThomas** [comment]
No red flags regarding Swift libs or whatever. Re: App Store makes it smaller: curious to see this - what is the size when uploaded to iTunes Connect? With App Thinning the app will be even smaller in the App Store, but that wouldn't explain the size difference in `IPA`s.

**Comment by rnystrom** [comment]
For my own curiosity, I tried

```
pod 'SwiftLint', :configurations => ['Debug']
```

And it didn't change.

**Comment by rnystrom** [comment]
Latest build is only 19.5mb on App Store even though uploaded IPA is 124mb. Weird! I called this out b/c uploading on airplane wifi was taking a lot time lol. I guess this is normal?

<img width="334" alt="screen shot 2017-11-01 at 9 38 46 am" src="https://user-images.githubusercontent.com/739696/32285759-8f973b9e-bee8-11e7-9421-9e21e179d03b.png">
