### ISSUE TITLE
Double tap comment to 👍

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#802]
<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1106)
Device: iPhone 7 Plus (iOS 11.0.3)
TestFlight: false
</pre>
</details>

**Comment by Sherlouk** [comment]
What are we? Instagram?

Oh wait... 🤔 🤔 😂

**Comment by heshamsalman** [comment]
[bitmoji](https://render.bitstrips.com/v2/cpanel/9946282-126668513_14-s1-v1.png?transparent=1&palette=1&width=246)

**Comment by rnystrom** [comment]
I discovered this on reddit today too, I love it.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
\*double taps\*

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
