### ISSUE TITLE
Sample Data compiled in release builds

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#804]
Related to #798 

In expanding the release IPAs generated from Buddybuild I've noticed that the sample JSON files are not being excluded.

Namely:
- authorizations.json
- _graphql.json
- _notifications.json

Definitely not big or worrisome, but should probably get rid of them for non-debug builds? @rnystrom

**Comment by rnystrom** [comment]
Lol ya gut em

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
done
