### ISSUE TITLE
iOS 10: search view improperly laying out

### ISSUE THREAD

**Issue by heshamsalman** [rnystrom/GitHawk#810]
![GitHawk Upload by Sherlouk](https://i.imgur.com/0uaWGex.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1106)
Device: iPhone 5s (iOS 10.3.2)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
I think I fixed this on the airplane over the weekend. Will find commit. Reminds me to publish new beta!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
#786
