### ISSUE TITLE
No way to leave bookmarks search

### ISSUE THREAD

**Issue by heshamsalman** [rnystrom/GitHawk#811]
Once you activate bookmarks search on an iOS 10 device (I'm testing on a 5S) there is no way to trigger a resign first responder without killing the app.  (scrolling, tapping, hitting clear all did nothing)

May not be iOS 10 specific, but found on an iOS10 iPhone 5S

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1106)
Device: iPhone 5s (iOS 10.3.2)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
@rizwankce 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rizwankce** [comment]
@heshamsalman guess it's fixed in latest test flight build 1127. Isn't? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by heshamsalman** [comment]
@rizwankce just pulled latest TestFlight. We're good ✌️

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
