### ISSUE TITLE
BookmarksViewController cells should have dynamic size

### ISSUE THREAD

**Issue by heshamsalman** [rnystrom/GitHawk#812]
When a cell has large content it can overflow out of the bounds of the cell.

![img_0004](https://user-images.githubusercontent.com/3388381/32250081-8a6dd0a6-be61-11e7-8d69-edc9efbe3f86.png)

**Comment by rnystrom** [comment]
cc @rizwankce 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Either fix to 1 line and truncate or needs dynamic size. Truncation is maybe ok? The bookmarks architecture is pretty bare-bones, idk how complicated it'll be to add dynamic height at this point...

**Comment by rizwankce** [comment]
Bookmark cell is simple `UITableViewCell` and it has dynamic size enabled already. Maybe recent changes related to swipe to delete broke something. I'm gonna check that now.

**Comment by heshamsalman** [comment]
If memory serves @rizwankce I changed the heightForRowAt from 40 to something in the constants. Probably should've made that an _estimatedHeightForRowAt_ 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rizwankce** [comment]
No pressure! Pushed a PR to add dynamic sizing. 👍
