### ISSUE TITLE
iOS 10: code viewer improperly laying out

### ISSUE THREAD

**Issue by heshamsalman** [rnystrom/GitHawk#813]
Start of file is obscured by nav. Related to #810. 

![GitHawk Upload by Sherlouk](https://i.imgur.com/UlbqOvi.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1106)
Device: iPhone 5s (iOS 10.3.2)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
@heshamsalman is this still the case I. The latest TF?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Just checked; it's fixed 👍
