### ISSUE TITLE
Repository 'code' view shows master instead of default

### ISSUE THREAD

**Issue by bobheadxi** [rnystrom/GitHawk#824]
Code view shows the state of `master` instead of the repository's default branch ie `dev` - not sure if intentional

**Comment by Sherlouk** [comment]
I'd say we should definitely change this, do you have an example of a repo which is configured as such for testing?

**Comment by rnystrom** [comment]
TIL you can change the default branch...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
@rnystrom Just need to chuck this somewhere:

```gql
... on Repository {
  defaultBranchRef {
    name
  }
}
```

**Comment by bobheadxi** [comment]
Some repos I've worked on that have `dev` as default:
- [1](https://github.com/bobheadxi/facebook-spotify-chatbot)
- [2](https://github.com/d4rken/reddit-android-appstore)

**Comment by rnystrom** [comment]
Maybe we need to just add branch selection in general. Atm it’s fixed for simplicity. However adding an extra call makes it basically as complicated as switching when you’re at the root dir.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
