### ISSUE TITLE
Add “user’s comment” to alert title and simplify actions

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#826]
![GitHawk Upload by rnystrom](https://i.imgur.com/LQniRgB.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1137)
Device: iPhone 7 Plus (iOS 11.0.3)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment]
What do you mean by "simplify actions"?

**Comment by rnystrom** [comment]
Sorry, “edit comment” can just be “edit”

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rizwankce** [comment]
what if user's comment is long. Don't think it would look good on Alert title IMO

**Comment by rnystrom** [comment]
No sorry I meant “user” like username. So

> rizwankce’s comment

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rizwankce** [comment]
gotcha 👍

**Comment by joerocca** [comment]
Related to #801

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
