### ISSUE TITLE
Open in Safari missing

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#829]
![GitHawk Upload by BasThomas](https://i.imgur.com/14NzY7y.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1137)
Device: iPhone 7 Plus (iOS 11.1)
TestFlight: true
</pre>
</details>

**Comment by Sherlouk** [comment]
Out of curiosity, do form sheets have a max action count?

**Comment by rizwankce** [comment]
As I can see from reddit app, there is no max action count. After certain limit it will just scroll

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rizwankce** [comment]
It was removed exactly in this commit https://github.com/rnystrom/GitHawk/commit/18801a10647c6b25542b101dbc240659df61095e

Is it intended? @rnystrom

**Comment by rnystrom** [comment]
Yup you can open in safari via share. Was redundant and taking up space.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Noooo but that opens Safari.app, not SafariVC :(
To be fair I did use this to check review comments when I saw I had a notification but I saw no new messages. Should be better once #828 lands
