### ISSUE TITLE
Only initial login works with SFAuth

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#831]
Setup auto-logs in when previously logging in on Safari, but then accessing an issue or permissions needs logging in again

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1137)
Device: iPhone10,6 (iOS 11.1)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
Oh weird shouldn’t it all use the same thing? Did SFAuth not get added to login?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
I think it's the other way around?

**Comment by joerocca** [comment]
AFAuthenticationSession doesn't share the session with SFSafariViewController.

**Comment by rnystrom** [comment]
@joerocca what is `AFAuthenticationSession`?

**Comment by joerocca** [comment]
@rnystrom oops, typo!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Haha, I read it as AFAuthenticationSession doesn't share w/ SFAuthenticationSession, now I see it. Here's how I see our options:

- Revert the `SFAuthenticationSession` stuff. This stinks b/c then if you have an active GitHub session in Safari.app, you can't take advantage of that.
- Remove the setting
- Have the setting `openURL` to Safari.app
- Leave it alone (maybe add a subtitle/disclaimer that might have to login again)

I guess this calls out a larger issue that our use of `SFAuthenticationSession`+`SFSafariViewController` is going to result in an inconsistent experience. Even if you open stuff like profile in a webview, you wont be logged in yet.

Sort of makes me lean towards reverting `SFAuthenticationSession` until we have 0 `SFSafariViewController`.

Thoughts?

**Comment by BasThomas** [comment]
Yeah, I'd go for reverting it. Also feel like the 0 `SFSafariViewController` isn't really something we can achieve soon. Having to log in just the once would make more sense then being logged in automatically but then finding you have to login again for certain webviews.

**Comment by joerocca** [comment]
Yeah, this is a tough choice because reverting will reopen #426. Is not having to log in again in safari worth losing the ability to log out? I feel like having to log in to safari is more of an inconvenience whereas inability to log out is a problem.

**Comment by rnystrom** [comment]
Ack that’s true. Uggggh. Maybe we just leave it alone then. Not being able to log out is pretty bad too.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Ok I think we should open permissions into Safari.app since `SFAuthenticationSession` shares info w/ Safari. Issues can only be opened in Safari.app anymore, and stuff like profile will eventually be native.

Everyone ok w/ this? @joerocca @BasThomas

**Comment by BasThomas** [comment]
Not loving it, but I get the reason. What about “view source code”, do you want to redirect that to the native repo view, maybe deeplinked to the code tab?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by joerocca** [comment]
Yeah, I️ think that is the best compromise.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
I’m not as concerned about the view source yet. I think GitHub offers more browsing tools and stuff. If we had a way to share out of the native code section I’d say ya.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by viktorgardart** [comment]
#~~~~

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
