### ISSUE TITLE
Code view does not respect safe area

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#836]
<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1137)
Device: iPhone10,6 (iOS 11.1)
TestFlight: true
</pre>
</details>

**Comment by Sherlouk** [comment]
Wanna rub it in a little bit more? 😢

**Comment by BasThomas** [comment]
Sorry! I mean, should I not create tickets? 😭

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
😂 We need a feature to ignore notifications with the iPhone X label 🤔 Nah keep it up!

**Comment by rnystrom** [comment]
does now
