### ISSUE TITLE
“Lock” is visible for unauthorized users

### ISSUE THREAD

**Issue by viktorgardart** [rnystrom/GitHawk#839]
![GitHawk Upload by viktorgardart](https://i.imgur.com/URZDr8M.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1137)
Device: iPhone10,6 (iOS 11.1)
TestFlight: true
</pre>
</details>

**Comment by viktorgardart** [comment]
Probably semi related to #712

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Yeah it all comes round to basically having no "ideal" way to know whether the user has permission :/ Probably wanna merge it all into one

**Comment by rnystrom** [comment]
I might just have to lock down editing controls to admins since that's the only permissions we have access to. Unless we want to make [another request](https://developer.github.com/v3/repos/collaborators/#check-if-a-user-is-a-collaborator).

**Comment by Sherlouk** [comment]
@rnystrom From a productivity standpoint I'd be strongly against making it admin only, genuinely it disables a large piece of functionality that I find highly useful via GitHawk (labelling, locking, closing, etc) 

If another request is the only way to do it then I say we do it. Maybe one thing we could do is use author association on comments and see if that's collaborator, so we don't make the request if we don't need to.

Also I'd say enable caching on it of like 24hrs? maybe longer? So we don't use an extra rate token for every single issue!
