### ISSUE TITLE
Refresh control as loading indicator?

### ISSUE THREAD

**Issue by hollanderbart** [rnystrom/GitHawk#841]
Hi,

Thanks for developing githawk. I really like the simplicity. 
I noticed you’re using the refresh control as the indicator for the initial load indicator. Is this the expected behavior for you? Wouldn’t you want to distinguish initial loading with reloading?

Best regards,
Bart

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.11.0 (2114)
Device: iPhone 7 (iOS 11.2)
TestFlight: false
</pre>
</details>

**Comment by rnystrom** [comment]
Hey @hollanderbart! Curious what the benefit of a different loading style would be?

**Comment by hollanderbart** [comment]
It seems odd that the screen is jumping after the initial loading state has been finished. You’re also using a different loading style in search results. I would expect that loading style for every initial loading style. This will increase consistency.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
@hollanderbart where does the jumping happen?

Agree w/ consistency, but seeing as search doesn't have a pull-to-refresh, we opted for a different design.

**Comment by hollanderbart** [comment]
The jumping happens when a page is initial loaded and the refresh control jumps up the screen. I've never seen this before in a other app and it's confusing me with a refresh.
