### ISSUE TITLE
Syntax highlighting broken?

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#842]
Is this working for you all? It's been broken for a couple weeks now. Very frustrating.

**Comment by BasThomas** [comment]
Don't think we've ever added this?

**Comment by rnystrom** [comment]
* in Xcode 😄

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by heshamsalman** [comment]
@rnystrom working fine on my end.

**Comment by rizwankce** [comment]
Had sometime before. It's not constantly hapenning though. I just restart the app and get back my highlighting back. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
