### ISSUE TITLE
Recent selections make bookmarks redundant?

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#843]
Here’s my search and bookmark status. Any thoughts?

![GitHawk Upload by rnystrom](https://i.imgur.com/uVW9Zrc.jpg)

![GitHawk Upload by rnystrom](https://i.imgur.com/ohAekLq.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1142)
Device: iPhone 7 Plus (iOS 11.1)
TestFlight: false
</pre>
</details>

**Comment by Sherlouk** [comment]
https://github.com/rnystrom/GitHawk/issues/791#issuecomment-340896408

Mentioned it here, but yeah I feel we should simplify the search area in terms of detecting repos you go to. It'd be nice if the area could be used for something else to be honest, like increased searching capabilities (more than repo, using advanced search filters, etc) or even trending repos as a "Search and Explore" sorta delio

Just throwing some ideas in the air see what sticks

**Comment by heshamsalman** [comment]
@Sherlouk liking the idea of [trending](https://github.com/trending) repos. I think recently visited seems to have made text-search history kind of irrelevant. At present, bookmarks and search kind of do the same thing, but there have been times where I've bookmarked specific issues or pull requests that may affect (but not involve) me to check in on them.

**Comment by rnystrom** [comment]
Agree, lets see where this goes once launched

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
