### ISSUE TITLE
“Archives” show only read?

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#845]
Would that make more sense? Weird to see read items in archives.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1142)
Device: iPhone 7 Plus (iOS 11.1)
TestFlight: false
</pre>
</details>

**Comment by Sherlouk** [comment]
I was thinking about this yesterday, I agree

**Comment by viktorgardart** [comment]
Been thinking about it as well, totally agree!

**Comment by rnystrom** [comment]
Well shoot, you only get unread or "all", so we'd have to filter out unread notifications which makes the paging logic a little weird...

Gonna punt this for now.
