### ISSUE TITLE
Scroll to bottom by default

### ISSUE THREAD

**Issue by mergesort** [rnystrom/GitHawk#85]
When reading through an issue, I think it would make sense to scroll the user to the last comment, rather than the first one.

Cheers!

**Comment by BasThomas** [comment]
It might even be able to scroll to one-after latest read? That'd be totally amazing.

**Comment by rnystrom** [comment]
What stinks is the comment id that I get from the notifications API (v3) doesn't relate to anything in the GraphQL API (v4), so I can't detect what the "new" comment is or anything. Scrolling to the bottom would be simple enough.

**Comment by BasThomas** [comment]
Yep, you'd have to for example start requesting the last page and let pagination kick in scrolling up.

**Comment by Sherlouk** [comment]
Done in 2a2f600
