### ISSUE TITLE
IGListKit on Bookmarks

### ISSUE THREAD

**Issue by rizwankce** [rnystrom/GitHawk#854]
Follow up from #819 

While starting we thought that bookmarks are going to be very simple table view cell with table view editing mode. Along the road, we had to do a lot more than that and added self-sizing, swipe to delete and support from iOS 10. 

Now if we step back and see, there are lots of ways we can improve or reuse using collection view cells in Bookmarks. So it would be really better to re-write bookmarks view controller to adopt IGListKit.

**Comment by rizwankce** [comment]
@heshamsalman mind pushing your iglsk re-write for this and we can pull this one together?
Or Do you want me to take care?

**Comment by heshamsalman** [comment]
@rizwankce yeah, i can push it up soon. should be ready for review ~Monday
