### ISSUE TITLE
Activities on an issue overflow on smaller devices

### ISSUE THREAD

**Issue by heshamsalman** [rnystrom/GitHawk#858]
![GitHawk Upload by heshamsalman](https://i.imgur.com/ehM6hSP.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1149)
Device: iPhone 5s (iOS 10.3.2)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
Oof good find. Maybe we should add resizing to one of the labels to it shrinks? That or we change it to one big label with attributes and dive into which attribute gets tapped. Bit more tricky but not impossible.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
We really should add word wrapping on to, the only limitation that I can think of for us not doing it is the badge colour background to "project-mgmt" the "background color attribute" doesn't look particularly nice. 

https://stackoverflow.com/a/34050391 < This SO response basically shows an example though where we could write a bit of extra logic to support that. We would then have no reason not to just support multiline attributed strings?

n.b. we'd have to use non-breaking space characters for names/labels/links/etc but that's trivial

**Comment by BasThomas** [comment]
Ref #58. Not fixed, apparently. 😉

**Comment by rnystrom** [comment]
actually if we just start using my attributes view for these it should all just work. I’ve got touch handling in that already.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Once I land the initial PR, I'll work on updating the commit and reference cells. I'm not sure we'll be able to get the labeled event cells w/out sacrificing the design (rounded bg color highlights).
