### ISSUE TITLE
Bookmark Search bar can be dragged over the empty state

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#862]
v 1.12.0 (1149) on TF. Not sure if this is caused by the search bar or the empty state
![simulator screen shot - iphone 5s - 2017-11-05 at 15 22 06](https://user-images.githubusercontent.com/4190298/32415641-19a6c848-c23d-11e7-8dba-445a952ed137.png)
.

**Comment by Sherlouk** [comment]
because it's just a background view on the table view as opposed to it's own cell which we use for search/notifications/repos/etc 

#854 would "fix" this
