### ISSUE TITLE
Issues doesn't remember scroll position

### ISSUE THREAD

**Issue by weyert** [rnystrom/GitHawk#866]
If you browse through the issues and select an issue and use the back button to head back to the Issues overview. The scroll position has changed.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1149)
Device: iPhone 6s (iOS 10.3.3)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
Noticed this too, super annoying. Fixing right now.

**Comment by rnystrom** [comment]
Somehow this came back when I moved Tabman to a local pod? It's the same version (1.0.5). Will dig.

**Comment by rnystrom** [comment]
fixed w/ tabman updates
