### ISSUE TITLE
Change Bookmark action to be a nav bar item

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#872]
- Free up alert action space
- Simpler, more intuitive UI

I'll prepare some assets and PR them if someone wants to hack at this. I think this is the last big thing I want to do before launching 1.12.0!

@rizwankce @heshamsalman @Sherlouk @BasThomas for thoughts

**Comment by Sherlouk** [comment]
I'm not sure what you're wanting here 🤷‍♂️

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
- Remove bookmark add/remove from action menu
- Put it as a bar button item in the right nav
- Outline icon when not bookmarked, solid icon when bookmarked

**Comment by BasThomas** [comment]
But what about https://github.com/rnystrom/GitHawk/issues/843?

**Comment by rnystrom** [comment]
The consensus I got there is that they will diverge over time and are each uniquely useful. I think I agree.
