### ISSUE TITLE
Issues not updated until restart

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#88]
Happened in #83. I opened the issue in Safari and added a comment, going back and refreshing in the app didn't show the comment I just posted. Killing and reopening the app did work. 

![img_1118](https://user-images.githubusercontent.com/4190298/28004413-cf35914a-6544-11e7-82f7-6f99aea1d0c7.PNG)

**Comment by rnystrom** [comment]
Last time I saw this, I [killed HTTP caching](https://github.com/rnystrom/Freetime/blob/master/Classes/Systems/Alamofire%2BGithubAPI.swift#L32) and it was fixed. I'm not sure if this is from:

- Github API caching
- Apollo GQL caching
- ???

Will dig.

Reminds me that I should add FLEX to Testflight builds so you all can do network inspecting.

**Comment by BasThomas** [comment]
Caching is definitely too aggressive here. Even issues that are in unread do not show the new comments until a reload

**Comment by rnystrom** [comment]
I remember having that issue before killing the URL cache. I wonder if I regressed that somehow?

It's niled [here](https://github.com/rnystrom/Freetime/blob/master/Classes/Systems/Alamofire%2BGithubAPI.swift#L32) and that `runningInSample()` checks a [bundle setting](https://github.com/rnystrom/Freetime/blob/3ac7e50293dcc25dfe3f8c5facbff0f6ce859e87/Resources/Snapshots-Info.plist#L44) only available in another target...

**Comment by rnystrom** [comment]
Tracking in #121
