### ISSUE TITLE
Put all @objc on same line as func

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#882]
Idk why I went w/ this style originally, but it looks clowny. Should be an easy project-wide find/replace.

**Comment by Sherlouk** [comment]
https://github.com/realm/SwiftLint/blob/5673b3fb5ed2e147be62970816263e69be3491ba/Source/SwiftLintFramework/Rules/AttributesRulesExamples.swift
https://github.com/realm/SwiftLint/blob/5673b3fb5ed2e147be62970816263e69be3491ba/Source/SwiftLintFramework/Rules/AttributesRule.swift

There's a SwiftLint rule that already exists for this 😄 Enable, and fix violations?

**Comment by rnystrom** [comment]
Yaaay, let's!

**Comment by rizwankce** [comment]
Weird! I try enabling swift lint but not working as expected.

```yml
opt_in_rules:
  - attributes
```
