### ISSUE TITLE
IGLK bookmark cells have awkward selection state

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#885]
![GitHawk Upload by rnystrom](https://i.imgur.com/Jf0lAhj.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1165)
Device: iPhone 7 Plus (iOS 11.1)
TestFlight: false
</pre>
</details>

**Comment by heshamsalman** [comment]
Ouch. Good find.
