### ISSUE TITLE
Is “Share” the right action word?

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#894]
It reads a little weird, GitHub isn’t like Twitter or something. Maybe “Send to”?

Am I being too pedantic?

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1166)
Device: iPhone 7 Plus (iOS 11.1)
TestFlight: false
</pre>
</details>

**Comment by Sherlouk** [comment]
In terms of accessibility i feel everybody knows what "Share" means 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Just want to say that I really appreciate you challenging these seemingly obvious things, @rnystrom!

**Comment by rnystrom** [comment]
IMO it’s the most fun part about projects that I use many times throughout the day. Not only do we get to make cool stuff work, but we can iron out every rough patch and make the app _feel_ great!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
