### ISSUE TITLE
Update Website Images

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#899]
ref #621

**Comment by rnystrom** [comment]
1.12.0 submitted to App Store! Will update the website w/:

- New gradient background
- 1.12.0 feature screenshots

**Comment by rnystrom** [comment]
done!

**Comment by BasThomas** [comment]
1.14 right? And nice ad campaign? 😜 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
