### ISSUE TITLE
Enable FLEX for Testflight builds

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#90]
- `git mv` the `FlexController` to `/Classes/Systems`
- Add compilation flag
- Use flag in builds for Testflight
  - Somehow add the custom flag when doing `fastlane beta`
- Make sure FLEX is [compiled in](https://github.com/rnystrom/Freetime/blob/91261835abca858adba7c62a3a4ab4b48386e137/Classes/Views/FlexController.m)

**Comment by Sherlouk** [comment]
Can think of a fairly easy way to do this, but would require sending different builds to TestFlight vs actual release - is that acceptable? @rnystrom 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
@Sherlouk yes! That's fine for me. I'll just have to pay attention to what build I'm actually sending lol.

Can we control this w/ fastlane too? Like if I do

```
$ fastlane beta
```

Do a TF build (w/ w/e build flavors we need for FLEX). But then I do 

```
$ fastlane appstore
```

And send an App Store build.

Is that easy?

**Comment by Sherlouk** [comment]
Yeah I can do that, shouldn’t be difficult!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
