### ISSUE TITLE
Larger tap target for ... buttons

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#902]
Too small, should be 44x44

![GitHawk Upload by rnystrom](https://i.imgur.com/wgyw2uu.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1166)
Device: iPhone 7 Plus (iOS 11.1)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment]
Ah so that's why they weren't always working as well. Makes sense.
