### ISSUE TITLE
IGLKCollectionLayout inset wrong, iOS10

### ISSUE THREAD

**Issue by heshamsalman** [rnystrom/GitHawk#906]
All views except for settings have content underneath the tab bar

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1163)
Device: iPhone 5s (iOS 10.3.2)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
Gonna revert that layout change and iron out issues for 1.13 instead

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Reverted
