### ISSUE TITLE
Edit comment has content underneath nav bar

### ISSUE THREAD

**Issue by heshamsalman** [rnystrom/GitHawk#907]
Makes editing a comment very difficult

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1163)
Device: iPhone 5s (iOS 10.3.2)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
@heshamsalman any tips to reproduce this? Using iOS 10.3 it seems to be working.

![simulator screen shot - iphone 7 - 2017-11-11 at 21 46 34](https://user-images.githubusercontent.com/739696/32695437-db52ba4c-c729-11e7-848c-16405004e9b2.png)

**Comment by heshamsalman** [comment]
Seems to be fine in latest test flight 

¯\_(ツ)_/¯ 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
