### ISSUE TITLE
Cells not resizing on orientation change

### ISSUE THREAD

**Issue by joerocca** [rnystrom/GitHawk#908]
![img_0164](https://user-images.githubusercontent.com/10346184/32579005-5e99738e-c4ad-11e7-996e-d514a6dd52b0.PNG)

**Comment by rnystrom** [comment]
Oh no! How did this regress

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by joerocca** [comment]
It is actually off master

**Comment by rnystrom** [comment]
Oh I bet it’s the layout change

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by weyert** [comment]
I still don't understand why UICollectionView doesn't consider invalidating it's layout when the bounds of the view change

**Comment by Sherlouk** [comment]
There's actually a function you can override for collection view layouts which do exactly that @weyert 

https://developer.apple.com/documentation/uikit/uicollectionviewlayout/1617781-shouldinvalidatelayout

**Comment by rnystrom** [comment]
Which we use:

https://github.com/Instagram/IGListKit/blob/master/Source/IGListCollectionViewLayout.mm#L364

**Comment by rnystrom** [comment]
Closing for now, will revisit once we ship 1.12 and reland the changes. Reverted the commit.
