### ISSUE TITLE
Bookmark confirmation

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#920]
Unless you know what the symbol means it's not really clear what the bookmark button does

Suggesting a green toast message?

Success haptic too?

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1163)
Device: iPhone 6s Plus (iOS 11.1)
TestFlight: true
</pre>
</details>

**Comment by BasThomas** [comment]
Think it has a haptic when adding, but not removing

**Comment by BasThomas** [comment]
Don't really know if it really needs a haptic as you already have the button change honestly

**Comment by rnystrom** [comment]
I feel like the bookmark icon is pretty universal? Also the icon is the same as the tab, so it shouldn’t be hard to connect the dots.

Not married to haptics tho.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Probably just me then, never used that icon before 😅 All good

**Comment by Sherlouk** [comment]
🤔

**Comment by rnystrom** [comment]
Recording App Previews 😄

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
