### ISSUE TITLE
Comment collapse feature?

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#928]
Would anyone find this useful? Imagine being able to tap the header of a comment and it folds to just the header. Maybe a little arrow indicating it’s collapsed.

I find this useful with huge comment threads on stuff like Hacker News and Reddit. Obviously there are no threads (barring PR comments). But maybe collapsing Long comments would be nice?

We already have collapse-on-load functionality. This could replace that entirely, or just compliment it.

Useful at all?

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1179)
Device: iPhone 7 Plus (iOS 11.1.1)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment]
I don't directly see me using this, but don't think it would hurt either. Would definitely be nice to play around with in a beta to see how useful it is!
