### ISSUE TITLE
New editing controls

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#929]
I think I solved our collaborator issues. We will def need to make another request to get collab information, but that’s only complicated now because these controls are placed with each unit (eg labels).

Instead, I propose we move all admin/collab controls to one place. It can start off as a single button that says “Edit” and a down carrot. Tap the cell and it unfolds to show all available editing controls.

- Edit Labels
- Edit Assignees
- etc

This gives us a place to keep expanding admin controls. Maybe eventually we move open/close here too?

Putting this in a. Single unit means we only need to update with a single new model once the collab endpoint returns, making this setup very simple.

I’ll post back with some drawings.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1179)
Device: iPhone 7 Plus (iOS 11.1.1)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment]
I was thinking about doing exactly that. Not entirely sure about the close/open though; locking can probably move there just fine. 👍👍👍👍

**Comment by rnystrom** [comment]
Awesome @BasThomas I’ll just add a new `UICollectionViewCell` and **model**, then ship!!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Testing

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Have you been testing here @rnystrom? I've been getting ghost notifications 😂

**Comment by rnystrom** [comment]
Lol yup, used this for the App Preview

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
