### ISSUE TITLE
Bookmarks deleted between beta builds

### ISSUE THREAD

**Issue by bigfish24** [rnystrom/GitHawk#930]
When I update to a new beta, the bookmarks disappear. Is this expected?

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1179)
Device: iPhone 7 Plus (iOS 11.1)
TestFlight: true
</pre>
</details>

**Comment by Sherlouk** [comment]
Yeah we have a few issues about this, the latest being #860 😞 

It is expected due to the work on the way they're stored and the model changes, this is just part of the development cycle unfortunately!

It should be stable in between app-store releases

**Comment by bigfish24** [comment]
Ok, this one is a bit personal given I work at Realm and data persistence is our thing. Perhaps this could be a good fit?

**Comment by rnystrom** [comment]
@bigfish24 that'd be pretty awesome!
