### ISSUE TITLE
Remotely managed "inbox zero" emoji and message

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#931]
For my talk at Swift Summit, I demo'd playing w/ Firebase to remotely manage and configure content. It was super easy to use, and got me thinking about doing this in GitHawk. I had an idea just now:

What if we remotely update the "Inbox Zero" message? I had the thought b/c Thanksgiving is coming up, and it would be cool to change the message to 🦃  and "Happy Thanksgiving!" or something cute.

Too late to launch this for Thanksgiving, but we could do this over the holidays.

Thoughts? @BasThomas @Sherlouk

**Comment by Sherlouk** [comment]
Nice idea, plenty of use cases over time!

I'd be up for it

**Comment by BasThomas** [comment]
Yes, that be so awesome! The Mailbox style possibilities are itching already. Go go go!

**Comment by rnystrom** [comment]
I'm gonna hack at this soon. It'll be fun to add a few easter eggs and "low impact" delight. Sometimes I get too into maxing every feature's impact and ignoring small things like this that add charm. Will be fun 😍

**Comment by BasThomas** [comment]
This is so super cool. It’s lovely. One small thing: maybe we should fetch / check this at app start? I just cleared my notifications and it showed the 🎉 for a second before switching to the ⛄️

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Good call, I put it on the section controller init so we aren’t always fetching, but maybe that doesn’t matter?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
