### ISSUE TITLE
Accessibility test bed

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#933]
Play around here!

**Comment by Sherlouk** [comment]
Hi how am I doing?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
😬 😬 @rnystrom (Out of VO atm) the above comment is not being escaped properly which is rendering some of our HTML code into the comment. That's really bad 😅

**Comment by rnystrom** [comment]
@Sherlouk I checked the raw message and its actually missing the `>` at the end. Edit slip?

**Comment by Sherlouk** [comment]
@rnystrom The edit was intentional to see if I could do it, I didn't expect deleting that character to do that though!

I've raised #938 to fix it

**Comment by rnystrom** [comment]
Test

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Sorry for the spam, testing assignment

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Closing this one for now, can always reopen if we want to do some more testing in the future :)
