### ISSUE TITLE
Can’t see white label dots

### ISSUE THREAD

**Issue by joerocca** [rnystrom/GitHawk#935]
White label dots are the same color as the issue/PR collection view background. Maybe a slight shadow on the dot cells?

![GitHawk Upload by joerocca](https://i.imgur.com/v4zxGc6.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Great callout, sucks for accessibility too. A pixel-thin, light color border would be great.

**Comment by BasThomas** [comment]
Fixed in #1135

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
