### ISSUE TITLE
Upload image action button broken on comment and edit

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#937]
@Sherlouk the button works on New Issue but just no-ops on everything else 😣

Probably in 1.12 that I just released

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1183)
Device: iPhone X (iOS 11.1.1)
TestFlight: false
</pre>
</details>

**Comment by Sherlouk** [comment]
😬 wut I tested this 🤔 will take a look ASAP

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Yano that moment when you have a commit on a branch that you never pushed up? Yea that's me - Pushing fix now.
