### ISSUE TITLE
Missing Notifications

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#939]
GitHawk had 2 less notifications than I had on the web version 😞 I know we've had this in the past, but has anyone else experienced it recently?

**Comment by BasThomas** [comment]
Not experienced it recently. Were those on web notifications for code changes? I think these might be ignored / wrongly parsed on our side and slip through?

**Comment by Sherlouk** [comment]
Yea commits in PRs, intriguing

**Comment by BasThomas** [comment]
Think this is a different issue than them not appearing until kill+relaunch, but definitely a bug we should fix. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
I did kill + relaunch though 🤔 😞

**Comment by BasThomas** [comment]
I know - but that didn’t fix it right?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Nope, still didn't appear! #blameGitHubAPI

**Comment by BasThomas** [comment]
Exactly. Thing is - I don't think it's the fault of the GitHub API, but us. **At least** we get the notification count from GitHub...

**Comment by BasThomas** [comment]
See also [here](https://github.com/rnystrom/GitHawk/issues/121#issuecomment-333028179)

**Comment by Sherlouk** [comment]
Let's keep discussion in 121 then to follow this (didn't see that issue!)

**Comment by Sherlouk** [comment]
@BasThomas Reason for re-open? Fix is in :)

**Comment by BasThomas** [comment]
Wait what where?!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Nvm, I see it now (#949)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
