### ISSUE TITLE
Copy comment text

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#945]
Add an option to copy just the comment text.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1179)
Device: iPhone X (iOS 11.1.1)
TestFlight: true
</pre>
</details>

**Comment by Sherlouk** [comment]
Dupe #609?

**Comment by BasThomas** [comment]
Oops

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
