### ISSUE TITLE
Optimistic update puts close event above comment

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#947]
Here I commented, then closed. Optimistic state is the other way around (it inserted the close event above the comment)

Also: check the top closed label being truncated for whatever reason

![GitHawk Upload by BasThomas](https://i.imgur.com/OJCbHS4.jpg)

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.0 (1179)
Device: iPhone X (iOS 11.1.1)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
I'm not sure about the label tho. Looks like the cell wasn't laid out again. Does that happen often?

**Comment by BasThomas** [comment]
Nah, only saw it this once. Don’t think we need to worry about it. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
