### ISSUE TITLE
Redesign labels cell as h-scroll

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#951]
Instead of the dots + tap-expand, what if we just make an h-scroll unit to display all the labels? Might be a better use of available whitespace, and easier to use.

Thoughts?

One constraint is that cells must be dynamically sized (prob not estimated size b/c of issues, but maybe it'd work here?). Makes it slightly more complicated.

**Comment by joerocca** [comment]
I like this idea! I do like that tapping to expand allows me to see all the labels in once glance/step though. If an issue has a bunch of labels, you'd have to scroll pretty far and I feel like that could get annoying.

**Comment by rnystrom** [comment]
Ya, that's true. Not sure how often it'll happen, but it could. I wonder how complicated it'd be to have a wrapping labels unit instead of h scroll?

**Comment by Sherlouk** [comment]
@rnystrom Almost want something like this: https://github.com/ElaWorkshop/TagListView

**Comment by rnystrom** [comment]
Ya! Trickiest part, like most things with `UICollectionView`, is finding the cell height.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Wouldn't the height be the same for every cell? `1 * Font.lineHeight` - We wouldn't want labels to wrap!

One nice thing about the TagListView as well is the ability to add actions to the labels (aka go and see all issues with the same label - do we have an issue for this?) and an optional 'x' button (aka remove this label 😉)

**Comment by rnystrom** [comment]
Actually wrapping would be cool, otherwise a plain h-scroll `UICollectionView` would be ez.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
To be clear: Wrapping of all items, yaa! But not wrapping of a single cell/label?

**Comment by rnystrom** [comment]
I confuse

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
