### ISSUE TITLE
Add “no description given" for empty root comments

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#959]
Eg. https://github.com/MessageKit/MessageKit/issues/354

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.1 (1185)
Device: iPhone X (iOS 11.1.1)
TestFlight: true
</pre>
</details>

**Comment by rnystrom** [comment]
If someone wants to peel this off, probably pretty easy

**Comment by BasThomas** [comment]
Test comment

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
OK so this is a bit more tricky as we need to know if the markdown is the root comment does not render anything that's visible to the user (to mimic GitHub). For now, I will only check if the root comment is completely empty.

**Comment by BasThomas** [comment]
Already in.
