### ISSUE TITLE
Add a Search tab

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#96]
Search all of Github. Maybe limit to just repositories at first?

**Comment by BasThomas** [comment]
What would be the purpose of this? I was actually thinking of adding search to find a specific issue (which can come in handy in the "read" section)

**Comment by rnystrom** [comment]
@BasThomas searching for a repo (same as GH search)

**Comment by Sherlouk** [comment]
@rnystrom Would we want some sort of Tab Bar Controller to have tabs for notifications/search/my repos etc?

**Comment by rnystrom** [comment]
@Sherlouk the way I did this before was use the root controller manager (or w/e I called it) to configure the tab VCs (it did it on user change too). I want to avoid subclassing where possible.

**Comment by Sherlouk** [comment]
@rnystrom Feel free to check my branch but got it working; definitely needs cleaning up but just embedded the nav bar for the left view - seems to work fine
