### ISSUE TITLE
Should we add a neat onboarding flow?

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#962]
I've seen some good ones. Something that isn't too verbose or in-your-face. But maybe could add a little charm?

Also might be a lot of effort for something people will only see once. Probably only worth doing if we have a grand-slam idea.

**Comment by rnystrom** [comment]
e.g. co worker showed me the coolest onboarding flow I've seen https://telegram.org/

**Comment by BasThomas** [comment]
Also always liked the IFTTT one, https://github.com/IFTTT/JazzHands / https://github.com/IFTTT/RazzleDazzle

**Comment by rnystrom** [comment]
nah
