### ISSUE TITLE
Manage not available when part of organisation

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#963]
I’m a member of MessageKit org but can’t manage any of the issues/prs even though I should be able to!

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.13.0 (1190)
Device: iPhone 6s Plus (iOS 11.2)
TestFlight: true
</pre>
</details>

**Comment by Sherlouk** [comment]
@rnystrom 

https://github.com/rnystrom/GitHawk/blob/710dae03883a56fcf2cf277cf0579602e4fa0d78/Classes/Issues/GithubClient%2BIssues.swift#L282-L300

Looks like the current API we use is very much just for collaborators

Maybe we should look to refactor that a tiny bit to use this endpoint:

https://developer.github.com/v3/repos/collaborators/#review-a-users-permission-level

This will give us the users permission level out of `admin`, `read`, `write` or `none`. Where write (I assume) is labels/milestones but covering cases like teams/collab/owner/orgs/etc

**Comment by rnystrom** [comment]
@Sherlouk did you test out that API to check your permissions on that repo? So you should have `write` permissions? I just want to make sure that returns the proper permissions before changing things.

**Comment by rnystrom** [comment]
I just tried to check your permissions and got a 403 forbidden

```
{
    "message": "Must have push access to view collaborator permission.",
    "documentation_url": "https://developer.github.com/v3/repos/collaborators/#review-a-users-permission-level"
}
```

Do you have push access to that repo?

**Comment by rnystrom** [comment]
What about using the team API?

https://developer.github.com/v3/orgs/teams/#get-team-membership

@Sherlouk can you try accessing your membership for that org?

https://api.github.com/teams/30243544/memberships/sherlouk

**Comment by Sherlouk** [comment]
@rnystrom 

https://api.github.com/repos/messagekit/messagekit/collaborators/sherlouk/permission?access_token=revoked
```json
{
  "permission": "write",
  "user": {
    "login": "Sherlouk",
    ...
    "type": "User",
    "site_admin": false
  }
}
```

https://api.github.com/teams/30243544/memberships/sherlouk
Just giving me a Not Found error

**Comment by rnystrom** [comment]
Great!!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Brill!

I've confirmed it on MessageKit (Part of the Org), IGListKit (Collab within an Org), GitHawk (Collab) which are all "write" as well as one of my repos where it's "admin". Both of these need access to manage :)

Looking forward to it
