### ISSUE TITLE
Can I use this project to make an app that supports Gitlab?

### ISSUE THREAD

**Issue by jeop10** [rnystrom/GitHawk#965]
I really like how this app works but at work we use self hosted gitlab is it possible that I use this project as a starting point for a new app that supports gitlab? Thanks in advance.

**Comment by Sherlouk** [comment]
There's an open discussion for this here: #408 - Currently the scope of the project is limited to GitHub (maybe looking into Enterprise) but there's definitely nothing stopping you from forking off and making changes to support other hosts!

**Comment by jeop10** [comment]
Thanks @Sherlouk I'll take a look on the other issue.
