### ISSUE TITLE
Bookmarks tab search for placeholder says “Search Bookmarks”

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#969]
<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.13.0 (1191)
Device: iPhone X (iOS 11.1.1)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment]
What should it be?

**Comment by rnystrom** [comment]
Title should read “should say” 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
Casual reminders that much like tweets, we need a way to edit titles 😅

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Lol so true. I’ll queue this up in release milestones. Would love to knock out assignees and reviewers next release, then sneak in title editing whenever.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
