### ISSUE TITLE
Add native error for empty comments (that are not root)

### ISSUE THREAD

**Issue by BasThomas** [rnystrom/GitHawk#976]
We should either show a local error toast containing the message (like with the empty title when creating an issue) (this might be fragile if GitHub changes this in the future though, allowing empty comments for some reason).

Or we can check if, based on the error code / headers, we can display something more useful to the user (instead of the generic "Something went wrong.")

**Comment by rnystrom** [comment]
Is this the same as #974 but for all comments? Should we close then?

**Comment by BasThomas** [comment]
No; non-root comments cannot be blank, thus you will get an error from the API when you try to do so (read: edit a comment and remove everything). Same thing happens on web.
