### ISSUE TITLE
Ghost notifications

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#978]
It appears as if I’m getting notifications for super basic reasons like reactions, it may be my imagination!

I’ll take an action to see if that’s true, as it might be related to removing the change which enables code changes to trigger notifications

May need a whitelist of reasons.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.13.0 (1192)
Device: iPhone 6s Plus (iOS 11.2)
TestFlight: true
</pre>
</details>

**Comment by Sherlouk** [comment]
Can’t assign yet but this is mine 😂

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lDiverse** [comment]
Test12

**Comment by Sherlouk** [comment]
Hmm will monitor, but I've tried a few different things n looks like it may have just been an event that GitHawk doesn't display 🤷‍♂️

**Comment by BasThomas** [comment]
Or a comment that was removed after?
