### ISSUE TITLE
Better Secrets.swift setup

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#986]
We've tried this before but haven't landed on something simple. Here's what I'd love to see:

- Set environment variables on command line
- Compiler **fails** when variables haven't been set

Then it should be basically impossible to screw up shipping a beta or App Store build w/out keys.

**Comment by Sherlouk** [comment]
Would be super simple to write a quick check in fastlane to prevent shipping w/out keys - but honestly I'd rather not have to define keys every time I switch branches!

If they were to read from environment variables, they could be defined via the scheme (which we don't share at the moment), BuddyBuild can define them itself using the secure variables area, and we could do something different for Fastlane to inject them maybe from a `secrets.json` which is in gitignore?

As I said on a different issue (can't remember which one) the keys are only needed for login, once you're in you're good - so for me I basically never need to put them in as I'm logged in on all the sims I regularly use!
