### ISSUE TITLE
Show/Browse my stared or my repo

### ISSUE THREAD

**Issue by MostafaAlaa2016** [rnystrom/GitHawk#990]
How can I Show/Browse my stared or my repo?

Also, how can I set notifications for some repos for any issues or requests to come into inbox?

I am really love the app and need to know how to use it

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.12.1 (1185)
Device: iPhone 8 Plus (iOS 11.1.2)
TestFlight: true
</pre>
</details>

**Comment by BasThomas** [comment]
You can search for a repository under "Search" and then bookmark it, making it available under the Bookmark tab. Does that help?

From within the app, you can't subscribe/unsubscribe to issues/PRs yet. I think that's what you're referring to, right?

**Comment by MostafaAlaa2016** [comment]
Thanks very much for fast reply. I believe if you can add the below features it will be great 
- View My repo
- View Stars repo
- subscribe/unsubscribe to issues/PRs

Thanks 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
We believe they're great features too! There are issues open for them below:

#95 Repositories Tab - Your/Starred Repos
#351 #352 - Subscribe/Unsubscribe to Issues/PRs

If you have further suggestions feel free to search our open feature requests and contribute further suggestions, or create a new one if it doesn't exist!

**Comment by MostafaAlaa2016** [comment]
Thanks waiting for the implementation for these features 👍🏻

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
