### ISSUE TITLE
Blow away bitmap caches on memory warning

### ISSUE THREAD

**Issue by rnystrom** [rnystrom/GitHawk#992]
`NSAttributedStringSizing` should dump it’s cache on memory warning. Only for bitmaps tho.

<details>
<summary>Bug Report Dump (Auto-generated)</summary>
<pre>
Version 1.13.0 (1197)
Device: iPhone X (iOS 11.1.1)
TestFlight: false
</pre>
</details>

**Comment by BasThomas** [comment]
Duplicate of #677?

**Comment by rnystrom** [comment]
Oops ya. Closing that one since this has more detail.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
