### ISSUE TITLE
Basic Analytics

### ISSUE THREAD

**Issue by Sherlouk** [rnystrom/GitHawk#998]
From experience iTC doesn't really give you the drill-down on analytics that we'd really like

Following the [localization discussion](https://twitter.com/_ryannystrom/status/932301382043996160) on Twitter, it's maybe worth adding a couple of our own analytics calls?

Namely: Device Language & Accessibility Preferences

If we did, should probably be opt-in only

(Obviously this wouldn't help with trying to enter new markets, but understanding the needs of the people who already use it)

**Comment by rnystrom** [comment]
Got a fav default suite? I’ll have to backtrack the App Store description that says “no analytics” haha, but I agree it’d be nice to have better demographics and info.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sherlouk** [comment]
I'm easy really, not that fussed but it might actually be nice if we're putting a bunch of effort into accessibility that there's a reason 😅

Would probably say Fabric, mainly because public crash reports too 🤷‍♂️ I'm not too familiar with the free solutions out there though may be a better one
